### ISSUE TITLE
为啥MADDPG这个example在我的电脑用GPU反而比不用GPU还慢？

### ISSUE THREAD

**Issue by amocken** [PaddlePaddle/PARL#1010]
我在程序的开头加上`paddle.device.set_device ('cpu')`之后，运行速度瞬间达到了原来的2.6倍。原来用时约26分钟，修改之后用时约10分钟。而且内存占用从一千多兆降到了一百多兆😓
我运行的是最新版的example，parl版本是2.1，paddlepaddle版本是2.3.2，win 11 22h2，GPU 是英伟达的MX450，CPU是i7 1165g7，cudatoolkit版本是11.6，cuda版本是12.0
GPU Compute Capability: 7.5, Driver API Version: 12.0, Runtime API Version: 11.6

**Comment by TomorrowIsAnOtherDay** [comment]
感谢反馈。下周上班了，我找飞桨框架的开发同学一起看下。

**Comment by amocken** [comment]
> 感谢反馈。下周上班了，我找飞桨框架的开发同学一起看下。
请问你们那边复现也有这个问题吗？

**Comment by amocken** [comment]
> 感谢反馈。下周上班了，我找飞桨框架的开发同学一起看下。

请问你们那边能复现出这个问题吗？

**Comment by TomorrowIsAnOtherDay** [comment]
抱歉上周漏了这个信息，我们正在借windows机器测试哈，会尽快反馈的。

**Comment by TomorrowIsAnOtherDay** [comment]
hello，我们测试了下相关的代码。目前的结论和你是相符的。
我们猜测是网络太简单了，GPU相比CPU的计算优势几乎为0，同时，因为GPU还需要把数据从内存加载到显存，这需要额外的时间，导致GPU的耗时更长了。
如果想体现GPU的优势，建议你把网络搞得更深层（大）一点。

**Comment by amocken** [comment]
> hello，我们测试了下相关的代码。目前的结论和你是相符的。 我们猜测是网络太简单了，GPU相比CPU的计算优势几乎为0，同时，因为GPU还需要把数据从内存加载到显存，这需要额外的时间，导致GPU的耗时更长了。 如果想体现GPU的优势，建议你把网络搞得更深层（大）一点。

好的，谢谢
