### ISSUE TITLE
???

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/PARL#1011]
不知道pytorch的强化学习库多久更新一次,反正飞桨的parl更新是真心慢.飞桨那么多仓库,还有哪个仓库比parl更新更慢的吗?超级少吧.
parl2.1的更新内容,哪里可以看到中文版本?不懂英文.
能否透露一下,parl17个月才更新一个2.1版本,内部是在憋什么大招?
我发觉,飞桨很多仓库,一个重要任务就是复现最近热门模型,parl17个月才更新,肯定没做这件事吧.clas,det,seg,等等仓库,基本更新内容都是提供一些新模型.

**Comment by TomorrowIsAnOtherDay** [comment]
不懂英文不是开一个issue的理由。
