### ISSUE TITLE
模型的保存和加载

### ISSUE THREAD

**Issue by vigorPan** [PaddlePaddle/PARL#1014]
训练好的模型如何保存和加载只找到了agent.save这个函数save出来了learn_program和pred_program两个文件，我现在如何load这两个问题？？？

**Comment by TomorrowIsAnOtherDay** [comment]
你这个save保留两个program的，应该是以前fluid的代码，可以参考这个函数：
https://github.com/PaddlePaddle/PARL/blob/9da7f2d3ff44319dd7bf880de48a5e9f9a594256/parl/core/fluid/agent.py#L206

另外不推荐使用静态图的parl代码了，建议直接使用动态图的。
