### ISSUE TITLE
萌新请问如何解决

### ISSUE THREAD

**Issue by G1aogiao** [PaddlePaddle/PARL#1021]
请问作业的代码在Windows上是用cmd跑的还是有别的代码软件跑的，cmd运行结果如下怎么解决
![1670681973086](https://user-images.githubusercontent.com/120259072/206859953-70f8cd1d-e3e3-4a4b-ae38-0df0f85f7e29.jpg)

**Comment by TomorrowIsAnOtherDay** [comment]
你这个是网络问题。
可以参考这个页面：
https://github.com/PaddlePaddle/PARL/blob/develop/docs/zh_CN/Overview.md#%E5%AE%89%E8%A3%85-1
