### ISSUE TITLE
benchmark如何复现

### ISSUE THREAD

**Issue by Littlehong-ai** [PaddlePaddle/PARL#1027]
请问各位大佬如何复现模型效果？代码中是不是没指定随机种子之类的

**Comment by Littlehong-ai** [comment]
例如，我每次运行benchmark/fluid/DQN下的train.py 都会得到不一致的test_reward

**Comment by TomorrowIsAnOtherDay** [comment]
这个是符合预期的，RL在训练过程中需要随机探索，会有一定的随机性。
如果想要稳定复现特定的效果，可以在程序执行前指定numpy、paddle/torch、random、gym的随机种子。

**Comment by Littlehong-ai** [comment]
> 这个是符合预期的，RL在训练过程中需要随机探索，会有一定的随机性。 如果想要稳定复现特定的效果，可以在程序执行前指定numpy、paddle/torch、random、gym的随机种子。
