### ISSUE TITLE
如何在slurm系统管理的服务器上提交PARL任务

### ISSUE THREAD

**Issue by jiangzhangze** [PaddlePaddle/PARL#1056]
如题，只能使用sbatch命令才能提交计算节点。

**Comment by TomorrowIsAnOtherDay** [comment]
hello，如果是百度内部集群的使用，请联系zhoubo01

**Comment by jiangzhangze** [comment]
> hello，如果是百度内部集群的使用，请联系zhoubo01

hello,我使用的不是百度内部集群，是学校的。

**Comment by TomorrowIsAnOtherDay** [comment]
噢，那标题中的slurm系统是指学校的系统吗？

**Comment by jiangzhangze** [comment]
> 噢，那标题中的slurm系统是指学校的系统吗？

对

**Comment by TomorrowIsAnOtherDay** [comment]
我不了解你们学校的系统，所以这个问题我无法回答。
