### ISSUE TITLE
provide an example for saving and restoring trained model

### ISSUE THREAD

**Issue by pxlong** [PaddlePaddle/PARL#106]
Can we add an example for illustrating how to save and restore the trained model?
I think it is a basic feature of a RL lib and it will be helpful for newbies like me to use PARL in our projects.

**Comment by TomorrowIsAnOtherDay** [comment]
Thanks for suggesting!
We discussed this before, and agreed that we can add some APIs in `parl.Agent` such that users can save and restore the parameters of the agent.
We will be working on this new feature, and provide new APIs as soon as possible.

**Comment by pxlong** [comment]
I am new to PARL (and Paddle), but I would love to contribute to it. 
Please let me know if I can be of any help.

**Comment by TomorrowIsAnOtherDay** [comment]
**Great!!!**

Currently we are preparing for the release of PARL 1.2, which includes:
- a more compact API for parallel computation, with a web server monitoring the status of computation resources such as CPU and memory usage.
-  various algorithms relative to recent research interest such as Evolutional Strategy(ES) and model-based RL.
- a web page with documentation and tutorials.

We hope that you can give us valuable feedback on using PARL in you project!
Feel free to reporte any issues.
