### ISSUE TITLE
pickle的错，无法import parl

### ISSUE THREAD

**Issue by yilongfengshen** [PaddlePaddle/PARL#1075]
在import parl时，报AttributeError: Can't pickle local object 'check_installed_framework.<locals>.check'的错，在parl\utils\utils.py in <module>文件中。

**Comment by TomorrowIsAnOtherDay** [comment]
感谢你的反馈，麻烦提供下你的py版本、运行系统、以及parl版本。

**Comment by yilongfengshen** [comment]
我用的是python 3.9.13，os是Windows11，parl的版本是2.2。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PARL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月12日(星期天) 晚上10:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PARL] pickle的错，无法import parl (Issue #1075)





 
感谢你的反馈，麻烦提供下你的py版本、运行系统、以及parl版本。

**Comment by TomorrowIsAnOtherDay** [comment]
好的，我们今天确认下问题并修复，在这期间可以使用parl2.1

**Comment by yilongfengshen** [comment]
好的，感谢



---原始邮件---
发件人: "Bo ***@***.***&gt;
发送时间: 2023年3月13日(周一) 上午9:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PARL] pickle的错，无法import parl (Issue #1075)




 
好的，我们今天确认下问题并修复，在这期间可以使用parl2.1

**Comment by yilongfengshen** [comment]
好的，我再问一下如何下载parl2.1




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PARL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月13日(星期一) 上午9:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PARL] pickle的错，无法import parl (Issue #1075)





 
好的，我们今天确认下问题并修复，在这期间可以使用parl2.1

**Comment by TomorrowIsAnOtherDay** [comment]
pip install parl==2.1
或者
python -m pip install parl==2.1

**Comment by yilongfengshen** [comment]
我已经安装好了，我在使用2.1时，'Agent' object has no attribute 'fluid_executor'，fluid_executor是被弃用了吗，请问用什么替代的






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PARL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月13日(星期一) 上午10:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PARL] pickle的错，无法import parl (Issue #1075)





 
pip install parl==2.1
 或者
 python -m pip install parl==2.1

**Comment by TomorrowIsAnOtherDay** [comment]
是的，fluid_executor已经废弃了，这是静态图时代的接口。
parl在2.0开始就全面转移到动态图了，如果希望继续使用fluid_executor，可以安装1.4及以下的版本。

**Comment by yilongfengshen** [comment]
无法安装1.4及以下版本，请问有什么吗，直接pip install parl==1.4会失败。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PARL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月13日(星期一) 上午10:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PARL] pickle的错，无法import parl (Issue #1075)





 
是的，fluid_executor已经废弃了，这是静态图时代的接口。
 parl在2.0开始就全面转移到动态图了，如果希望继续使用fluid_executor，可以安装1.4及以下的版本。

**Comment by TomorrowIsAnOtherDay** [comment]
噢，是因为parl在发行1.4的时候，py39还没出来。。你在py39的环境下是找不到1.4版本的。这样的话，你还得降级python。建议采用anaconda来配置不同版本python环境。

**Comment by yilongfengshen** [comment]
官方现在有什么最新学习parl的文档或者视频教程吗，我自己改一下代码，或者1.4版需要什么版本的python






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PARL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月13日(星期一) 上午10:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PARL] pickle的错，无法import parl (Issue #1075)





 
噢，是因为parl在发行1.4的时候，py39还没出来。。你在py39的环境下是找不到1.4版本的。这样的话，你还得降级python。建议采用anaconda来配置不同版本python环境。

**Comment by TomorrowIsAnOtherDay** [comment]
科老师的教程是3年前的了，关于最新学习文档的话，目前我们建议直接看文档+quick_start的example来熟悉动态图的parl。
中文文档可以参考这里：https://github.com/PaddlePaddle/PARL/blob/develop/docs/zh_CN/Overview.md
英文的看这里：https://parl.readthedocs.io/en/latest/index.html


另外parl1.4版本需要python3.7.

**Comment by yilongfengshen** [comment]
已收到，感谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PARL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月13日(星期一) 上午10:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PARL] pickle的错，无法import parl (Issue #1075)





 
科老师的教程是3年前的了，关于最新学习文档的话，目前我们建议直接看文档+quick_start的example来熟悉动态图的parl。
 中文文档可以参考这里：https://github.com/PaddlePaddle/PARL/blob/develop/docs/zh_CN/Overview.md
 英文的看这里：https://parl.readthedocs.io/en/latest/index.html
 
另外parl1.4版本需要python3.7.
