### ISSUE TITLE
IDE无法运行安装PARL

### ISSUE THREAD

**Issue by Anncastle** [PaddlePaddle/PARL#1090]
代码报错：

`import parl`

pycharm下子进程中不能input输入，会报错EOFError: EOF when reading a line，因为子进程中没有像我们主进程这样的在pycharm下的控制台可以输入东西的地方

![976092a76e50009872d5bdf5d59b107a](https://user-images.githubusercontent.com/33474645/230852974-d80f296b-9169-418d-b7bf-8ba08bc0b665.png)

**Comment by ddz-mark** [comment]
同样的问题，pip安装过程是正常的

**Comment by TomorrowIsAnOtherDay** [comment]
感谢两位的反馈，请提供下你们的操作系统信息。

**Comment by ddz-mark** [comment]
mac python==3.8.2 paddlepaddle==2.3.2 parl==2.2.1 时出现上述问题。
将 parl==2.1 则解决问题。

**Comment by TomorrowIsAnOtherDay** [comment]
好的，我们明天定位下，先下班了：）

**Comment by TomorrowIsAnOtherDay** [comment]
@ddz-mark  hello，刚合并了@Anncastle 提交的修复代码，请尝试安装下develop分支的代码试试看。

**Comment by Anncastle** [comment]
> @ddz-mark hello，刚合并了@Anncastle 提交的修复代码，请尝试安装下develop分支的代码试试看。

这个会从develop分支merge到master嘛？不然在其他环境下还是不方便

**Comment by TomorrowIsAnOtherDay** [comment]
我们的默认开发分支就是develop分支的，用户git clone下来的就是develop分支：）
