### ISSUE TITLE
pip安装问题

### ISSUE THREAD

**Issue by chunda-zhang** [PaddlePaddle/PARL#1136]
![image](https://github.com/PaddlePaddle/PARL/assets/61903695/40a53d20-a2c2-422b-8fd1-f7d2119934c0)
求助：pip 安装就出现这个问题为什么？vs也下了

**Comment by TomorrowIsAnOtherDay** [comment]
Python 版本是多少呢？

**Comment by chunda-zhang** [comment]
3.11.5

**Comment by chunda-zhang** [comment]
> Python 版本是多少呢？

3.11.5

**Comment by TomorrowIsAnOtherDay** [comment]
看报错推测是第三方库不支持3.11.5，建议使用3.7/8版本的Python重试下。

**Comment by chunda-zhang** [comment]
> 看报错推测是第三方库不支持3.11.5，建议使用3.7/8版本的Python重试下。

强  3.7版本  已安装  谢谢
