### ISSUE TITLE
ValueError: optimizer got an empty parameter list

### ISSUE THREAD

**Issue by luweiagi** [PaddlePaddle/PARL#1150]
![image](https://github.com/PaddlePaddle/PARL/assets/19629731/d8b0a984-fc33-406b-b7a6-45a93718fa2e)

**Comment by TomorrowIsAnOtherDay** [comment]
Can you run the official DDPG? This error doesn't seem to be caused by PARL, but rather because the network you defined doesn't have optimizable neural network parameters.

**Comment by kzhdlmu** [comment]
I got the same Error
