### ISSUE TITLE
Find a bug in layer_warppers

### ISSUE THREAD

**Issue by a-big-tomato** [PaddlePaddle/PARL#147]
![image](https://user-images.githubusercontent.com/36156553/64309677-efced400-cfcf-11e9-96cf-742a4806e35d.png)
it should be
```
bias_attr=self.attr_holder.bias_attr
```
not 

```
bias_attr=self.bias_attr
```

**Comment by zenghsh3** [comment]
Thank you for pointing out the bug, we will fix it now.
