### ISSUE TITLE
Cannot run IMPALA in conda environment

### ISSUE THREAD

**Issue by mxfengustc** [PaddlePaddle/PARL#151]
I cannot run IMPALA algorithm in my docker's conda environment.
My docker container is built on nvidia/cuda:18.04 with anaconda 5.3.0, and i create an environment named dist-rl with installing python=3.7 paddlepaddle-gpu=1.5.2 cudatoolkit=10.0 via conda and installing  parl/gym[atari]/opencv-python via pip 
When i run `python train.py` after starting the cpu cluster using `xparl start --port 8010 --cpu_num 5`(i also changed the number of cpus in impala_config.py), it occurred errors as follows:

![Screenshot from 2019-09-12 20-12-06](https://user-images.githubusercontent.com/37872960/64783624-dc58d580-d59a-11e9-8108-18c6db1c043c.png)
![Screenshot from 2019-09-12 20-12-33](https://user-images.githubusercontent.com/37872960/64783635-e1b62000-d59a-11e9-93a3-322f532285d5.png)
![Screenshot from 2019-09-12 20-12-57](https://user-images.githubusercontent.com/37872960/64783639-e549a700-d59a-11e9-99b7-72cce782c466.png)

It seems that the main error is `paddle.fluid.core_avx.EnforceNotMet: Invoke operator elementwise_mul error.`, but i don't know how to deal with it.
Thanks very much~

**Comment by zenghsh3** [comment]
这边测试了下发现paddle>=1.5.1版本时，在GPU上训练时会有这个问题，CPU能正常训练(export CUDA_VISIBLE_DEVICES="")，这个问题应该跟Paddle的这个issue类似：
https://github.com/PaddlePaddle/Paddle/issues/19628

这边先问下Paddle开发者这个issue解决的进展，你也可以先尝试用CPU训练先。

**Comment by TomorrowIsAnOtherDay** [comment]
Thanks for raising the issue. Can you run the IMPALA algorithm in your environment when setting `CUDA_VISIBLE_DEVICES=""` ?

**Comment by mxfengustc** [comment]
@TomorrowIsAnOtherDay When I only use CPU to run it, no errors occurred.

**Comment by yobobobo** [comment]
I can run the IMPALA algorithm with GPU in the anaconda environment.
Some packages in your anaconda environment might not be compatible with the paddle1.5.1. I have exported my environment into a yml file. 
To copy my environment, copy the following lines into a file named `parl.yml`, and run the command:
 `conda env create -f parl.yml`

```
name: parl
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py36_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - ncurses=6.1=he6710b0_1
  - openssl=1.1.1b=h7b6447c_1
  - pip=19.1=py36_0
  - python=3.6.8=h0371630_0
  - readline=7.0=h7b6447c_5
  - setuptools=41.0.0=py36_0
  - sqlite=3.28.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.33.1=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.7.1
    - aspy-yaml==1.3.0
    - atari-py==0.1.7
    - cffi==1.12.3
    - cfgv==2.0.0
    - chardet==3.0.4
    - click==7.0
    - cloudpickle==1.2.1
    - cycler==0.10.0
    - cython==0.29.12
    - decorator==4.4.0
    - funcsigs==1.0.2
    - future==0.17.1
    - glfw==1.8.2
    - grpcio==1.22.0
    - gym==0.12.1
    - identify==1.4.5
    - idna==2.8
    - imageio==2.5.0
    - importlib-metadata==0.18
    - importlib-resources==1.0.2
    - kiwisolver==1.1.0
    - lockfile==0.12.2
    - markdown==3.1.1
    - matplotlib==2.2.3
    - mujoco-py==0.5.1
    - nltk==3.4
    - nodeenv==1.3.3
    - numpy==1.16.3
    - opencv-python==4.1.0.25
    - paddlepaddle-gpu==1.5.1.post97
    - parl==1.1.2
    - pillow==6.0.0
    - pre-commit==1.17.0
    - prettytable==0.7.2
    - protobuf==3.7.1
    - pyarrow==0.13.0
    - pycparser==2.19
    - pyglet==1.3.2
    - pyopengl==3.1.0
    - pyparsing==2.4.0
    - python-dateutil==2.8.0
    - python-graphviz==0.10.1
    - pytz==2019.1
    - pyyaml==5.1
    - pyzmq==18.0.1
    - rarfile==3.0
    - recordio==0.1.7
    - requests==2.22.0
    - scipy==1.2.1
    - singledispatch==3.4.0.3
    - six==1.12.0
    - tb-nightly==1.15.0a20190801
    - tensorboard==1.14.0
    - tensorboardx==1.8
    - termcolor==1.1.0
    - toml==0.10.0
    - tqdm==4.32.2
    - urllib3==1.25.3
    - virtualenv==16.6.2
    - werkzeug==0.15.4
    - yapf==0.24.0
    - zipp==0.5.2
```

**Comment by zenghsh3** [comment]
@mxfengustc Hi, we find that IMPALA example also can run normally when using single GPU to train. You can try to set `export CUDA_VISIBLE_DEVICES=0`.

**Comment by mxfengustc** [comment]
@zenghsh3 Hi,thanks for the advice, now i can run the code~
You can close the issue , and i think that maybe you can communicate with paddlepaddle team to try to solve the problem for getting errors when using multiple gpus.
I offen use some nodes with gpus as actors to sample experiences, i want to know if errors will occur in this setting(actors with gpus)

**Comment by TomorrowIsAnOtherDay** [comment]
Thanks @zenghsh3 for providing the temporary solution. I'm closing the issue as it is not an error of `PARL`. We can confirm that it is a bug of PaddlePaddle. 
We will do following things:
1. assert that only a GPU is being used when running the `IMPALA` algorithm.
2. locate the bug and report it to the Paddle team.

Thanks @mxfengustc  for reporting the issue and @yobobobo  for providing suggestion.
