### ISSUE TITLE
询问关于ZQCNN人脸识别问题

### ISSUE THREAD

**Issue by JinLn** [PaddlePaddle/PARL#161]
你好，我在左庆的ZQCNN文章下见你在PC上运行了，我也在初手ZQCNN。现在我已在ubuntu系统ZQCNN文件中cmake..和make完成，但接下来不知道做哪一步或者怎么做使用这个库对图片进行识别实现。

**Comment by TomorrowIsAnOtherDay** [comment]
I'm closing this issue as it is not a PARL issue.
