### ISSUE TITLE
运行demo出错

### ISSUE THREAD

**Issue by 1145520074** [PaddlePaddle/PARL#169]
在/PARL/examples/QuickStart目录下执行： 
python train.py
W1105 17:30:22.264058 15205 init.cc:212] *** Aborted at 1572946222 (unix time) try "date -d @1572946222" if you are using GNU date ***
W1105 17:30:22.266913 15205 init.cc:212] PC: @                0x0 (unknown)
W1105 17:30:22.267369 15205 init.cc:212] *** SIGSEGV (@0x0) received by PID 15205 (TID 0x7f9838abb740) from PID 0; stack trace: ***
W1105 17:30:22.269906 15205 init.cc:212]     @     0x7f98386a8130 (unknown)
W1105 17:30:22.270401 15205 init.cc:212]     @     0x7f97c49c6a96 pybind11::detail::make_new_python_type()
W1105 17:30:22.270716 15205 init.cc:212]     @     0x7f97c49c81f8 pybind11::detail::generic_type::initialize()
W1105 17:30:22.271059 15205 init.cc:212]     @     0x7f97c4b4e552 _ZN8pybind115enum_IN10onnx_torch20TensorProto_DataTypeEEC1IJEEERKNS_6handleEPKcDpRKT_
W1105 17:30:22.271669 15205 init.cc:212]     @     0x7f97c4b46848 torch::onnx::initONNXBindings()
W1105 17:30:22.272096 15205 init.cc:212]     @     0x7f97c482fc28 initModule()
W1105 17:30:22.275000 15205 init.cc:212]     @     0x7f9838cef335 _PyImport_LoadDynamicModuleWithSpec
W1105 17:30:22.278131 15205 init.cc:212]     @     0x7f9838cef540 _imp_create_dynamic
W1105 17:30:22.281011 15205 init.cc:212]     @     0x7f9838bec711 PyCFunction_Call
W1105 17:30:22.283577 15205 init.cc:212]     @     0x7f9838c9a4ad _PyEval_EvalFrameDefault
W1105 17:30:22.285887 15205 init.cc:212]     @     0x7f9838c698e4 _PyEval_EvalCodeWithName
W1105 17:30:22.288254 15205 init.cc:212]     @     0x7f9838c6a771 fast_function
W1105 17:30:22.290830 15205 init.cc:212]     @     0x7f9838c70505 call_function
W1105 17:30:22.293635 15205 init.cc:212]     @     0x7f9838c9538a _PyEval_EvalFrameDefault
W1105 17:30:22.296411 15205 init.cc:212]     @     0x7f9838c6a53b fast_function
W1105 17:30:22.298804 15205 init.cc:212]     @     0x7f9838c70505 call_function
W1105 17:30:22.301241 15205 init.cc:212]     @     0x7f9838c9538a _PyEval_EvalFrameDefault
W1105 17:30:22.303527 15205 init.cc:212]     @     0x7f9838c6a53b fast_function
W1105 17:30:22.305831 15205 init.cc:212]     @     0x7f9838c70505 call_function
W1105 17:30:22.308269 15205 init.cc:212]     @     0x7f9838c9538a _PyEval_EvalFrameDefault
W1105 17:30:22.310564 15205 init.cc:212]     @     0x7f9838c6a53b fast_function
W1105 17:30:22.312858 15205 init.cc:212]     @     0x7f9838c70505 call_function
W1105 17:30:22.315277 15205 init.cc:212]     @     0x7f9838c9538a _PyEval_EvalFrameDefault
W1105 17:30:22.317591 15205 init.cc:212]     @     0x7f9838c6a53b fast_function
W1105 17:30:22.319972 15205 init.cc:212]     @     0x7f9838c70505 call_function
W1105 17:30:22.322440 15205 init.cc:212]     @     0x7f9838c9538a _PyEval_EvalFrameDefault
W1105 17:30:22.324836 15205 init.cc:212]     @     0x7f9838c6abab _PyFunction_FastCallDict
W1105 17:30:22.327309 15205 init.cc:212]     @     0x7f9838be9b0f _PyObject_FastCallDict
W1105 17:30:22.329708 15205 init.cc:212]     @     0x7f9838c2b810 _PyObject_CallMethodIdObjArgs
W1105 17:30:22.332087 15205 init.cc:212]     @     0x7f9838be0b10 PyImport_ImportModuleLevelObject
W1105 17:30:22.334471 15205 init.cc:212]     @     0x7f9838c97a8b _PyEval_EvalFrameDefault
W1105 17:30:22.336856 15205 init.cc:212]     @     0x7f9838c6b289 PyEval_EvalCodeEx
Segmentation fault

请问是什么原因？多谢
paddle版本是：https://paddle-wheel.bj.bcebos.com/1.6.0-gpu-cuda9-cudnn7-mkl/paddlepaddle_gpu-1.6.0.post97-cp36-cp36m-linux_x86_64.whl

**Comment by TomorrowIsAnOtherDay** [comment]
你好，我看你的报错信息有 `torch::onnx::initONNXBindings`这样的错误，猜测可能是paddle与torch的依赖冲突导致的。
你目前的环境可以正常运行paddle的普通程序吗？

**Comment by 1145520074** [comment]
> 你好，我看你的报错信息有 `torch::onnx::initONNXBindings`这样的错误，猜测可能是paddle与torch的依赖冲突导致的。
> 你目前的环境可以正常运行paddle的普通程序吗？

可以运行别的

**Comment by TomorrowIsAnOtherDay** [comment]
你使用的是anaconda部署环境吗？如果是的话请导出anaconda的环境配置，我们这边尝试复现下这个问题。
如果是pip配置的话，请使用pip list 输出配置环境。

如果赶时间的话，建议用anaconda开一个新的环境，只配置paddle以及PARL。

**Comment by ddayzzz** [comment]
说起 `torch`我倒是发现代码[https://github.com/PaddlePaddle/PARL/blob/develop/parl/core/torch/agent.py#L75](https://github.com/PaddlePaddle/PARL/blob/develop/parl/core/torch/agent.py#L75) 有点问题：

>    self.alg = algorithm
        self.device = **torc**.device('cuda' if torch.cuda.
                                  is_available() else 'cpu')

是否出现了拼写错误？

**Comment by TomorrowIsAnOtherDay** [comment]
> 说起 `torch`我倒是发现代码https://github.com/PaddlePaddle/PARL/blob/develop/parl/core/torch/agent.py#L75 有点问题：
> 
> > self.alg = algorithm
> > self.device = **torc**.device('cuda' if torch.cuda.
> > is_available() else 'cpu')
> 
> 是否出现了拼写错误？

是的！感谢指出。我们的单测应该会覆盖到这部分代码的，但实际上并没有覆盖到。我们立刻定位下原因。

**Comment by TomorrowIsAnOtherDay** [comment]
> > 说起 `torch`我倒是发现代码https://github.com/PaddlePaddle/PARL/blob/develop/parl/core/torch/agent.py#L75 有点问题：
> > > self.alg = algorithm
> > > self.device = **torc**.device('cuda' if torch.cuda.
> > > is_available() else 'cpu')
> > 
> > 
> > 是否出现了拼写错误？
> 
> 是的！感谢指出。我们的单测应该会覆盖到这部分代码的，但实际上并没有覆盖到。我们立刻定位下原因。

问题已定位到并fix了，再次感谢指出！

**Comment by loretoparisi** [comment]
@TomorrowIsAnOtherDay We have the same error on PaddlePaddle https://github.com/PaddlePaddle/Paddle/issues/23086

```
W0318 11:19:35.642894   150 init.cc:217]     @     0x7fd7e9316c94 _ZN8pybind115enum_IN10onnx_torch20TensorProto_DataTypeEEC1IJEEERKNS_6handleEPKcDpRKT_
W0318 11:19:35.644227   150 init.cc:217]     @     0x7fd7e931029c torch::onnx::initONNXBindings()
```

We have `torch` among the requirements.
Any hint?

**Comment by TomorrowIsAnOtherDay** [comment]
@loretoparisi  Sorry, our suggestion was to install `torch` and  `paddle` in different environments. We do not suggest using PARL in an environment with  torch and paddle installed, due to the potential dependency conflicts.

**Comment by loretoparisi** [comment]
@TomorrowIsAnOtherDay thank you, in the meanwhile we have found out that the conflict happens with `torch==1.0.0` at least.
