### ISSUE TITLE
PARL cluster setup failed in windows; get_ip_address not supported

### ISSUE THREAD

**Issue by yixinLi** [PaddlePaddle/PARL#178]
I tried to follow the example in https://parl.readthedocs.io/en/latest/parallel_training/setup.html to setup my windows machine as a cluster. However the xparl start command failed and it seemed the get_ip_address function implemented in parl/utils/machine_info.py doesnt support windows.

my questions are threefold:
1. Does PARL distributed training support windows?
2. If it does support windows, then is the incompatibility of get_ip_address under windows the only reason why the example program failed in my case?
3. how should I fix get_ip_address? (i.e. "set ip address manually", as in the code comment). i am not familiar with socket communication so hopefully there is an easy way...

**Comment by TomorrowIsAnOtherDay** [comment]
Thanks for your interest in PARL.
Unfortunately, we failed to solve the issues in the *Windows* platform(see #157).
The main issue is that windows has a different command set to control the processes. We would like to solve it in the future.
At the moment, we suggest that you use PARL in a linux environment:)

**Comment by luoruiming** [comment]
I had the same get_ip_address problem when using PARL in Windows. Quickly I moved to a Linux environment and that problem didn't bother me anymore.

**Comment by TomorrowIsAnOtherDay** [comment]
Hi, guys, PARL has supported installation on Windows now. I'm going to close this issue. Please have a try on it and feel free to report any issue, thanks a lot!
