### ISSUE TITLE
PaddleCheckError: cudaGetDeviceCount failed in paddle::platform::GetCUDADeviceCountImpl

### ISSUE THREAD

**Issue by zienn** [PaddlePaddle/PARL#179]
`paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::platform::GetCUDADeviceCount()

----------------------
Error Message Summary:
----------------------
PaddleCheckError: cudaGetDeviceCount failed in paddle::platform::GetCUDADeviceCountImpl, error code : 30, Please see detail in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038: unknown error at [/paddle/paddle/fluid/platform/gpu_info.cc:67]
`
this problem happend sometimes, it can be solved after I reboot the computer.
what should I do?

**Comment by zenghsh3** [comment]
It looks like cuda cannot find gpu normally, and raise an exception in Paddle. Maybe you can raise an issue in [Paddle](https://github.com/PaddlePaddle/Paddle/issues).
