### ISSUE TITLE
Will it support Multi-Agent RL in the future?

### ISSUE THREAD

**Issue by zienn** [PaddlePaddle/PARL#180]
how to deal with importing Multi-Agent Env or custom envs?

**Comment by TomorrowIsAnOtherDay** [comment]
Yes! We will open-source a multi-agent  example in the next release! 

For centralized Multi-agent reinforcement learning(MARL) algorithm, its implementation is similar to the single-agent algorithm.
For decentralized MARL algorithm, we can synchronize parameters among different agents by using `xparl`, the parallel computation tool in **PARL**.

**Comment by zienn** [comment]
thx，I can't wait for it.

**Comment by TomorrowIsAnOtherDay** [comment]
Thanks for your interest in PARL. We are now working on the state-of-the-art algorithms on continuous spaces such as TD3, SAC. For other algorithms, we still need more time to implement.
