### ISSUE TITLE
Warning: NaN or Inf found in input tensor.

### ISSUE THREAD

**Issue by zienn** [PaddlePaddle/PARL#198]
控制台显示NaN or Inf found in input tensor.
我该怎么定位这个问题呢？
![error](https://user-images.githubusercontent.com/19533066/72325300-c47b9480-36e7-11ea-97bc-ab0acd8587ce.png)

**Comment by TomorrowIsAnOtherDay** [comment]
这是运行哪个example时候出现的问题呢？
请更详细地描述你的问题，方便我们复现定位问题。

**Comment by zienn** [comment]
我是在IMPALA算法进行的更改，改动挺多的

**Comment by TomorrowIsAnOtherDay** [comment]
这样啊，建议你自行看下是跑训练还是测试时候出现这个问题。
如果是测试时候出现这个warning，到底是哪层layer出现了异常的输入输出。
由于我们不知道你的具体代码以及逻辑，没法给你提供很准确的解决方案，建议这块你自己再定位下：）

**Comment by zienn** [comment]
好的，感谢

**Comment by TomorrowIsAnOtherDay** [comment]
祝好：）有问题再随时提起issue吧～
