### ISSUE TITLE
pip install parl. Error: command cmake failed: no such file or directory 

### ISSUE THREAD

**Issue by ydchen9** [PaddlePaddle/PARL#201]
Under Windows 7 system， python 2.7 and paddle 1.5.1. The following error occurred.

![image](https://user-images.githubusercontent.com/26667822/74514097-e49cae80-4f46-11ea-84d7-493d00c7cc05.png)

**Comment by TomorrowIsAnOtherDay** [comment]
Thank you for your interest in PARL. We have noticed the installation issue in Windows and started to address the issue. Hopefully, it will be solved in the following months. 
We now recommend that you try PARL in a linux environment. 
If you do not have appropriate linux devices, please try it at [AIstudio](https://aistudio.baidu.com/), a platform that provides virtual linux environments.

**Comment by ydchen9** [comment]
> Thank you for your interest in PARL. We have noticed the installation issue in Windows and started to address the issue. Hopefully, it will be solved in the following months.
> We now recommend that you try PARL in a linux environment.
> If you do not have appropriate linux devices, please try it at [AIstudio](https://aistudio.baidu.com/), a platform that provides virtual linux environments.

Thanks！

**Comment by TomorrowIsAnOtherDay** [comment]
We now support the installation on Windows. Try it and feel free to report any issue !
Thanks !
