### ISSUE TITLE
example coding for cluster can't work

### ISSUE THREAD

**Issue by Li-Guanda** [PaddlePaddle/PARL#202]
I build a cluster successfully. But when I run  the example and recommended Practice, it will return an error.
[02-27 09:23:17 MainThread @logger.py:224] Argv: a.test.py
[02-27 09:23:37 Thread-2 @client.py:244] ERR [xparl] lost connection with a job, current actor num: 0

I test it in ubuntu 18, ubuntu 16 and WSL.

**Comment by TomorrowIsAnOtherDay** [comment]
Thank you for your interest in PARL.
Are you running the following code at the `Recommended Practice` page ?
```python
import threading
import parl

@parl.remote_class
class A(object):
    def run(self):
        ans = 0
        for i in range(100000000):
            ans += i
threads = []
parl.connect("localhost:6006")
for _ in range(5):
    a = A()
    th = threading.Thread(target=a.run)
    th.start()
    threads.append(th)
for th in threads:
    th.join()
```

-------
Could you try restart the cluster and rerun the code, using the `xparl stop` to shutdown the cluster.
