### ISSUE TITLE
Does Baidu apply PARL into online recommendation system?

### ISSUE THREAD

**Issue by scriptboy1990** [PaddlePaddle/PARL#220]
RT

**Comment by TomorrowIsAnOtherDay** [comment]
Exactly. Reinforcement learning is one of the main techniques we uses in our productions, including our News feed product and short-video product.
For example, RL can be used to rerank the news from the perspective of reranking a news list, capturing the connections between news items, and recommending the news full of various kinds.

**Comment by scriptboy1990** [comment]
> Exactly. Reinforcement learning is one of the main techniques we uses in our productions, including our News feed product and short-video product.
> For example, RL can be used to rerank the news from the perspective of reranking a news list, capturing the connections between news items, and recommending the news full of various kinds.

thx.
