### ISSUE TITLE
Can you give out an  example of PrioritizedDQN, another version of DQN?

### ISSUE THREAD

**Issue by Cyanide13** [PaddlePaddle/PARL#239]

**Comment by Cyanide13** [comment]
Priorized replay memory is so hard.

**Comment by TomorrowIsAnOtherDay** [comment]
Thanks for your interest in PARL. We are now implementing it, and will provide this example in the next few weeks.

**Comment by TomorrowIsAnOtherDay** [comment]
We have provided the implementation in #326 .
