### ISSUE TITLE
该升级了，和paddlehub不同步啊

### ISSUE THREAD

**Issue by 60999** [PaddlePaddle/PARL#246]
ERROR: parl 1.2.3 has requirement flask==1.0.4, but you'll have flask 1.1.1 which is incompatible.

ERROR: paddlehub 1.6.1 has requirement flask>=1.1.0, but you'll have flask 1.0.4 which is incompatible.

**Comment by TomorrowIsAnOtherDay** [comment]
不同的库依赖的第三方库也不一样，为了解决冲突问题，建议使用anaconda来隔离python环境：）可以很方便地解决这类问题。
