### ISSUE TITLE
不知可否增加一个SAC的离散action版本？

### ISSUE THREAD

**Issue by dbsxdbsx** [PaddlePaddle/PARL#271]
理论上这个是可行的，但我不知道这个在paddle parl这里怎么写，不知可否官方实现下：
我能找到的参考资料有: 
https://stackoverflow.com/questions/56226133/soft-actor-critic-with-discrete-action-space
https://www.spaces.ac.cn/archives/6705

感谢。

**Comment by TomorrowIsAnOtherDay** [comment]
感谢你的建议。我们先去了解下，评估下可行性再答复。

**Comment by TomorrowIsAnOtherDay** [comment]
感谢你的建议。我们先去了解下，评估可行性后再答复。

**Comment by TomorrowIsAnOtherDay** [comment]
我看了下torch的实现，主要的操作是:
`torch.empty()` 创建参数，然后通过常规的OP来进行后续的计算。
至于创建参数这个操作，可以使用`layers.create_parameter`，具体可以参考PPO的做法。
https://github.com/PaddlePaddle/PARL/blob/6efa7871dbb4ab02799330bbb8941a691d5f522e/examples/PPO/mujoco_model.py#L54

**Comment by TomorrowIsAnOtherDay** [comment]
我们先关闭这个issue哈，如果实现过程中有任何使用的问题，欢迎随时再开issue：）
祝好
