### ISSUE TITLE
在parl中可能batch_norm函数无法正常使用

### ISSUE THREAD

**Issue by dbsxdbsx** [PaddlePaddle/PARL#280]
win10_64，paddlepaddle: 1.8.1.post107，parl: 1.3 
相关issue: https://github.com/PaddlePaddle/Paddle/issues/24835

经提醒，发现可能是以下2个模块中的batch_norm的函数产生了冲突：
```
from paddle.fluid.layers import *
from parl.core.fluid.layers.layer_wrappers import *
```
PS: 我在vscode中` self.bn1 = layers.batch_norm(act='relu',fuse_with_relu=True)`,ctrl+click跟踪`batch_norm`函数会跟踪到`layers.nn.py`模块中，而在pycharm中会跟踪到`layers_wrappers.py`中。

目前没有发现在parl中使用batch_norm的正确方式。 觉得可能是个隐患，所以发个issue在这里。

**Comment by zenghsh3** [comment]
你好，感谢反馈问题。我们定位发现是paddle新版本中`batch_norm` layer去除掉了`fuse_with_relu`参数，而PARL layers是暂时没有对齐到最新的paddle版本，建议先下载使用paddle 1.6.1版本。

另外，我们在paddle 1.6.1中是有针对PARL `batch_norm` layer的相关单测来验证功能正常。

**Comment by TomorrowIsAnOtherDay** [comment]
这个问题的来源是Paddle在更新1.8的过程中并没有做接口兼容性更新，我们已经和开发接口的团队沟通了，后续会增加兼容性检查避免类似的问题。

再次感谢反馈！
