### ISSUE TITLE
parl can not install for Win7-64bit，python 2.7 platform.

### ISSUE THREAD

**Issue by ydchen9** [PaddlePaddle/PARL#287]
I use the command as "pip install parl", and it shows that parl is successfully installed. 
But when I import parl, the error arises as follows:
![QQ截图20200607200040](https://user-images.githubusercontent.com/26667822/83968376-5d12eb00-a8fb-11ea-8312-97b74ee20bee.png)
How can I fix it?

**Comment by TomorrowIsAnOtherDay** [comment]
Thanks for your interest in PARL. PARL only supports python 3.6+ in Windows platform as one of its dependencies, Pyarrow, doesn't not support python2.7 in Windows. 
To solve this problem, we suggest that you install PARL in python 3.6+(Anaconda is a helpful tool to create a python3.6 environment). 
We will be updating the README to tell users this problem. 
Thanks for reporting the problem!
