### ISSUE TITLE
使用PARL导致环境输出过多debug信息的问题

### ISSUE THREAD

**Issue by dbsxdbsx** [PaddlePaddle/PARL#302]
win10下parl 1.3版本。
我拿example中的SAC做实验，用的是一个第三方的custom gym env, 该环境在下面的代码中测试输出正常：
```
env = gym.make('custom_env_name')
	for i_episode in range(10):
		i = 0
		done = False
		print(f"start resetting new episode[{i_episode}]")
		observation = env.reset()
		xx = env.observation_space
		i_episode += 1

		while not done:
			action = env.action_space.sample()
			i += 1
			print(f"{i}：got action: {action} for obs time:{env.get_datetime(observation[-1][-1])}")
			observation, reward, done, info = env.step(action)

		print(f"episode[{i_episode}] finished")
```
但是当我在SAC样例中使用该env的时候，发现`observation = env.reset()`和`env.step`会输出大量的debug信息，前缀像这样：
```
2020-06-18 21:23:25,390-DEBUG:
2020-06-18 21:23:25,410-DEBUG:
```
是不是parl中有个调试输出的开关代码呢？ 我原以为是不是logger这个模块，但是没找到相关的代码。

**Comment by zenghsh3** [comment]
这debug信息应该不是PARL输出的，会是你用到的custom gym env输出的吗？

**Comment by TomorrowIsAnOtherDay** [comment]
https://github.com/PaddlePaddle/PARL/blob/aa81b0f10bdee6ae7fbe2a16c53ed2b0a1beb803/parl/utils/logger.py#L110
PARL的logger模块是可以设定输出级别的，参考上面的级别设置即可。

举个例子
```python
from parl.utils import logger
logger.set_level("INFO")
logger.debug("Hello")
```

**Comment by dbsxdbsx** [comment]
@zenghsh3  确实不是parl的输出，是自己环境的输出，我不清楚的是，为何同样的环境，在简易环境中没有问题，但用在parl中就有问题了，而且上面我说的只是f5调试的情况，除了输出有点多，其他正常。但当直接运行时，发现脚本走不到done的位置,最后还会不断输出把程序给卡死了。
@TomorrowIsAnOtherDay，这个可能不是logger模块的问题，因为我把主文件下的所有logger替换成print后问题依旧。可能问题和env与agent和model模块的交互有关，不知会不会是牵扯到paddle静态图之类的。

我回去再做做剥离测试，看看问题在哪里...

**Comment by TomorrowIsAnOtherDay** [comment]
好嘞，加油。
如果是PARL的问题请随时指出来。

**Comment by dbsxdbsx** [comment]
经过剥离测试，发现只要包含`paddle.complex`模块，自定义env就会有debug的输出。并且后来经过查找，自定义环境中的debug信息也是通过logger模块来输出的：`self._logger.debug(“xxx”)`,当把它设置level的语句`self._logger.setLevel(logging.DEBUG)`注释掉或者调成比DEBUG更高的level后，就没有debug输出了。 

但我仍不清楚为何在没用paddle的情况下即使自定义环境是debug输出level，却仍不会输出debug信息？  
这应该不是paddle的问题，但会影响兼容性。
