### ISSUE TITLE
Where is 'UnableSerializeObject' defined?

### ISSUE THREAD

**Issue by cclauss** [PaddlePaddle/PARL#305]
https://github.com/PaddlePaddle/PARL/search?q=UnableSerializeObject
Six files call `UnableSerializeObject()` but I can not find any files that define it.

**Comment by TomorrowIsAnOtherDay** [comment]
Thanks for pointing it out.
This is an undefined variable in the unittest, but our tests do not run this part of code.
We will remove it.

**Comment by TomorrowIsAnOtherDay** [comment]
closed by #307
