### ISSUE TITLE
layers.batch_norm()与paddle.fluid.layers.batch_norm冲突

### ISSUE THREAD

**Issue by yujieNC** [PaddlePaddle/PARL#308]
您好，我收到一个报错:
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/parl/core/fluid/layers/layer_wrappers.py in __call__(self, input, is_test)
    550                 do_model_average_for_mean_and_var,
    551                 fuse_with_relu=fuse_with_relu,
--> 552                 use_global_stats=use_global_stats)
    553 
    554     return BatchNorm_()
TypeError: batch_norm() got an unexpected keyword argument 'fuse_with_relu'

我的版本: PARL1.3.1，paddlepaddle1.8.2和1.6.3
我怀疑这是parl的一个bug:
parl.layers.batch_norm(),有一个输入参数是fuse_with_relu，该参数在parl.layers.batch_norm()中被传入了paddle.fluid.layers.batch_norm().
但是，paddle.fluid.layers.batch_norm()并没有一个名为fuse_with_relu的输入参数。

**Comment by zenghsh3** [comment]
你好，感谢反馈问题。这个问题是由于Paddle在新版本更新时没有做该接口的兼容性更新。
paddle新版本中batch_norm layer去除掉了fuse_with_relu参数，而PARL layers是暂时没有对齐到最新的paddle版本，建议先下载使用paddle 1.6.1版本。

**Comment by zenghsh3** [comment]
你好，感谢反馈问题，这个问题的来源是Paddle在更新版本的过程中没有做该接口的兼容性更新导致的，一个解决方案是可以先下载使用paddle 1.6.1版本，另外，我们也针对这个问题进行了paddle不同版本的兼容，已发起PR #310

**Comment by yujieNC** [comment]
您好，感谢你们的跟进。希望PARL越来越好！

2020-06-22 11:27:32"Hongsheng Zeng" <notifications@github.com>写道：

你好，感谢反馈问题，这个问题的来源是Paddle在更新版本的过程中没有做该接口的兼容性更新导致的，一个解决方案是可以先下载使用paddle 1.6.1版本，另外，我们也针对这个问题进行了paddle不同版本的兼容，已发起PR #310
