### ISSUE TITLE
agent保存之后加载报尺寸不匹配错误

### ISSUE THREAD

**Issue by liucc09** [PaddlePaddle/PARL#311]
![微信图片_20200622132226](https://user-images.githubusercontent.com/9207861/85251254-6ff4f600-b48b-11ea-9787-0d8a6098db2b.png)

代码如下：

```
agent.save(ckpt)
agent.restore(ckpt)
```

报错：

---------------------------------------------------------------------------RuntimeError                              Traceback (most recent call last)<ipython-input-25-1c9c3f053848> in <module>
      1 print(ckpt)
      2 agent.save(ckpt)
----> 3 agent.restore(ckpt)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/parl/core/fluid/agent.py in restore(self, save_path, program)
    194             dirname=dirname,
    195             main_program=program,
--> 196             filename=filename)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py in load_params(executor, dirname, main_program, filename)
    796         main_program=main_program,
    797         predicate=is_parameter,
--> 798         filename=filename)
    799 
    800 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py in load_vars(executor, dirname, main_program, vars, predicate, filename)
    680             main_program=main_program,
    681             vars=list(filter(predicate, main_program.list_vars())),
--> 682             filename=filename)
    683     else:
    684         load_prog = Program()
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py in load_vars(executor, dirname, main_program, vars, predicate, filename)
    739                     "Shape not matching: the Program requires a parameter with a shape of ({}), "
    740                     "while the loaded parameter (namely [ {} ]) has a shape of  ({}).".
--> 741                     format(orig_shape, each_var.name, new_shape))
    742 
    743 
RuntimeError: Shape not matching: the Program requires a parameter with a shape of ((16, 64)), while the loaded parameter (namely [ fc.w_18 ]) has a shape of  ((64, 64)).

**Comment by TomorrowIsAnOtherDay** [comment]
这个在群里面已经有人提问过了，原因在于你更改了模型结构之后，但是加载了之前保存的模型。

**Comment by TomorrowIsAnOtherDay** [comment]
@liucc09 能否贴一下完整的可复现代码呢？方便我们复现定位问题。

**Comment by liucc09** [comment]
> 
> 
> @liucc09 能否贴一下完整的可复现代码呢？方便我们复现定位问题。

代码如下，版本1：https://aistudio.baidu.com/aistudio/projectdetail/581234

**Comment by liucc09** [comment]
> 
> 
> @liucc09 能否贴一下完整的可复现代码呢？方便我们复现定位问题。

我并没有改模型，而且再怎么改模型也不可能把第一个fc层变成64*64，毕竟state的维度是16

**Comment by TomorrowIsAnOtherDay** [comment]
![image](https://user-images.githubusercontent.com/25046619/85252029-72584f80-b48d-11ea-800e-aa8aa085602f.png)
好的，请更改下权限。

**Comment by liucc09** [comment]
这个notebook是作业里点进去的，没有公开按钮
 
发件人： Bo Zhou
发送时间： 2020-06-22 13:37
收件人： PaddlePaddle/PARL
抄送： liucc09; Mention
主题： Re: [PaddlePaddle/PARL] agent保存之后加载报尺寸不匹配错误 (#311)

好的，请更改下权限。

**Comment by TomorrowIsAnOtherDay** [comment]
我看群里已经有PARL的用户答复你了。
我在这里总结下：
Paddle目前的静态图机制，使得每次实例化agent的时候，都会在静态图上继续搭建网络，导致参数增多，这样二次加载的时候，模型根据名字去查找之前的参数会引发问题。
建议：
1）在本地跑
2）notebook每次跑的时候重启下，销毁之前的静态图数据。

**Comment by TomorrowIsAnOtherDay** [comment]
我即将关闭这个issue。
原因在于这并不是PARL的bug，而是静态图机制和notebook的内存托管机制导致的混乱。
感谢您的反馈，有问题请随时再提出来：）
祝好

**Comment by liucc09** [comment]
> 
> 
> 我即将关闭这个issue。
> 原因在于这并不是PARL的bug，而是静态图机制和notebook的内存托管机制导致的混乱。
> 感谢您的反馈，有问题请随时再提出来：）
> 祝好

好的
