### ISSUE TITLE
parl的/examples/tutorials 下面的python文件编码声明不在第一行，直接运行代码会有错误

### ISSUE THREAD

**Issue by leiming-cool** [PaddlePaddle/PARL#313]
例如：
PARL-develop/examples/tutorials/lesson3/dqn/train.py

![image](https://user-images.githubusercontent.com/67268894/85281208-2a045600-b4bc-11ea-9d03-e743a7cff502.png)

**Comment by TomorrowIsAnOtherDay** [comment]
你是怎么启动程序的呢？
如果是python + 代码文件跑的话应该不会有这个问题？

**Comment by leiming-cool** [comment]
> 嗯， 是的。 我是 pycharm 文件里面main方法执行会有这个问题； 如果 python 直接运行，这个就受本机环境影响了。
> 我把，编码声明放到第一行，pycharm和 python + 文件就都可以。

**Comment by leiming-cool** [comment]
> 你是怎么启动程序的呢？
> 如果是python + 代码文件跑的话应该不会有这个问题？

嗯， 是的。 我是 pycharm 文件里面main方法执行会有这个问题； 如果 python 直接运行，这个就受本机环境影响了。
我把，编码声明放到第一行，pycharm和 python + 文件就都可以。

**Comment by TomorrowIsAnOtherDay** [comment]
这个是很常用的版权声明，建议你查询下pycharm如何解决这个问题。
https://github.com/tensorflow/models/blob/8aa44501abd01cc95bcddd27fd686aa52ce138c2/research/cvt_text/preprocessing.py#L1
