### ISSUE TITLE
Use int32 instead of int

### ISSUE THREAD

**Issue by TonyLianLong** [PaddlePaddle/PARL#316]
https://github.com/PaddlePaddle/PARL/blob/develop/parl/algorithms/fluid/ddqn.py#L78

I believe the latest paddle paddle does not support 'int' as a type. You can run DQN_variant example as a proof.

**Comment by TomorrowIsAnOtherDay** [comment]
Hi, thanks for reporting the problem. 
What's the paddlepaddle version in your environment?

**Comment by TonyLianLong** [comment]
> Hi, thanks for reporting the problem.
> What's the paddlepaddle version in your environment?

paddlepaddle-gpu   1.8.2.post107

My PARL is the latest one.

**Comment by TomorrowIsAnOtherDay** [comment]
I've reproduced the issue in my environment. Thanks a lot!
This problem issues from the upgrade of Paddle 1.8+.
We will fix this problem.
