### ISSUE TITLE
save and load model in PPO

### ISSUE THREAD

**Issue by yingyingll** [PaddlePaddle/PARL#322]

**Comment by TomorrowIsAnOtherDay** [comment]
Hi, can you detail the issue?

**Comment by yingyingll** [comment]
> Hi, can you detail the issue?

Hi,
I trained the example code of PPO,  I want to save and reload the trained model, I use
    agent.restore('policy.cpkt', program=agent.policy_learn_program)
    agent.restore('value.cpkt', program=agent.value_learn_program)
and 
       agent.save('policy.cpkt', program=agent.policy_learn_program)
       agent.save('value.cpkt', program = agent.value_learn_program)
but there is an error. What‘s the right way? Thank you!

**Comment by TomorrowIsAnOtherDay** [comment]
Thanks for your reply!
I fail to reproduce the issue you mentioned. Here is my code:
```python
if __name__ == '__main__':
    from mujoco_model import MujocoModel
    obs_dim = 10
    act_dim = 4
    policy_lr = 1e-3
    value_lr = 1e-4
    model = MujocoModel(obs_dim, act_dim)
    alg = parl.algorithms.PPO(
        model,
        act_dim=act_dim,
        policy_lr=policy_lr,
        value_lr=value_lr)
    agent = MujocoAgent(
        alg, obs_dim, act_dim, 0.003, 'CLIP')
    agent.save('policy.cpkt', program=agent.policy_learn_program)
    agent.save('value.cpkt', program=agent.value_learn_program)
    agent.restore('policy.cpkt', program=agent.policy_learn_program)
    agent.restore('value.cpkt', program=agent.value_learn_program)
```

**Comment by TomorrowIsAnOtherDay** [comment]
Can you show us the code to reproduce the issue ?

**Comment by TomorrowIsAnOtherDay** [comment]
We are closing this issue as it seems that PARL runs correctly.
