### ISSUE TITLE
'MujocoAgent' object has no attribute 'alg'

### ISSUE THREAD

**Issue by Gaoee** [PaddlePaddle/PARL#323]
Hi, when i run the td3 benchmark in torch example, I get following error:
Traceback (most recent call last):
  File "train.py", line 135, in <module>
    main()
  File "train.py", line 96, in main
    agent = MujocoAgent(algorithm, obs_dim, act_dim)
  File "/home/exp/Codes/PARL/benchmark/torch/td3/mujoco_agent.py", line 29, in __init__
    self.alg.sync_target(decay=0)
AttributeError: 'MujocoAgent' object has no attribute 'alg'

Is it the problem of the code, or something wrong I have made?

**Comment by TomorrowIsAnOtherDay** [comment]
Thanks for reporting the issue.
We will fix this problem.

**Comment by rical730** [comment]
I made a hotfix in https://github.com/PaddlePaddle/PARL/pull/325. Please consider using this patch before it merges and releases.
