### ISSUE TITLE
是否有基于resnet网络的强化学习例子

### ISSUE THREAD

**Issue by bxdxstu** [PaddlePaddle/PARL#328]
看到框架里的AlphaZero示例是基于Torch实现的，是否有基于paddlepaddle实现的例子？parl目前能否搭建resnet网络，能否给个例子？

**Comment by TomorrowIsAnOtherDay** [comment]
感谢提问！
这有2个问题，我逐个回复下：

1.  目前Alpha Zero是基于torch实现的。是的，这个是我们为了**推广PARL并行**在kaggle上面开源的算法。https://www.kaggle.com/c/connectx/leaderboard 这是目前通过机器学习算法取得的最好的成绩（截止到我们6月底提交的时候），排在第一二名的算法，根据作者公开的信息来看，是基于工程trick加速代码搜索的。

2. paddle版本的AlphaZero目前还没有，但是搭建resnet肯定是可以的，可以参考paddle仓库中的[cv模型搭建](https://github.com/PaddlePaddle/models/blob/1bf7264771fb30b588c426e9c153f9b643256971/PaddleCV/image_classification/models/resnet.py)。我们会在下一个大版本中支持paddle最新的动态图，届时会考虑复现alphazero这个算法的。
