### ISSUE TITLE
能否给一个多维离散动作的例子

### ISSUE THREAD

**Issue by Synmul** [PaddlePaddle/PARL#329]
例如无人机act_dim = [3,3] 0表示减,1表示不采取动作,2表示加
第一维升降
第二维前后
第三维左右
虽然act用一维表示也可以但是无人机三个维度的动作同时执行互不影响
我修改了dqn代码  把输出维度layers.reshape(out, [-1, 3, 3])但是没什么效果,还总是出现Warning: NaN or Inf found in input tensor.

**Comment by TomorrowIsAnOtherDay** [comment]
是否需要把问题建模成【多维离散】问题，是取决于具体问题的。
有些连续空间的控制问题是可以通过离散化连续空间，把连续控制问题转换成离散控制问题的。
这种针对特定问题的解决方案，不适合开源在PARL中，我们更倾向于开源有广泛借鉴意义的算法，比如离散控制问题上的DQN算法。

针对飞行器这个问题，我建议你把输出维度改为【1 * 9】，然后每个格子对应你无人机问题中【3*3】的一个格子，这样改代码不容易出现问题。

**Comment by Synmul** [comment]
我并不只是为了解决无人机这个特定问题,无人机只是比喻,而我实际遇到的问题无法通过多维转换到单维解决,不过已经借鉴其他开源库的算法解决了,我想尝试一下使用paddle,可是一直没有效果,可能是我对paddle的接口不够熟悉并且也没找到相关的例子,所以希望官方能出个例子.
