### ISSUE TITLE
[PaddleCheckError] there seems to be some problems of the operator

### ISSUE THREAD

**Issue by zbp-xxxp** [PaddlePaddle/PARL#336]
----------------------
Error Message Summary:
----------------------
PaddleCheckError: op mul does not have kernel for data_type[uint8_t]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN] at [D:\paddle-tiny-release-liujinquan\1.6.1-tiny\Paddle\paddle\fluid\framework\operator.cc:1007]
  [operator < mul > error]

What should i do to solve these problems?
If you could give me some solutions, I'd be very grateful!

**Comment by TomorrowIsAnOtherDay** [comment]
It seems like a problem about data type, please convert your unit_8 data to the float type before computation.
Try this:
```python
data = layers.cast(data, dtype='float32')
```
