### ISSUE TITLE
[ImportError] There are some trouble when I use box2d in AI Studio

### ISSUE THREAD

**Issue by zbp-xxxp** [PaddlePaddle/PARL#337]
one trouble is 

--> 227 del base
    228 
    229 # XXX remove

NameError: name 'base' is not defined

the second is 

<ipython-input-24-f258b78585b7> in run_episode(agent, env, rpm)
     16 
     17 def run_episode(agent, env, rpm):
---> 18     obs = env.reset()
     19     total_reward = 0
     20     steps = 0
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/gym/wrappers/time_limit.py in reset(self, **kwargs)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/gym/envs/box2d/car_racing.py in reset(self)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/gym/envs/box2d/car_racing.py in step(self, action)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/gym/envs/box2d/car_racing.py in render(self, mode)
ImportError: cannot import name 'rendering' from 'gym.envs.classic_control' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/gym/envs/classic_control/__init__.py)

But when I run it locally, there's no problem.
I would appreciate it if you can give me some suggestion, thanks.

**Comment by TomorrowIsAnOtherDay** [comment]
Thanks for submitting the issue! But this is not a PARL problem. We suggest that you use box2d locally, as AIStudio doesn't support all the environments.
