### ISSUE TITLE
[TypeError] fc() got an unexpected keyword argument 'is_test'

### ISSUE THREAD

**Issue by zbp-xxxp** [PaddlePaddle/PARL#338]
the output is :
[07-11 17:24:48 MainThread @logger.py:95] WRN Cannot find available GPU devices, using CPU now.
---------------------------------------------------------------------------TypeError                                 Traceback (most recent call last)<ipython-input-5-f258b78585b7> in <module>
    108 
    109 if __name__ == '__main__':
--> 110     main()
<ipython-input-5-f258b78585b7> in main()
     81     model = Model(act_dim)
     82     algorithm = DDPG(model, gamma=GAMMA, tau=TAU, actor_lr=ACTOR_LR, critic_lr=CRITIC_LR)
---> 83     agent = Agent(algorithm, obs_dim, act_dim)
     84 
     85     agent.restore(r'model/pre_training/model_number_60.ckpt')
<ipython-input-2-bf826c9f47f3> in __init__(self, algorithm, obs_dim, act_dim)
     10         self.obs_dim = obs_dim
     11         self.act_dim = act_dim
---> 12         super(Agent, self).__init__(algorithm)
     13 
     14         # 注意：最开始先同步self.model和self.target_model的参数.
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/parl/core/fluid/agent.py in __init__(self, algorithm, gpu_id)
     85         self.gpu_id = 0 if machine_info.is_gpu_available() else -1
     86 
---> 87         self.build_program()
     88 
     89         self.place = fluid.CUDAPlace(
<ipython-input-2-bf826c9f47f3> in build_program(self)
     22             obs = layers.data(
     23                 name='obs', shape=[self.obs_dim], dtype='float32')
---> 24             self.pred_act = self.alg.predict(obs)
     25 
     26         with fluid.program_guard(self.learn_program):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/parl/algorithms/fluid/ddpg.py in predict(self, obs)
     76         """ use actor model of self.model to predict the action
     77         """
---> 78         return self.model.policy(obs)
     79 
     80     @deprecated(
<ipython-input-3-e5f23a7c1839> in policy(self, obs)
      8 
      9     def policy(self, obs):
---> 10         return self.actor_model.policy(obs)
     11 
     12     def value(self, obs, act):
<ipython-input-3-e5f23a7c1839> in policy(self, obs)
     24 
     25     def policy(self, obs):
---> 26         out = self.fc1(obs)
     27         out = self.fc2(out)
     28         return out
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/parl/core/fluid/layers/layer_wrappers.py in __call__(self, input, is_test)
    154                 bias_attr=self.attr_holder.bias_attr,
    155                 act=act,
--> 156                 is_test=is_test)
    157 
    158     return FC_()
TypeError: fc() got an unexpected keyword argument 'is_test'

How to solve the error?
I would appreicate it if you could give me some suggestions.

**Comment by TomorrowIsAnOtherDay** [comment]
It seems that you are using out-of-date version of PARL. Please update the PARL version according to the documentation.
