### ISSUE TITLE
[NoSuchDisplayException] Cannot connect to "None"

### ISSUE THREAD

**Issue by zbp-xxxp** [PaddlePaddle/PARL#339]
Track generation: 1072..1345 -> 273-tiles track
---------------------------------------------------------------------------NoSuchDisplayException                    Traceback (most recent call last)<ipython-input-5-f258b78585b7> in <module>
    108 
    109 if __name__ == '__main__':
--> 110     main()
<ipython-input-5-f258b78585b7> in main()
     90     # 往经验池中预存数据
     91     while len(rpm) < MEMORY_WARMUP_SIZE:
---> 92         run_episode(agent, env, rpm)
     93 
     94     episode = 0
<ipython-input-5-f258b78585b7> in run_episode(agent, env, rpm)
     16 
     17 def run_episode(agent, env, rpm):
---> 18     obs = env.reset()
     19     total_reward = 0
     20     steps = 0
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/gym/wrappers/time_limit.py in reset(self, **kwargs)
     42         self._episode_started_at = time.time()
     43         self._elapsed_steps = 0
---> 44         return self.env.reset(**kwargs)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/gym/envs/box2d/car_racing.py in reset(self)
    293         self.car = Car(self.world, *self.track[0][1:4])
    294 
--> 295         return self.step(None)[0]
    296 
    297     def step(self, action):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/gym/envs/box2d/car_racing.py in step(self, action)
    305         self.t += 1.0/FPS
    306 
--> 307         self.state = self.render("state_pixels")
    308 
    309         step_reward = 0
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/gym/envs/box2d/car_racing.py in render(self, mode)
    328         assert mode in ['human', 'state_pixels', 'rgb_array']
    329         if self.viewer is None:
--> 330             from gym.envs.classic_control import rendering
    331             self.viewer = rendering.Viewer(WINDOW_W, WINDOW_H)
    332             self.score_label = pyglet.text.Label('0000', font_size=36,
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/gym/envs/classic_control/rendering.py in <module>
     25 
     26 try:
---> 27     from pyglet.gl import *
     28 except ImportError as e:
     29     raise ImportError('''
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pyglet/gl/__init__.py in <module>
    235     # trickery is for circular import
    236     _pyglet.gl = _sys.modules[__name__]
--> 237     import pyglet.window
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pyglet/window/__init__.py in <module>
   1888 if not _is_pyglet_doc_run:
   1889     pyglet.window = sys.modules[__name__]
-> 1890     gl._create_shadow_window()
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pyglet/gl/__init__.py in _create_shadow_window()
    207 
    208     from pyglet.window import Window
--> 209     _shadow_window = Window(width=1, height=1, visible=False)
    210     _shadow_window.switch_to()
    211 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pyglet/window/xlib/__init__.py in __init__(self, *args, **kwargs)
    169                     self._event_handlers[message] = func
    170 
--> 171         super(XlibWindow, self).__init__(*args, **kwargs)
    172 
    173         global _can_detect_autorepeat
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pyglet/window/__init__.py in __init__(self, width, height, caption, resizable, style, fullscreen, visible, vsync, display, screen, config, context, mode)
    573 
    574         if not display:
--> 575             display = pyglet.canvas.get_display()
    576 
    577         if not screen:
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pyglet/canvas/__init__.py in get_display()
     93 
     94     # Otherwise, create a new display and return it.
---> 95     return Display()
     96 
     97 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pyglet/canvas/xlib.py in __init__(self, name, x_screen)
    121         self._display = xlib.XOpenDisplay(name)
    122         if not self._display:
--> 123             raise NoSuchDisplayException('Cannot connect to "%s"' % name)
    124 
    125         screen_count = xlib.XScreenCount(self._display)
NoSuchDisplayException: Cannot connect to "None"

**Comment by TomorrowIsAnOtherDay** [comment]
We are closing this issue as it doesn't seems to be a problem relative to PARL.
