### ISSUE TITLE
[NameError] name 'base' is not defined

### ISSUE THREAD

**Issue by zbp-xxxp** [PaddlePaddle/PARL#341]
Track generation: 1257..1584 -> 327-tiles track
---------------------------------------------------------------------------NameError                                 Traceback (most recent call last)<ipython-input-10-b7fa1b0df735> in <module>
    108 
    109 if __name__ == '__main__':
--> 110     main()
<ipython-input-10-b7fa1b0df735> in main()
     90     # 往经验池中预存数据
     91     while len(rpm) < MEMORY_WARMUP_SIZE:
---> 92         run_episode(agent, env, rpm)
     93 
     94     episode = 0
<ipython-input-10-b7fa1b0df735> in run_episode(agent, env, rpm)
     16 
     17 def run_episode(agent, env, rpm):
---> 18     obs = env.reset()
     19     total_reward = 0
     20     steps = 0
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/gym/wrappers/time_limit.py in reset(self, **kwargs)
     42         self._episode_started_at = time.time()
     43         self._elapsed_steps = 0
---> 44         return self.env.reset(**kwargs)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/gym/envs/box2d/car_racing.py in reset(self)
    293         self.car = Car(self.world, *self.track[0][1:4])
    294 
--> 295         return self.step(None)[0]
    296 
    297     def step(self, action):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/gym/envs/box2d/car_racing.py in step(self, action)
    305         self.t += 1.0/FPS
    306 
--> 307         self.state = self.render("state_pixels")
    308 
    309         step_reward = 0
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/gym/envs/box2d/car_racing.py in render(self, mode)
    328         assert mode in ['human', 'state_pixels', 'rgb_array']
    329         if self.viewer is None:
--> 330             from gym.envs.classic_control import rendering
    331             self.viewer = rendering.Viewer(WINDOW_W, WINDOW_H)
    332             self.score_label = pyglet.text.Label('0000', font_size=36,
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/gym/envs/classic_control/rendering.py in <module>
     25 
     26 try:
---> 27     from pyglet.gl import *
     28 except ImportError as e:
     29     raise ImportError('''
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pyglet/gl/__init__.py in <module>
    223 elif compat_platform == 'darwin':
    224     from .cocoa import CocoaConfig as Config
--> 225 del base  # noqa: F821
    226 
    227 # XXX remove
NameError: name 'base' is not defined

It's too hard for me.
When I run the second times, the errors are change!

**Comment by TomorrowIsAnOtherDay** [comment]
We are closing this issue as it seems not to be a parl issue.
