### ISSUE TITLE
BicNet算法复现，双向lstm网络有问题

### ISSUE THREAD

**Issue by zienn** [PaddlePaddle/PARL#348]
有没有复现BicNet算法的计划，我自己在尝试写BicNet算法的时候发现paddlepaddle的双向lstm接口有问题。
已经有人提出了这个问题
[https://github.com/PaddlePaddle/Paddle/issues/22979#issue-579681421](url)

**Comment by TomorrowIsAnOtherDay** [comment]
近期没有这个计划，我们下一版本的是跟进目前SOTA的离散控制算法（MuZero、Agent57等）。

--------

至于双向lstm的问题，我去咨询下Paddle框架团队，让他们跟进下，晚点答复你哈。

**Comment by TomorrowIsAnOtherDay** [comment]
Paddle团队的开发成员已经在这个issue下回复了，请关注下：
https://github.com/PaddlePaddle/Paddle/issues/24300#issuecomment-658002094
