### ISSUE TITLE
尝试parl的并行运算，但是无法运行例程

### ISSUE THREAD

**Issue by kabuwaniu** [PaddlePaddle/PARL#350]
![image](https://user-images.githubusercontent.com/46389180/87557059-09f63a00-c6ea-11ea-858b-41411b4e2e95.png)
能够运行xparl start --port 8010
但是从parl文档拷贝下的并行代码无法运行
![image](https://user-images.githubusercontent.com/46389180/87557415-796c2980-c6ea-11ea-8d4b-c73d0f9d6147.png)

**Comment by zenghsh3** [comment]
你好，感谢反馈问题，我们在windows10和parl==1.3.2环境下不能复现你的错误，可以提供下你的parl版本，以及完整的错误信息吗？

**Comment by kabuwaniu** [comment]
您好， 我的parl版本是1.3.1

**Comment by kabuwaniu** [comment]
我尝试升级parl到1.3.2 但仍然有这些问题
D:\Anaconda3\python.exe C:/Users/UAV_Robot/Desktop/ddpg_robotics/palleratest.py
[07-16 14:21:46 MainThread @logger.py:224] Argv: C:/Users/UAV_Robot/Desktop/ddpg_robotics/palleratest.py
D:\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
[07-16 14:21:50 MainThread @client.py:367] Remote actors log url: http://10.162.159.87:60022/logs?client_id=10.162.159.87_60375_1594880510
Traceback (most recent call last):
  File "C:/Users/UAV_Robot/Desktop/ddpg_robotics/palleratest.py", line 14, in <module>
    a = A()
  File "D:\Anaconda3\lib\site-packages\parl\remote\remote_decorator.py", line 137, in __init__
    raise RemoteError('__init__', traceback_str)
parl.remote.exceptions.RemoteError: [PARL remote error when calling function `__init__`]:
[Errno 22] Invalid argument: 'xparl_C:/Users/UAV_Robot/Desktop/ddpg_robotics/palleratest.py'
traceback:
Traceback (most recent call last):
  File "d:\anaconda3\lib\site-packages\parl\remote\job.py", line 316, in wait_for_connection
    cls = load_remote_class(file_name, class_name, end_of_file)
  File "d:\anaconda3\lib\site-packages\parl\remote\utils.py", line 65, in load_remote_class
    with open(tmp_file_name, 'w') as t_file:
OSError: [Errno 22] Invalid argument: 'xparl_C:/Users/UAV_Robot/Desktop/ddpg_robotics/palleratest.py'


Process finished with exit code 1
![image](https://user-images.githubusercontent.com/46389180/87634535-09a08200-c770-11ea-9227-00af1b854f86.png)

**Comment by zenghsh3** [comment]
你好，方便提供下windows版本和Python版本信息？（目前我们只在windows10和python3环境下测试过xparl）

**Comment by kabuwaniu** [comment]
window10    python3.7  请问 xparl 是要在.py 文件下的终端 运行吗

**Comment by kabuwaniu** [comment]
用的是  paddlepaddle-gpu                   1.6.3.post107

**Comment by zenghsh3** [comment]
你好，我们推测应该是由于文件分隔符混用导致的，如下图所示，存在两种文件分隔符
![image](https://user-images.githubusercontent.com/5762635/87636029-9e0be400-c772-11ea-9ed2-93106598f3e5.png)

可能跟运行终端相关，请问你是用什么终端运行的呢？是否可以尝试用windows默认的终端测试下呢？

**Comment by kabuwaniu** [comment]
你好  为了避免 文件 问题，我尝试直接在window 下的CMD 终端   py文件所处的文件夹内  来运行 代码 
![image](https://user-images.githubusercontent.com/46389180/87637292-90575e00-c774-11ea-81e6-b67ce610df0a.png)

![image](https://user-images.githubusercontent.com/46389180/87637466-d57b9000-c774-11ea-8302-183526c4e1b3.png)

**Comment by zenghsh3** [comment]
你好，看这个错误提示是由于paddle导致的，可以尝试先卸载paddle，再运行脚本

**Comment by kabuwaniu** [comment]
你好 请问您 推荐装哪个版本的paddle
![image](https://user-images.githubusercontent.com/46389180/87639486-ebd71b00-c777-11ea-9e1b-4cfaac0a37a3.png)
因为我的电脑 有显卡 所以安装的  是gpu版本的 paddle  而并行运算是不是用的是cpu模块的东西  所以 gpu版本的paddle会冲突呢

**Comment by zenghsh3** [comment]
你好，parl的并行是不依赖于paddle的，paddle安装建议参考官网教程：https://www.paddlepaddle.org.cn/install/quick

**Comment by kabuwaniu** [comment]
你好 尝试重装了 parl=1.3.2， paddle-gpu=1.6.3.post107
出现了以下错误
![image](https://user-images.githubusercontent.com/46389180/87665955-5d27c580-c79a-11ea-9a3a-48a039f71e90.png)
![image](https://user-images.githubusercontent.com/46389180/87665998-6e70d200-c79a-11ea-9d0e-45e723d1dcea.png)

**Comment by kabuwaniu** [comment]
你好 尝试重装了 parl=1.3.2， paddle-gpu=1.6.3.post107  成功 
![image](https://user-images.githubusercontent.com/46389180/87670440-4dac7a80-c7a2-11ea-9fd6-ca0fd4046de5.png)
在非终端的平台上运行会出现错误  并且如果cpu在干其他事情的时候 运行.py 会出现错误

**Comment by yangsia** [comment]
同样的问题，如果windows下用pycharm执行就会报错。希望可以给出解决方案

**Comment by TomorrowIsAnOtherDay** [comment]
pycharm 给的报错提示是什么样的呢？麻烦截个图我们看下

**Comment by yangsia** [comment]
![image](https://user-images.githubusercontent.com/76164429/102489672-c3e23f80-40a8-11eb-8721-ca6a57205164.png)
parl==1.3.2 python==3.7.7 paddlepaddle==1.6.3

try.py 如下：
import threading
import parl


@parl.remote_class
class A(object):
    def run(self):
        ans = 0
        for i in range(100000000):
            ans += i
        print(ans)
threads = []

parl.connect("localhost:8010")
for _ in range(5):
    a = A()
    th = threading.Thread(target=a.run)
    th.start()
    threads.append(th)
for th in threads:
    th.join()

**Comment by TomorrowIsAnOtherDay** [comment]
parl 目前的最新版本是1.3.3哈，我们相比1.3.2提升了文件分发的兼容性，请尝试下1.3.3版本。

**Comment by yangsia** [comment]
我貌似debug了这个问题，在Lib/site-packages/parl/remote/utils.py里面。在
module_name = 'xparl_' + file_name
tmp_file_name = 'xparl_' + file_name + '.py'
之前加上
if "/" in file_name or "\\" in file_name:
        file_name = os.path.split(file_name)[-1]

搞定。（开始要 import os）
![image](https://user-images.githubusercontent.com/76164429/102490772-40c1e900-40aa-11eb-9b67-c7ed87eb4873.png)
就是传绝对路径的时候会出这个问题，卡了我一个下午
（吐槽：这里debug要不停地重新开服务关服务，超级麻烦）

**Comment by TomorrowIsAnOtherDay** [comment]
赞，好强的动手能力。我们这边跟进看看能否在Windows复现。

**Comment by yangsia** [comment]
BTW: parl 1.3.3 一样不好使

**Comment by TomorrowIsAnOtherDay** [comment]
这个是pycharm的分隔符问题0.0我们修复下
