### ISSUE TITLE
How to create a fully reproducible environment with PARL?

### ISSUE THREAD

**Issue by familyld** [PaddlePaddle/PARL#356]
PARL is a high-quality reinforcement learning framework. As the development team claims "**Reproducible**" is one of the key features of PARL, I would like to ask how to eliminate the randomness during the training and testing process, e.g., what are the factors that may cause randomness and how to prevent them.

Thank you.

**Comment by TomorrowIsAnOtherDay** [comment]
Hi, Thanks for your interest in PARL.
**Reproducible** means that we aim to provide high-quality implementation that reaches the same performance as the paper, unlike some other frameworks that only test the performance on some simple environments such as Cartpole.

------------------

Regarding the randomness, it is an avoidable problem in most real-world tasks. We should improve the robustness of our algorithms, instead of trying to eliminate it.

**Comment by familyld** [comment]
@TomorrowIsAnOtherDay Thanks for your quick reply! The robustness is definitely important in real-world applications. But I am still interested in **how to reproduce the same result with the same code** since this may help us better identify potential problems. Do you have any good advice for it? e.g., what random seeds should be fixed.

Thank you.

**Comment by TomorrowIsAnOtherDay** [comment]
We often focus on three parts:

1.  environmental randomness
2. machine learning framework randomness
3. interaction randomness(how we choose the action randomly)

To know more about the randomness in RL, I suggest you to watch the following video:
https://www.youtube.com/watch?v=Vh4H0gOwdIg

**Comment by familyld** [comment]
Cool. The video is really a good reference.

For the environmental randomness,  I can set `env.seed(seed) `. But I am not quite sure about the second one, i.e., the randomness in the PARL framework. Does PARL provide any interface for fixing random seeds and/or something else in this framework that may cause randomness irrespective to the environment and other packages? Thanks.

**Comment by TomorrowIsAnOtherDay** [comment]
Sorry, we do not provide such APIs to eliminate the randomness.
You can try the following APIs:
np.random.seed(1024)
random.seed(1024)
For randomness in Paddle, please refer to: https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/Program_cn.html#random-seed

**Comment by familyld** [comment]
Thanks.
