### ISSUE TITLE
在parl 的model 里面增加一个网络

### ISSUE THREAD

**Issue by kabuwaniu** [PaddlePaddle/PARL#363]
你好 我想在parl 基础上设计其他的方法 其中model 里面有了 action网络和critic网络 
我还想再弄一个predict网络 我增加后，在执行目标网络 到当前网络复制函数时会报错 
![image](https://user-images.githubusercontent.com/46389180/88387895-09def400-cde6-11ea-8bbe-43303fbc1376.png)
想请问 在parl 的model里面 我还可以增加网络吗 
![image](https://user-images.githubusercontent.com/46389180/88387961-28dd8600-cde6-11ea-843d-fd0981e6efae.png)

**Comment by TomorrowIsAnOtherDay** [comment]
`sync_target`这个函数的实现可以发出来看下吗？

**Comment by kabuwaniu** [comment]
![image](https://user-images.githubusercontent.com/46389180/88393505-50d1e700-cdf0-11ea-959e-9e492d0f8ed0.png)
你好 sync_target 就是你们DDPG框架下的软更新

**Comment by TomorrowIsAnOtherDay** [comment]
感谢反馈。
按道理，添加一个model不会出现问题的，能否贴下完整的model代码和agent代码，让我们在本地复现一下？

**Comment by kabuwaniu** [comment]
from parl import layers

from copy import deepcopy
from paddle import fluid

import numpy as np
import parl

class ActorModel(parl.Model):
    def __init__(self, act_dim):
        hid_size = 200
        self.fc1 = layers.fc(size=hid_size, act='relu')
        self.fc2 = layers.fc(size=hid_size, act='relu')
        self.fc3 = layers.fc(size=10, act='relu')
        self.fc4 = layers.fc(size=act_dim, act='tanh')

    def policy(self, obs):
        hid = self.fc1(obs)
        hid = self.fc2(hid)
        hid = self.fc3(hid)
        means = self.fc4(hid)
        return means

class CriticModel(parl.Model):
    def __init__(self):
        hid_size = 100
        self.fc1 = layers.fc(size=hid_size, act='relu')
        self.fc2 = layers.fc(size=10, act='relu')
        self.fc3 = layers.fc(size=1, act=None)

    def value(self, obs):
            # concat = layers.concat([obs, act], axis=1)
        hid = self.fc1(obs)
        hid = self.fc2(hid)
        Q = self.fc3(hid)
        Q = layers.squeeze(Q, axes=[1])
        return Q

class PredictModel(parl.Model):
    def __init__(self, obs_dim):
        hid_size = 200
        self.fc1 = layers.fc(size=hid_size, act='relu')
        self.fc2 = layers.fc(size=hid_size, act='relu')
        self.fc3 = layers.fc(size=hid_size, act='relu')
        self.fc4 = layers.fc(size=10, act='relu')
        self.fc5 = layers.fc(size=obs_dim, act='tanh')

    def predict(self, obs, act):
        concat = layers.concat([obs, act], axis=1)
        hid = self.fc1(concat)
        hid = self.fc2(hid)
        hid = self.fc3(hid)
        hid = self.fc4(hid)
        next_obs = self.fc5(hid)
        return next_obs

#构造网络结构 critic and actor
class Model(parl.Model):
    def __init__(self, act_dim, obs_dim):
        self.predict_model = PredictModel(obs_dim)
        self.actor_model = ActorModel(act_dim)
        self.critic_model = CriticModel()

    def policy(self, obs):
        return self.actor_model.policy(obs)

    def value(self, obs):
        return self.critic_model.value(obs)

    def predict(self, obs, act):
        return self.predict_model.predict(obs, act)

    def get_actor_params(self):
        return self.actor_model.parameters()

# 构造loss 函数
class DDPG(parl.Algorithm):
    def __init__(self,
                 model,
                 gamma=None,
                 tau=None,
                 actor_lr=None,
                 critic_lr=None,
                 predict_lr=None):
        assert isinstance(gamma, float)
        assert isinstance(tau, float)
        assert isinstance(actor_lr, float)
        assert isinstance(critic_lr, float)
        assert isinstance(predict_lr, float)
        self.gamma = gamma    # record 衰减因子
        self.tau = tau        # 软同步参数
        self.actor_lr = actor_lr       # actor学习率
        self.critic_lr = critic_lr     # critic学习率
        self.predict_lr = predict_lr  # predict学习率
        self.model = model             #
        self.target_model = deepcopy(model)

    def policy(self, obs):
        """ 使用 self.model 的 actor model 来预测动作"""
        return self.model.policy(obs)

    def predict(self, obs, action):
        """使用 self .model 的 actor model 来预测状态"""
        return self.model.predict(obs, action)

    # 预测模型的训练 预处理前 单独训练
    def model_learn(self, obs, action, next_obs):
        predict_cost = self._predict_learn(obs, action, next_obs)
        return predict_cost

    def learn(self, obs, action, reward, next_obs, terminal):
        """ 用DDPG算法更新 actor 和 critic"""
        actor_cost = self._actor_learn(obs)
        critic_cost = self._critic_learn(obs, reward, next_obs, terminal)
        predict_cost = self._predict_learn(obs, action, next_obs)
        return actor_cost, critic_cost, predict_cost

    def _predict_learn(self, obs, action, next_obs):
        next_s = self.model.predict(obs, action)
        cost = layers.square_error_cost(next_s, next_obs)
        cost = layers.reduce_mean(cost)
        optimizer = fluid.optimizer.AdamOptimizer(self.critic_lr)
        optimizer.minimize(cost)
        return cost

    def _actor_learn(self, obs):
        action = self.model.policy(obs)          # 预测行动
        state = self.model.predict(obs, action)  # 行动预测下一步的
        Q = self.model.value(state)              # 预测下一个状态的q值
        cost = layers.reduce_mean(-1.0 * Q)
        optimizer = fluid.optimizer.AdamOptimizer(self.actor_lr)
        optimizer.minimize(cost, parameter_list=self.model.get_actor_params())  # 只优化 行动参数
        return cost

    def _critic_learn(self, obs, reward, next_obs, terminal):
        next_value = self.target_model.value(next_obs)
        terminal = layers.cast(terminal, dtype='float32')
        target_Q = reward + (1.0 - terminal) * self.gamma * next_value
        target_Q.stop_gradient = True
        Q = self.model.value(obs)
        cost = layers.square_error_cost(Q, target_Q)
        cost = layers.reduce_mean(cost)
        optimizer = fluid.optimizer.AdamOptimizer(self.critic_lr)
        optimizer.minimize(cost)
        return cost

    def sync_target(self, decay=None, share_vars_parallel_executor=None):
        """ self.target_model从self.model复制参数过来，若decay不为None,则是软更新"""
        if decay is None:
            decay = 1.0 - self.tau

        self.model.sync_weights_to(
            self.target_model,
            decay=decay,
            share_vars_parallel_executor=share_vars_parallel_executor)

class Agent(parl.Agent):
    def __init__(self, algorithm, obs_dim, act_dim):
        assert isinstance(obs_dim, int)
        assert isinstance(act_dim, int)
        self.obs_dim = obs_dim
        self.act_dim = act_dim
        super(Agent, self).__init__(algorithm)

        # 注意：最开始先同步self.model和self.target_model的参数.
        self.alg.sync_target(decay=None)

    def build_program(self):

        self.pred_program = fluid.Program()  # 动作产生
        self.learn_program = fluid.Program()  # 训练所有网络
        self.predict_program = fluid.Program()  # 下个状态预测
        self.model_learn__program = fluid.Program()  # 训练预测模型网络

        with fluid.program_guard(self.pred_program):
            obs = layers.data(
                name='obs', shape=[self.obs_dim], dtype='float32')
            self.policy_act = self.alg.policy(obs)

        with fluid.program_guard(self.predict_program):
            obs = layers.data(
                name='obs', shape=[self.obs_dim], dtype='float32')
            act = layers.data(
                name='act', shape=[self.act_dim], dtype='float32')
            self.pred_model = self.alg.predict(obs, act)

        with fluid.program_guard(self.learn_program):
            obs = layers.data(
                name='obs', shape=[self.obs_dim], dtype='float32')
            act = layers.data(
                name='act', shape=[self.act_dim], dtype='float32')
            reward = layers.data(name='reward', shape=[], dtype='float32')
            next_obs = layers.data(
                name='next_obs', shape=[self.obs_dim], dtype='float32')
            terminal = layers.data(name='terminal', shape=[], dtype='bool')

            _, self.critic_cost, self.model_cost = self.alg.learn(obs, act, reward, next_obs,
                                                 terminal)

        with fluid.program_guard(self.model_learn__program):
            obs = layers.data(
                name='obs', shape=[self.obs_dim], dtype='float32')
            act = layers.data(
                name='act', shape=[self.act_dim], dtype='float32')
            next_obs = layers.data(
                name='next_obs', shape=[self.obs_dim], dtype='float32')
            self.model_cost = self.alg.model_learn(obs, act, next_obs)


###################################################

    def policy(self, obs):
        obs = np.expand_dims(obs, axis=0)
        act = self.fluid_executor.run(
            self.pred_program, feed={'obs': obs},
            fetch_list=[self.policy_act])[0]
        act = np.squeeze(act)
        return act

    def predict(self, obs, act):
        obs = np.expand_dims(obs, axis=0)
        act = np.expand_dims(act, axis=0)
        obs_next = self.fluid_executor.run(
            self.predict_program, feed={'obs': obs, 'act': act},
            fetch_list=[self.policy_act])[0]
        obs_next = np.squeeze(obs_next)
        return obs_next

    def learn(self, obs, act, reward, next_obs, terminal):
        feed = {
            'obs': obs,
            'act': act,
            'reward': reward,
            'next_obs': next_obs,
            'terminal': terminal
        }
        critic_cost = self.fluid_executor.run(
            self.learn_program, feed=feed, fetch_list=[self.critic_cost])[0]
        self.alg.sync_target()
        return critic_cost

    def model_learn(self, obs, act, next_obs):
        feed = {
            'obs': obs,
            'act': act,
            'next_obs': next_obs,
        }
        model_cost = self.fluid_executor.run(
            self.model_learn__program, feed=feed, fetch_list=[self.model_cost])[0]
        return model_cost

**Comment by kabuwaniu** [comment]
class ActorModel(parl.Model):
    def __init__(self, act_dim):
        hid_size = 200
        self.fc1 = layers.fc(size=hid_size, act='relu')
        self.fc2 = layers.fc(size=hid_size, act='relu')
        self.fc3 = layers.fc(size=10, act='relu')
        self.fc4 = layers.fc(size=act_dim, act='tanh')

**Comment by kabuwaniu** [comment]
[DDPG.txt](https://github.com/PaddlePaddle/PARL/files/4977004/DDPG.txt)
你好我上传这个txt文件，我写的model在这个里面  我的网络结构是 相当于在 原来actor critic 的基础上 再加一个model 预测未来输出的

**Comment by TomorrowIsAnOtherDay** [comment]
收到。我们已经在本地复现定位了下这个问题，主要是静态图的运算规则导致的：
原始的DDPG实现中，`target_model`的policy还有value都是用于计算的，但是在你的代码中，`target_model`只使用了value这部分，`target_policy` 并没有用于计算，这就导致其参数并没有初始化。

https://github.com/PaddlePaddle/PARL/blob/3a27f4072ef30786bad21318aa1ecdde23fc3292/parl/algorithms/fluid/ddpg.py#L77

建议：

- 把model拆成多个传进algorithm，然后只对value_model创建target_model 。
- 或者计算图中使用target_model中的policy 。

PS：后续我们升级到动态图之后，这一问题不复存在。
