### ISSUE TITLE
Fail to return model weights by using model.get_weights()

### ISSUE THREAD

**Issue by familyld** [PaddlePaddle/PARL#364]
Version:
paddlepaddle==1.6.2
parl==1.3.1

Code:
```
import parl
import paddle.fluid as fluid
from parl import layers

class CartpoleModel(parl.Model):
    def __init__(self, act_dim):
        hid_size = 8
        self.fc1 = layers.fc(size=hid_size, act='relu')
        self.fc2 = layers.fc(size=act_dim, act=None)

    def value(self, obs):
        h = self.fc1(obs)
        Q = self.fc2(h)
        return Q

action_dim = 2
model = CartpoleModel(act_dim=action_dim)
model.get_weights()
```

Error:
```
AssertionError: Cannot find fc.b_32 in scope. Perhaps you need to make the variable persistable by using var.persistable = True in your program.
```

**Comment by familyld** [comment]
It seems like the model is initialized after building programs so the parameters are still unavailable in the above code snippet.  But **when and how the model initialized exactly**? I would also like to ask **where can I set the random seed for model parameter initialization.** Thank you.

**Comment by TomorrowIsAnOtherDay** [comment]
Hi, familyId.
Thanks for your interest in PARL. As the backend(paddle) of PARL is not a DL framework with eager mode.
The agent will initialize all the parameters when we create an agent:
```python
model = Model()
alg = Algorithm(model)
agent = Agent(alg) # here
```
Regarding the last problem, please refer to the following page:
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/Program_cn.html#random-seed

**Comment by familyld** [comment]
Thanks. But this link doesn't really provide enough information for the problem. I found the model parameters are initialized after executing [this line](https://github.com/PaddlePaddle/PARL/blob/c85204dc1937c13950d16d022341b2cecdc32e7e/parl/core/fluid/agent.py#L84), i.e., after running the `default_startup_program()` when initializing the agent. However, fixing the random seed of this default program makes no changes. The initialized model parameters are still different.

**Comment by familyld** [comment]
Fixing fluid.default_startup_program().random_seed is what I need.

**Comment by TomorrowIsAnOtherDay** [comment]
Great!
