### ISSUE TITLE
多机并行应该如何进行调试？

### ISSUE THREAD

**Issue by helloworld0000** [PaddlePaddle/PARL#366]
修改了一下impala的样例代码，想要尝试一下多机并行，在移除 @parl.remote_class 单机已经能够测试跑通，并可以输出日志。
使用多机进行尝试时，运行后发现评估信息为空。想要查看日志 如图：

![image](https://user-images.githubusercontent.com/12150210/88637370-a9ed9380-d0ec-11ea-8089-2d27f5c4c0a2.png)

![image](https://user-images.githubusercontent.com/12150210/88637768-2aac8f80-d0ed-11ea-805d-6da3581b64f4.png)

![image](https://user-images.githubusercontent.com/12150210/88637813-35672480-d0ed-11ea-8f2c-209351ec600e.png)

![image](https://user-images.githubusercontent.com/12150210/88637863-4879f480-d0ed-11ea-880f-ac61469be8d6.png)

发现运行日志不存在，请问如何获得worker的运行日志，方便调试呢？

**Comment by tanzeyy** [comment]
你好，请问可以提供一下操作系统和parl的版本信息吗？

**Comment by helloworld0000** [comment]
parl 版本是 1.3.2
操作系统 信息如下
Linux version 3.10.0-957.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (RedHat 4.8.5-36) (GCC) ) #1 SMP Thu Nov 8 23:39:32 UTC 2018

**Comment by tanzeyy** [comment]
你好，请进一步提供如下信息，方便我们复现问题：
- actor的输出代码
- 本地日志文件，路径：`~/.parl_data/job/{job_id}`（如图所示其中一个job的路径为：`~/.parl_data/job/10.136.238.25_45252_1595923040`）。正常情况下此路径下会有两个文件：`log.log`和`stdout.log`，方便的话请提供此两个文件的内容，谢谢~

如果是分布式运行的parl（worker节点在远程机器上），则去对应的机器的对应路径下寻找~

**Comment by helloworld0000** [comment]
只有log.log    没有stdout.log
log.log 中看到了报错内容，是import的问题，在有错误的情况下是无法通过url获取错误信息的么？

**Comment by tanzeyy** [comment]
请问能提供log.log中具体的报错内容吗？
如果log.log中出现了错误，一些服务会启动失败，无法获得对应节点的信息。

**Comment by helloworld0000** [comment]
好的，稍等提供，重新运行了一下发现在 Actor Num=2的时候，目录下并没有log，log不存在，是在进行一些其他很需要时间的操作么？例如依赖安装？需要时间大概九分钟，九分钟后这份log日志出来

访问依然是 {"message":"Log not exsits, please check your job_id"}
log日志内容为
![image](https://user-images.githubusercontent.com/12150210/88649410-6ac63f00-d0fa-11ea-86bc-232153e04248.png)

![image](https://user-images.githubusercontent.com/12150210/88649519-83cef000-d0fa-11ea-9b76-ebc0e6a256d1.png)
然后此处为0，没有看到明显的报错

**Comment by tanzeyy** [comment]
你好，正常情况下这个过程花费的时间通常在几秒钟左右。方便的话，请进行以下操作，我们可以进一步排查问题所在。
- 在单台机器上启动parl集群，使用`examples/IMPALA`里面的默认配置运行并提供对应的log文件
- 如果在多台机器运行parl集群（worker节点connect到master节点），这种情况下请检查所使用机器的：
  - python和各个依赖库的版本是否一致（可以通过`pip list`来检查）
  - 多台机器的网络配置情况（防火墙的配置，多台机器之间的端口访问是否有限制等）

**Comment by helloworld0000** [comment]
您好我尝试了单机启动parl集群，对应的log文件：

^[[32m[07-29 10:29:51 MainThread @job.py:361]^[[0m [Job] Job 10.31.77.11_37948_1595989791 initialized. Reply heartbeat socket Address: 10.31.77.11:37948.¬
^[[33m[07-29 11:30:09 MainThread @remote_decorator.py:81]^[[0m ^[[5m^[[33mWRN^[[0m Note: this object willbe runnning as a local object¬
^[[31m[07-29 11:30:09 MainThread @job.py:324]^[[0m ^[[4m^[[5m^[[31mERR^[[0m traceback:¬
Traceback (most recent call last):¬
  File "/root/env/lib/python3.7/site-packages/parl/remote/job.py", line 317, in wait_for_connection¬
    args, kwargs = cloudpickle.loads(message[2])¬
AttributeError: Can't get attribute 'ActionSpace_l2rpn_neurips_2020_track1_small' on <module 'grid2op.Space.GridObjects' from '/root/env/lib/python3.7/site-packages/grid2op/Space/GridObjects.py'>¬
¬
^[[31m[07-29 11:30:09 MainThread @job.py:378]^[[0m ^[[4m^[[5m^[[31mERR^[[0m Error occurs when running a single task. We will reset this job. ¬
Reason:¬
^[[31m[07-29 11:30:09 MainThread @job.py:380]^[[0m ^[[4m^[[5m^[[31mERR^[[0m traceback:¬
Traceback (most recent call last):¬
  File "/root/env/lib/python3.7/site-packages/parl/remote/job.py", line 373, in run¬
    assert obj is not None¬
AssertionError¬

请问在单机移除 @parl.remote_class 时单纯使用多线程是可以跑通的，parl在并行时的拷贝是什么机理呢？
使用url依然无法访问。

**Comment by zenghsh3** [comment]
多机通信是通过cloudpickle进行序列化，pyzmq进行数据传输，看错误提示应该是该object不可被序列化

**Comment by helloworld0000** [comment]
![image](https://user-images.githubusercontent.com/12150210/88768546-d4535580-d1ad-11ea-845b-cc09916ba2e2.png)

仔细看了一下这部分的代码，发现 @parl.remote_class 后，先加载remote class 代码，再使用cloudpickle 加载 remote class的初始化传参，上面的问题是因为load时，remote环境中cloudpickle无法解析初始化传参的问题。

从而导致没有执行  logfile_path = os.path.join(self.log_dir, 'stdout.log')
因此没有 stdout.log 日志
也就是最终导致没有日志的原因。

感谢解答，希望可以帮助到更多同学。
