### ISSUE TITLE
AssertionError: the action should be in range [-1.0, 1.0] 动作范围超限？

### ISSUE THREAD

**Issue by jkren6** [PaddlePaddle/PARL#367]
![action_mapping](https://user-images.githubusercontent.com/46992227/88814857-397a6b80-d1ed-11ea-81aa-daeff7e504e5.jpeg)
在使用PARL官方提出的TD3算法训练时，偶尔会提示在action_mapping的时候，动作超出[-1.0, 1.0]范围的断言提示，然后就中断训练了。有的时候一开始训练就出现，有时训练几千的episode的时候才出现这个错误。

有同学说可能是PaddlePaddle版本的问题，建议我升级版本。请问是这样解决么，是否旧版本存在这个问题？

TD3 Repo: PARL/examples/TD3/

**Comment by EastSmith** [comment]
可以加 action = np.clip(action, -1,1) 这行代码把动作强制截断到[-1.0, 1.0]。经过试验，截断神经网络的输出并限制在[-1.0, 1.0]之间，神经网络也能收敛。

**Comment by TomorrowIsAnOtherDay** [comment]
这个是卡精度了，与paddle框架无关的，我fix一下，感谢反馈：）
