### ISSUE TITLE
为何parl中的网络可以不用输入input参数?

### ISSUE THREAD

**Issue by dbsxdbsx** [PaddlePaddle/PARL#378]
如SAC算法中：
```
class ActorModel(parl.Model):
    def __init__(self, act_dim):
        hid1_size = 400
        hid2_size = 300

        self.fc1 = layers.fc(size=hid1_size, act='relu')
        self.fc2 = layers.fc(size=hid2_size, act='relu')
        self.mean_linear = layers.fc(size=act_dim)
        self.log_std_linear = layers.fc(size=act_dim)

    def policy(self, obs):
        hid1 = self.fc1(obs)
        hid2 = self.fc2(hid1)
        means = self.mean_linear(hid2)
        log_std = self.log_std_linear(hid2)
        log_std = layers.clip(log_std, min=LOG_SIG_MIN, max=LOG_SIG_MAX)

        return means, log_std
```
这里的`layers.fc`都不用输入`input`参数的，但是看了下`parl.layers`不就是继承的`paddle.fluid.layers`么，为何在其他地方实验行不通呢？

**Comment by zenghsh3** [comment]
你好，对于可训练、带参数（parameters）的layers，`parl.layers`是重新封装了`paddle.fluid.layers`，使其类似于动态图的用法；代码逻辑如下：
https://github.com/PaddlePaddle/PARL/blob/28ea49fcc89c228be526e09d0c29d7c13a8eca12/parl/core/fluid/layers/layer_wrappers.py#L137
对于不可训练、不带参数（parameters）的layers，`parl.layers`是等价于`paddle.fluid.layers`。

**Comment by TomorrowIsAnOtherDay** [comment]
也就是说，我们的参数接口与paddle的接口一样，但是使用上是面向对象的写法。

**Comment by dbsxdbsx** [comment]
@zenghsh3 , 你的意思是paddle的动态图网络接口可以不用输入input size吗？ 我实践下来不行呢，用的`dynagraph.nn.Linear`测试的。又或者是2.0版本才有？

**Comment by zenghsh3** [comment]
不是的，只是说类似于动态图的写法，但跟paddle的动态图接口是有区别的，具体以paddle动态图文档为准哈

**Comment by dbsxdbsx** [comment]
好的，感谢2位，不过也希望能将这种便利性的功能添加到paddlepaddle中...
