### ISSUE TITLE
[AssertionError]: the action should be in range [-1.0, 1.0]

### ISSUE THREAD

**Issue by Ryan906k9** [PaddlePaddle/PARL#380]
PPO 的 example 中，train.py 文件中，run_evaluate_episode 函数需要加上 action = np.clip(action, -1.0, 1.0)，否则有可能出现超过范围的情况导致程序运行失败。
另外，建议可以在里面加上中间阶段进行模型保存的语句，否则整个训练过程很长，如果由于中间断掉要从头开始很可惜。

**Comment by TomorrowIsAnOtherDay** [comment]
Hi，Ray 早上好。
感谢您的使用反馈，我逐个回答下：
1）关于clip。这个问题之前已经有用户反馈过#367 。我们已经在#368 中修复这个问题，使用最新版本的代码即可。
2）关于保存中间模型，中间突然出问题重跑确实挺费时间的。PARL 为了提供精简的代码示例，尽可能地减少了不必要的示例代码，所以我们倾向于不增加参数保存和加载模型的代码。如有需要，请参考下面这个回复。
https://github.com/PaddlePaddle/PARL/issues/322#issuecomment-650884107

**Comment by Ryan906k9** [comment]
我看了下 PPO example 中的 evaluate 里面的代码应该并没有修正这个问题，难道是我看错地方了吗？

**Comment by TomorrowIsAnOtherDay** [comment]
这个报错主要是action_mapping 函数引起的，该函数的实验不在PPO文件夹里面。

**Comment by Ryan906k9** [comment]
哦，明白了，谢谢
