### ISSUE TITLE
Inconsistency issue in function **evaluate**

### ISSUE THREAD

**Issue by jncsw** [PaddlePaddle/PARL#386]
Hi, we are developing some tools to help detect bugs for Python automatically. Our tool finds an inconsistency below.

https://github.com/PaddlePaddle/PARL/blob/d6e82f0145b6a0e926280cd6aa2ae2cb20eb9b9d/examples/DQN/train.py#L57

The definition of the function **evaluate** in this file is **evaluate(agent, env, render=False)**. 

However, in many other definitions, the **evaluate** is defined as **evaluate(env, agent, render=False)**.

```
examples/others/deepes.py
def evaluate(env, agent):
examples/tutorials/homework/lesson3/dqn_mountaincar/train.py
def evaluate(env, agent, render=False):
examples/tutorials/homework/lesson4/policy_gradient_pong/train.py
def evaluate(env, agent, render=False):
examples/tutorials/homework/lesson5/ddpg_quadrotor/train.py
def evaluate(env, agent, render=False):
examples/tutorials/lesson3/dqn/train.py
def evaluate(env, agent, render=False):
examples/tutorials/lesson4/policy_gradient/train.py
def evaluate(env, agent, render=False):
examples/tutorials/lesson5/ddpg/train.py
def evaluate(env, agent, render=False):
```

It would be better is this issue got fixed. Thanks!

**Comment by TomorrowIsAnOtherDay** [comment]
Hi @jncsw , thanks for your report. **This is not an issue**. These function named "evaluate" are in the folder `examples `, where we place various separate examples for different algorithms. They can be viewed as different projects.
When will having the same function names be an issue? 
I think if they are in the framework code.
