### ISSUE TITLE
Alpha Zero plays same games on each thread.

### ISSUE THREAD

**Issue by goshawk22** [PaddlePaddle/PARL#401]
Each thread is run with the same seed which means that all the games are the same.
This is then the same as running it in single threaded, but it could also bias the network.

**Comment by zenghsh3** [comment]
Thanks for your issue and PR. But I don't understand why we need the seed here.

**Comment by TomorrowIsAnOtherDay** [comment]
Hi, @goshawk22 , thanks for your contribution. This may cause the data collected by different thread to be identical.  It will limit the data diversity.

**Comment by TomorrowIsAnOtherDay** [comment]
Please update the PR according to the comments.
