### ISSUE TITLE
并行问题

### ISSUE THREAD

**Issue by yingyingll** [PaddlePaddle/PARL#404]
您好，

我仿照a2c写了一个并行框架的代码，遇到两个问题想要咨询一下～

1. 我在单机上启动了cluster集群，20个actor，运行起来后想kill掉，如何把所有进程都kill掉呢？需要自己手动kill吗？试了一下xparl stop感觉不起作用。（发现主agent停掉以后，查看还有很多python的进程在运行)
2. examples中的A2C paddle版本，主agent想要在gpu上训练，需要改动train的代码吗？例如 mode.cuda() 这种，还是说直接设置export CUDA_VISIBLE_DEVICES=[GPU_ID_TO_USE]就可以呢?

谢谢！

**Comment by TomorrowIsAnOtherDay** [comment]
1. xparl stop 即可。这个会把所有parl并行相关的进程kill掉的。如果还有进程没办法kill 掉，请确认下哪些残留的进程是否是别的账号启动的。

**Comment by zenghsh3** [comment]
A2C训练默认支持GPU训练的，直接export CUDA_VISIBLE_DEVICES=0即可

**Comment by yingyingll** [comment]
> A2C训练默认支持GPU训练的，直接export CUDA_VISIBLE_DEVICES=0即可

感谢回答，我是在a2c的train.py的这个位置加了一下，
![image](https://user-images.githubusercontent.com/44187354/90859015-ee9ddf00-e3b9-11ea-88a7-060359213e1d.png)
服务器上单机启动cluster运行，目前报错
![image](https://user-images.githubusercontent.com/44187354/90858783-6d464c80-e3b9-11ea-8010-6c17812542ff.png)
请问什么原因呢？目前不使用GPU是可以的跑通的～

**Comment by TomorrowIsAnOtherDay** [comment]
建议先检查下你的机器能否跑paddle的GPU版本哈，我们不是paddle框架的开发人员，我们的仓库主要针对强化学习的。

**Comment by yingyingll** [comment]
嗯嗯 感谢回答，还想请教一下～

1. 直接设置export CUDA_VISIBLE_DEVICES=0，多个Actor使用的仍然是CPU，Learner只使用一个GPU，是这个逻辑吗？
2. 在benchmark路径的torch的A2C例子中，我看到actor.oy里面也设置了CUDA_VISIBLE_DEVICES,这时候是actor和learner都在使用gpu，是这样不？

谢谢！

**Comment by TomorrowIsAnOtherDay** [comment]
1.对的，因为默认actor里面是使用CPU执行的，只有learner这边会用GPU
2.如果希望actor也用GPU，需要在actor里面也设置的。

-----------------
如果希望在actor里面使用GPU，这个需要使用最新版本的哈，就是git clone当前仓库直接安装。

**Comment by yingyingll** [comment]
> 1.对的，因为默认actor里面是使用CPU执行的，只有learner这边会用GPU
> 2.如果希望actor也用GPU，需要在actor里面也设置的。
> 
> 如果希望在actor里面使用GPU，这个需要使用最新版本的哈，就是git clone当前仓库直接安装。

了解了，给反馈效率点个赞。下午的报错解决了，确实与PARL无关，感谢解答。

**Comment by Gaoee** [comment]
@yingyingll ，请问你是用pytorch写的吗，现在是可以让actor使用GPU了吗？

**Comment by Gaoee** [comment]
@TomorrowIsAnOtherDay 请问用pytorch编写的并行RL，想让actor也使用GPU，需要具体怎么修改actor呢？

```
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
self.actor_cuda = False
```
将上面两句改过成：
```
os.environ['CUDA_VISIBLE_DEVICES'] = （GPU device）
self.actor_cuda = True
```

就可以了吗？

**Comment by TomorrowIsAnOtherDay** [comment]
是的，这样应该就没问题了。如果有问题，请随时开个issue：）
祝好

**Comment by Gaoee** [comment]
谢谢，我试用了，没有问题，但好像要用最新的PARL才行。

**Comment by TomorrowIsAnOtherDay** [comment]
对的，我们最近升级了下并行，进一步扩展了兼容性，现在很多东西都可以序列化过去给其他机器，通用性进一步上升。
