### ISSUE TITLE
a2c参数问题

### ISSUE THREAD

**Issue by yingyingll** [PaddlePaddle/PARL#406]
您好，

请问一下examples中，a2c的   config中， 'get_remote_metrics_interval'和'log_metrics_interval_s'这两个参数一般怎么确定呢？ 还是一般不用改，取10就行呢？

谢谢

**Comment by TomorrowIsAnOtherDay** [comment]
这两个参数的用途如下：
`get_remote_metrics_interval`：表示间隔多久去获取这个actor的episode_reward
` log_metrics_interval_s`：表示每间隔多久输出一次指标到tensorboard
这两个参数可以根据需求自行更改，但是采用默认值10也是没问题的。

**Comment by yingyingll** [comment]
感谢回答， 还想问一下，如何更改actor 的log的存储路径呢？ 目前看到是 ~/.parl_data/job/下， 想自己指定一下存储路径，且希望仍然能在浏览器中访问到，在那个位置更改呢？

谢谢！

**Comment by TomorrowIsAnOtherDay** [comment]
目前该接口还没有对外开放的。如果有这块的需求，建议在actor里面直接open一个文件用于输出log的，但是这样会导致在浏览器无法访问到。
