### ISSUE TITLE
关于 mujoco_agent 中的  'CLIP' 部分

### ISSUE THREAD

**Issue by Ryan906k9** [PaddlePaddle/PARL#407]
PARL/examples/PPO/mujoco_agent.py /
这个文件的代码中只看到了 'KLPEN' 的部分，请问 'CLIP' 部分是在哪里实现的呢？
```
def policy_learn(self, obs, actions, advantages):
        """ Learn policy:
        1. Sync parameters of policy model to old policy model
        2. Fix old policy model, and learn policy model multi times
        3. if use KLPEN loss, Adjust kl loss coefficient: beta
        """
        self.alg.sync_old_policy()

        all_loss, all_kl = [], []
        for _ in range(self.policy_learn_times):
            loss, kl = self._batch_policy_learn(obs, actions, advantages)
            all_loss.append(loss)
            all_kl.append(kl)

        if self.loss_type == 'KLPEN':
            # Adative KL penalty coefficient
            if kl > self.kl_targ * 2:
                self.beta = 1.5 * self.beta
            elif kl < self.kl_targ / 2:
                self.beta = self.beta / 1.5

        return np.mean(all_loss), np.mean(all_kl)

```

**Comment by zenghsh3** [comment]
是在algorithm上会有区分，具体可以参考：
https://github.com/PaddlePaddle/PARL/blob/ef8ed9ac37a6513be9411b3a222c36eaedba097d/parl/algorithms/fluid/ppo.py#L110

**Comment by TomorrowIsAnOtherDay** [comment]
这部分我觉得适合放在algorithm 里面，但是目前静态图无法满足这个需求。
algorithm 目前只能用于静态图建图，没办法进行KLPEN这种动态参数更新。
后续动态图可以迁移一下：）

**Comment by Ryan906k9** [comment]
被静态图动态图彻底搞晕了

**Comment by Ryan906k9** [comment]
> 是在algorithm上会有区分，具体可以参考：
> https://github.com/PaddlePaddle/PARL/blob/ef8ed9ac37a6513be9411b3a222c36eaedba097d/parl/algorithms/fluid/ppo.py#L110

那在这个 example 中，是调用的哪个 policy_learn 函数呢？

**Comment by TomorrowIsAnOtherDay** [comment]
> 被静态图动态图彻底搞晕了

我们近期会逐步迁移到动态图的，敬请期待哈：）

**Comment by TomorrowIsAnOtherDay** [comment]
> > 是在algorithm上会有区分，具体可以参考：
> > https://github.com/PaddlePaddle/PARL/blob/ef8ed9ac37a6513be9411b3a222c36eaedba097d/parl/algorithms/fluid/ppo.py#L110
> 
> 那在这个 example 中，是调用的哪个 policy_learn 函数呢？

https://github.com/PaddlePaddle/PARL/blob/ef8ed9ac37a6513be9411b3a222c36eaedba097d/parl/algorithms/fluid/ppo.py#L120
可以看下这行的注释，这个参数决定使用哪种方式的

**Comment by Ryan906k9** [comment]
> > > 是在algorithm上会有区分，具体可以参考：
> > > https://github.com/PaddlePaddle/PARL/blob/ef8ed9ac37a6513be9411b3a222c36eaedba097d/parl/algorithms/fluid/ppo.py#L110
> > 
> > 
> > 那在这个 example 中，是调用的哪个 policy_learn 函数呢？
> 
> https://github.com/PaddlePaddle/PARL/blob/ef8ed9ac37a6513be9411b3a222c36eaedba097d/parl/algorithms/fluid/ppo.py#L120
> 
> 
> 可以看下这行的注释，这个参数决定使用哪种方式的

明白了，谢谢！
