### ISSUE TITLE
[TD3]agent couldn't use the save method

### ISSUE THREAD

**Issue by dennislx** [PaddlePaddle/PARL#410]
The example agent (PARL/examples/TD3/mujoco_agent.py) you give raises an attributeError when I try to save the trained model. Its parent class is trying to call `self.alg.learn_program` but `parl.algorithms.TD3` hasn't defined this attribute. How should I get around with it?

```
  File "C:\home\aistudio\work\rl\lessonM\train.py", line 63, in run_game
    agent.save(save_dir + "model_run_{}.ckpt".format(run+1))
  File "C:\Users\denni\Envs\imitate\lib\site-packages\parl\core\fluid\agent.py", line 154, in save  
    program = self.learn_program
AttributeError: 'Agent' object has no attribute 'learn_program'
```

Parl Version        1.3.2

**Comment by dennislx** [comment]
I have checked the base `Agent` class and found it has an argument `program` to allow me to specify which program to store but it appears I have to save two seperate learning program in this case.

**Comment by TomorrowIsAnOtherDay** [comment]
Sorry for the late response. Our team just went out for the team building:)
Ror actor-critic RL methods, we often have two models to save. This can be done by calling the function `save` twice.
Please refer to what we did in PPO: https://github.com/PaddlePaddle/PARL/issues/322#issuecomment-650884107

**Comment by TomorrowIsAnOtherDay** [comment]
Hi, @dennislblog, I have discussed with other developers. While this API can be applied to actor-critic methods, it does not seem natural and convenient.
We will update this API, in which both actor/critic-only and actor-critic methods can use the same API, despite the require for additional disk space.

**Comment by dennislx** [comment]
That would be great. Thanks and keep up your good work. You may close this issue now.
