### ISSUE TITLE
关于parl中MADDPG代码的一处疑问

### ISSUE THREAD

**Issue by zxm-NEU** [PaddlePaddle/PARL#411]
请问parl中的MADDPG算法，使用了论文中提到推理其他智能体的策略，减少通信，这个技巧了吗，在代码中没有看到这一部分的实现。critic网络的输入还是所有智能体的state和action。

**Comment by rical730** [comment]
你好，PARL的MADDPG代码参考了OpenAI的实现，OpenAI发布的代码也是直接使用别的agent的policy，并未使用论文中提到的这个技巧。

**Comment by zxm-NEU** [comment]
> 你好，PARL的MADDPG代码参考了OpenAI的实现，OpenAI发布的代码也是直接使用别的agent的policy，并未使用论文中提到的这个技巧。

哪想请问您一下，如果使用了这个技巧，是不是就相当于critic网络不需要输入其他智能体的action了吗？

**Comment by rical730** [comment]
还是要的，MADDPG本身的设计就是集中式训练，分布式执行，训练时是集中式地学习训练critic与actor，使用时actor只用知道局部信息就能运行。所以训练的时候critic是需要其他智能体的策略信息，你提到的这个论文中的技巧只是一种估计其他智能体策略的方法，就不用通过不断的通信来获取其他智能体的策略了。

**Comment by zxm-NEU** [comment]
> 还是要的，MADDPG本身的设计就是集中式训练，分布式执行，训练时是集中式地学习训练critic与actor，使用时actor只用知道局部信息就能运行。所以训练的时候critic是需要其他智能体的策略信息，你提到的这个论文中的技巧只是一种估计其他智能体策略的方法，就不用通过不断的通信来获取其他智能体的策略了

**Comment by zxm-NEU** [comment]
> > 还是要的，MADDPG本身的设计就是集中式训练，分布式执行，训练时是集中式地学习训练critic与actor，使用时actor只用知道局部信息就能运行。所以训练的时候critic是需要其他智能体的策略信息，你提到的这个论文中的技巧只是一种估计其他智能体策略的方法，就不用通过不断的通信来获取其他智能体的策略了

好的，是我理解有一些偏差了，谢谢您的回复。
