### ISSUE TITLE
关于MADDPG中智能体状态信息的疑问

### ISSUE THREAD

**Issue by zxm-NEU** [PaddlePaddle/PARL#412]
以simple_tag中三个捕食者，两个逃逸者为例，我尝试打print了这五个智能体的状态信息，得到了一个array，其中good_agents的状态为18，adversaries的状态信息为20，想请教一下，这些状态分别是什么呢，为什么还会不一致呢？
![image](https://user-images.githubusercontent.com/57446199/93308388-c7112980-f834-11ea-8903-744f63a736ed.png)

**Comment by TomorrowIsAnOtherDay** [comment]
这个信息我建议去OpenAI的官方仓库提问哈：）【狗头】
我们之前跑这个环境的时候没有刻意关注过这些状态信息，建议这块还是咨询环境的发布者。

**Comment by zxm-NEU** [comment]
> 这个信息我建议去OpenAI的官方仓库提问哈：）【狗头】
> 我们之前跑这个环境的时候没有刻意关注过这些状态信息，建议这块还是咨询环境的发布者。

**Comment by zxm-NEU** [comment]
> > 这个信息我建议去OpenAI的官方仓库提问哈：）【狗头】
> > 我们之前跑这个环境的时候没有刻意关注过这些状态信息，建议这块还是咨询环境的发布者。

想请问前辈，如果我想输出智能体的坐标信息，是否要从这入手？

**Comment by TomorrowIsAnOtherDay** [comment]
可以尝试下读下环境的源码，看下transition是如何运转的，以及对应的observation是怎么得到的。
我关闭这个issue了，因为它不是PARL仓库的问题。
