### ISSUE TITLE
3D环境搭建

### ISSUE THREAD

**Issue by zxm-NEU** [PaddlePaddle/PARL#413]
请问有尝试过将MPE环境扩展为3D的前辈吗？在core中有一个更改维度的变量，但是改成3D后会出现很多问题。
![image](https://user-images.githubusercontent.com/57446199/93429126-3a797080-f8f3-11ea-8976-c49dca78ee49.png)
![image](https://user-images.githubusercontent.com/57446199/93429191-57ae3f00-f8f3-11ea-8fd8-152aa9fdb211.png)

**Comment by TomorrowIsAnOtherDay** [comment]
Hi，@zxm-NEU，你这个core.py是PARL的吗？在我们的MADDPG example文件夹下面似乎没看到这个代码。
