### ISSUE TITLE
训练好的模型该如何去使用

### ISSUE THREAD

**Issue by gudufengzhongyipilang** [PaddlePaddle/PARL#417]
以MADDPG的demo为例，当完成训练时，会保留model和train_log，应该如何使用这个model？
在使用命令行：`python train.py --env [ENV_NAME] --show --restore`时，似乎会使用训练好的model，但是我不太确定。
如果代码中已经有如何使用模型的部分，可以展示一下吗？

**Comment by rical730** [comment]
有的，`train.py`代码中展示了如何加载model，只需要使用parl已经封装好的restore函数即可。
可以查看 https://github.com/PaddlePaddle/PARL/blob/develop/examples/MADDPG/train.py#L121

**Comment by gudufengzhongyipilang** [comment]
好的哈。那么比如我想通过`restore`去实现一个“模型再训练”的功能的话，是否利用`agent.restore()`函数和`agent.save()`函数就可以办到呢？
比如具体地，当训练进行一定程度时，我们需要修改reward的某参数然后继续训练，这时按以下思路：
1、首先保留A参数下训练的checkpoint；
2、修改A参数后，使用`agent.restore()`重新加载A参数的ckpt文件；
3、接着得到r、s、a然后继续送入`agent.learn()`进行训练；
4、通过`agent.save()`保存为ckpt文件；
循环执行以上过程。那么以上过程是否实现我想要的一个“模型再训练”呢？

**Comment by rical730** [comment]
可以的，只要Model不修改，就可以先保存参数到本地，修改其他与Model不相关的代码，再重新加载训练。

**Comment by gudufengzhongyipilang** [comment]
嗯嗯，也就是网络结构不能更改，不然与ckpt不匹配了。谢谢您哈，回复很快速~

**Comment by rical730** [comment]
对的，很高兴能够帮到你，那我先把这个issue关闭了哈~有任何与PARL使用相关的问题都可以随时提issue咨询哒。

**Comment by gudufengzhongyipilang** [comment]
好的
