### ISSUE TITLE
FileNotFoundError: cannot locate the remote file

### ISSUE THREAD

**Issue by Gaoee** [PaddlePaddle/PARL#420]
这里好像有个bug，我是在非源程序的目录下运行代码造成的：
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/exp/anaconda3/envs/××/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/exp/anaconda3/envs/××/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 176, in get_remote_gradient
    remote_actor = Actor(self.config)
  File "/home/exp/Codes/PARL/parl/remote/remote_decorator.py", line 285, in __init__
    *args, **kwargs)
  File "/home/exp/Codes/PARL/parl/remote/remote_decorator.py", line 134, in __init__
    file_path = locate_remote_file(module_path)
  File "/home/exp/Codes/PARL/parl/remote/utils.py", line 138, in locate_remote_file
    raise FileNotFoundError("cannot locate the remote file")
FileNotFoundError: cannot locate the remote file

**Comment by Gaoee** [comment]
之前的PARL版本是没有这个问题的，现在使用最新的代码就有这个问题了

**Comment by TomorrowIsAnOtherDay** [comment]
感谢反馈。
最新的代码确实是更改了这部分逻辑，你可以把涉及并行的这部分代码贴一下吗？我们一起定位下问题在哪里。

**Comment by Gaoee** [comment]
看我这边的代码可能作用不大。

应该是我运行程序的方式造成的，具体如下：
我在A目录下install我写好的算法了，这个算法是调用了parl的；
然后我想在B目录下调用我的算法，所以remote_actor = Actor(self.config)是在B目录下调用的，这样就出现上面的问题了；
但如果直接在A目录下调用remote_actor = Actor(self.config)，是不会出错的。

可能是PARL/parl/remote/utils.py中处理文件路径的代码没有考虑得很全面吧

**Comment by TomorrowIsAnOtherDay** [comment]
赞，你的分析是对的，应该是这个文件路径没处理对。
我们在持续继承测试里面应该包含了你上面说的这个情况，我先尝试在本地复现你说的情况看看。

**Comment by TomorrowIsAnOtherDay** [comment]
> A目录下install我写好的算法了

咨询下你这个install是什么含义呢？可以描述地更详细点吗？

不过我好像复现了这个问题，我的调用代码如下，我先fix这个问题。
```python
#!/usr/bin/env python
# coding=utf8
# File: test.py
import parl
import sys
sys.path.append('/home/yobobobo/Firework/PARL')
import Module2

parl.connect('localhost:8001')
b = Module2.B()
print(b.add_sum(10, 20))
```

**Comment by TomorrowIsAnOtherDay** [comment]
我刚和@zhs 讨论了下，这个问题在当前的逻辑下不好解决，预计需要把文件分发这块的逻辑给重新整理一遍（包含文件分发，远程机器目录设置等）。
**现阶段建议**更换成之前的版本（我们之前的版本是使用picklecloud进行文件分发，支持的类型兼容性差但是分发通用性强）或者把他们放到同一个目录下执行。
这个问题我们会在下个版本的更新中进行修正（预计会在11月发一个大版本，再次改善并行的体验）。
再次感谢你的反馈，祝好：）

**Comment by Gaoee** [comment]
> > A目录下install我写好的算法了
> 
> 咨询下你这个install是什么含义呢？可以描述地更详细点吗？
> 
> 不过我好像复现了这个问题，我的调用代码如下，我先fix这个问题。
> 
> ```python
> #!/usr/bin/env python
> # coding=utf8
> # File: test.py
> import parl
> import sys
> sys.path.append('/home/yobobobo/Firework/PARL')
> import Module2
> 
> parl.connect('localhost:8001')
> b = Module2.B()
> print(b.add_sum(10, 20))
> ```

嗯，跟你复现的做法差不多，就是用pip install -e .安装的。
请问回退到那个版本可以让pytorch并行的时候可以使用GPU，并且不会出现这个问题呢？

**Comment by TomorrowIsAnOtherDay** [comment]
1.3版本应该就是可以的，你先试试看哈，有问题我们继续讨论。
