### ISSUE TITLE
在本地怎么设置使用GPU呀  报错如下

### ISSUE THREAD

**Issue by minhoooo1** [PaddlePaddle/PARL#421]
CUDA_VISIBLE_DEVICES found gpu count: 1
[33m[10-01 23:26:05 MainThread @machine_info.py:105][0m [5m[33mWRN[0m Found non-empty CUDA_VISIBLE_DEVICES.                 But PARL found that Paddle was not complied with CUDA, which may cause issues.                 Thus PARL will not use GPU.

**Comment by TomorrowIsAnOtherDay** [comment]
```shell
export CUDA_VISIBLE_DEVICES=""
```
试试这个，
节日快乐：）
