### ISSUE TITLE
whats the diff between benchmark and examples

### ISSUE THREAD

**Issue by cww97** [PaddlePaddle/PARL#425]
in examples I see each one has a readme and seems reaches the accrucy in paper,

seems this is better, so what does 'benchmark's do= - =

**Comment by TomorrowIsAnOtherDay** [comment]
Hi, the 'benchmark' here is for our developers.  This folder provides the algorithm implemented in other neural network framework. It is a benchmark for us to implement the algorithm in PaddlePaddle, since some authors may release their code with torch implementation.
