### ISSUE TITLE
PARL何时能支持AlphaZero算法？

### ISSUE THREAD

**Issue by bxdxstu** [PaddlePaddle/PARL#426]

**Comment by TomorrowIsAnOtherDay** [comment]
Hi, bxdxstu.
感谢你的建议。
我们目前有个基于PARL并行的[简化版本](https://github.com/PaddlePaddle/PARL/tree/develop/benchmark/torch/AlphaZero)。
你可以先参考这个，至于围棋版本的AlphaZero，目前还没有计划。
