### ISSUE TITLE
When can PARL be installed on Jetson TX2/NX ?

### ISSUE THREAD

**Issue by Wongziseoi** [PaddlePaddle/PARL#427]
Please make a tutorial about how to install PARL on Jetson device. It seems that pyarrow can not be installed in ARMv8 device.

**Comment by TomorrowIsAnOtherDay** [comment]
Hi, Wongziseoi. Thanks for pointing out the pyarrow issue.
We haven't yet tested PARL in TX2/NX platform, since we do not have such devices on hand.
Regarding the pyarrow, we are going to remove the dependency on pyarrow in the future. (Hopefully, it will be released in the end of this year).

**Comment by zenghsh3** [comment]
The latest version of PARL has removed the dependency on pyarrow. And we also installed the latest version of PARL in Jetson Xavier NX directly.
