### ISSUE TITLE
There is a little different between release-1.3.2 and the version on website in the loggler.py file.

### ISSUE THREAD

**Issue by YeFeiyangx** [PaddlePaddle/PARL#428]
173 ->     if hasattr(mod, '__file__'):
174 ->             basename = os.path.basename(mod.__file__)
175 ->     else:
176 ->             basename = ''

The missing of row 173 make a error when using NoteBook in AIStudio to save the log which is beneficial to using VisualDL.

**Comment by TomorrowIsAnOtherDay** [comment]
Hi, YeFeiyangx. Thanks for your feedback.
Do you mean that the PARL on the github cannot run normally in AIStudio?
