### ISSUE TITLE
PARL现在可以在paddle2.0rc上运行么？

### ISSUE THREAD

**Issue by EastSmith** [PaddlePaddle/PARL#431]
现在飞桨出了paddle2.0rc版本，尝试在paddlepaddle-gpu  （2.0.0rc0.post101）使用使用parl1.31版本
`import parl`直接报错：
`---------------------------------------------------------------------------ValueError                                Traceback (most recent call last)<ipython-input-4-9cabb425d7ff> in <module>
----> 1 import parl
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/parl/__init__.py in <module>
     20 
     21 from tensorboardX import SummaryWriter
---> 22 from parl.utils.utils import _HAS_FLUID, _HAS_TORCH
     23 
     24 if _HAS_FLUID:
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/parl/utils/__init__.py in <module>
     14 
     15 from parl.utils.exceptions import *
---> 16 from parl.utils.utils import *
     17 from parl.utils.csv_logger import *
     18 from parl.utils.machine_info import *
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/parl/utils/utils.py in <module>
     89 try:
     90     from paddle import fluid
---> 91     fluid_version = get_fluid_version()
     92     assert fluid_version >= 161 or fluid_version == 0, "PARL requires paddle>=1.6.1"
     93     _HAS_FLUID = True
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/parl/utils/utils.py in get_fluid_version()
     81 def get_fluid_version():
     82     import paddle
---> 83     fluid_version = int(paddle.__version__.replace('.', ''))
     84     return fluid_version
     85 
ValueError: invalid literal for int() with base 10: '200-rc0'`

**Comment by TomorrowIsAnOtherDay** [comment]
感谢对于PARL的关注：）
目前还没开始支持这个release candidate版本，我们预计会在12月完成动态图版本的支持。
