### ISSUE TITLE
请问如何在单个服务上使用多张显卡多CPU？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/PARL#435]
我有一台双卡的服务器，我在训练DQN，但是资源使用率很低，只是使用了单卡和单个CPU核心，如何提高使用率呢？

**Comment by TomorrowIsAnOtherDay** [comment]
这个不是通过使用多张显卡就能提升效率的，建议尝试下我们的A2C，可以使用多个CPU核心并发。

**Comment by yeyupiaoling** [comment]
@TomorrowIsAnOtherDay DQN可以使用多个CPU核心并发吗？

**Comment by TomorrowIsAnOtherDay** [comment]
DQN是可以改成多核心并发的，但是我们没有提供这样的示范。

**Comment by yeyupiaoling** [comment]
@TomorrowIsAnOtherDay 能提供一下简单示例吗？

**Comment by TomorrowIsAnOtherDay** [comment]
这个实现并不简单哈，对初学者不大友好，还是建议使用A2C。

**Comment by yeyupiaoling** [comment]
![3N81W X}}6)( CRV3RXDL0](https://user-images.githubusercontent.com/26297768/99047365-1377ac00-25cf-11eb-82a6-ec6027dfb116.jpg)
