### ISSUE TITLE
安装了parl的python环境，在paddle 2.0rc版本下import会导致出错

### ISSUE THREAD

**Issue by jiangjiajun** [PaddlePaddle/PARL#436]
![image](https://user-images.githubusercontent.com/19339784/98338711-90da7400-2045-11eb-9c86-600a61c5897a.png)

**Comment by TomorrowIsAnOtherDay** [comment]
感谢反馈，我们现在修复下。

**Comment by TomorrowIsAnOtherDay** [comment]
fixed in #437
