### ISSUE TITLE
A2C什么时候有?

### ISSUE THREAD

**Issue by kosoraYintai** [PaddlePaddle/PARL#44]
百度的各位大大们，A2C算法框架什么时候能出？

**Comment by TomorrowIsAnOtherDay** [comment]
嗯，我们有计划逐步follow 主流算法的，包括不仅限于A2C/A3C/IMPALA等。
同时也会考虑一些有意义的RL子领域算法比如multi-agent, hierarchical RL, meta-learning, model-based 等。
请紧密关注我们后续的工作呢。

**Comment by kosoraYintai** [comment]
Nice，目前无论Git还是国内博客，代码风格严重不统一，而且存在超参数难调、收敛性不保证、Env无法复用等一系列问题；昨天用PG框架试验Pendulum和MountainCar，都成功了。真心期待PARL在强化学习领域能“千秋万载一统江湖” ^_^

**Comment by TomorrowIsAnOtherDay** [comment]
@kosoraYintai 
我们的A2C已经实现好啦，性能应该是我们所知道的开源框架里面最好的 -----
5个worker在2个小时就可以在breakout上达到400分了。
#62

**Comment by kosoraYintai** [comment]
好的，回头我试一下。另外，PARL版Flappy-Bird已经出炼丹炉，欢迎访问 O(∩_∩)O：https://aistudio.baidu.com/aistudio/#/projectdetail/51092

https://github.com/kosoraYintai/PARL-Sample/tree/master/flappy_bird

**Comment by TomorrowIsAnOtherDay** [comment]
哇，好赞
