### ISSUE TITLE
1.3版本的Bug

### ISSUE THREAD

**Issue by yueyue-yue** [PaddlePaddle/PARL#442]
example跑不出來！太難受了！！！
    batch = batch.batch
NameError: name 'batch' is not defined

    from parl import layers
ImportError: cannot import name 'layers' from 'parl'

**Comment by TomorrowIsAnOtherDay** [comment]
今天周末，回复会有点晚：）
你的paddle版本以及parl版本请输出一下，通过pip list可以看到

**Comment by yueyue-yue** [comment]
parl 1.3.2, paddlepaddle 1.8.5 , 現在用的內置的一個沒有import layer的DDPG例子挺好，但是只要有import layer的都整不成。（沒想到周末還會有人回復·····牛&感謝）

**Comment by TomorrowIsAnOtherDay** [comment]
感谢反馈，建议安装paddle 1.6XX版本的，估计就可以使用了。
你遇到的问题应该是最新版本的paddle更新了API与之前的用法不兼容。
我们会在周一修复这个问题，这两天建议安装旧版本的paddle:
```shell
pip install paddlepaddle==1.6.1
```

**Comment by yueyue-yue** [comment]
😭😭😭感谢！！！！！！！
________________________________
发件人: Bo Zhou <notifications@github.com>
发送时间: 2020年11月14日 18:57
收件人: PaddlePaddle/PARL <PARL@noreply.github.com>
抄送: Yue Zenglin <e0575902@u.nus.edu>; State change <state_change@noreply.github.com>
主题: Re: [PaddlePaddle/PARL] 1.3版本的Bug (#442)

        - External Email -



感谢反馈，建议安装paddle 1.6XX版本的，估计就可以使用了。
你的问题应该是最新版本的paddle更新了API与之前的用法不兼容。
我们会在周一修复这个问题，这两天建议安装旧版本的paddle:

pip install paddlepaddle==1.6.1

**Comment by TomorrowIsAnOtherDay** [comment]
hello，今天周一了：）
请提供下你的系统版本，我在Ubuntu 1604上面无法复现你提到的问题，比如我跑quickstart是可以跑的。

**Comment by TomorrowIsAnOtherDay** [comment]
我的复现环境是：
Ubuntu 1604
paddlepaddle        1.8.5  
parl 1.3.2 (pip install parl ==1.3.2)

**Comment by TomorrowIsAnOtherDay** [comment]
我们的软件发版本都是有经过测试的哈，在teamcity上面会跑所有的测试服务，我们目前覆盖到了ubuntu系列的2.7/3.6/3.7 python版本

**Comment by yueyue-yue** [comment]
你好，
我也不知爲何，前兩天突然可以用了，我以爲你們突然熬夜修復了😳,
這是我的環境截圖，[cid:62a51c5e-4329-4435-ad9a-98b63940305c]


可能是因爲github的包有問題，我好像重新下載了幾遍paddlepaddle，最後一次是pycharm默認的'install package'(下面這張圖裏的install package)

[cid:37a7618d-4e8c-48be-9326-55bb616d9e3d]





此外在一些論壇上好像也有人出現這個問題：https://www.bilibili.com/video/BV1yv411i7xd
[http://i1.hdslb.com/bfs/archive/16886b754103548a572d47bcb0203170a9185228.jpg]<https://www.bilibili.com/video/BV1yv411i7xd>
世界冠军带你从零实践强化学习_哔哩哔哩 (゜-゜)つロ 干杯~-bilibili<https://www.bilibili.com/video/BV1yv411i7xd>
百度NeurIPS全球顶会冠军团队亲自授课，5大核心算法讲解+5次实战，带你从零实践强化学习！课程平台链接：https://aistudio.baidu.com/aistudio/course/introduce/1335 【主讲老师】科老师：飞桨强化学习PARL团队核心成员，百度高级研发工程师。所在团队曾两度夺得NeurIPS强化学习赛事冠军，并获得百度最高奖等荣誉。
www.bilibili.com
[cid:31eb5356-c092-43b5-b342-eb757fbd1865]
祝好！

________________________________
发件人: Bo Zhou <notifications@github.com>
发送时间: 2020年11月16日 10:46
收件人: PaddlePaddle/PARL <PARL@noreply.github.com>
抄送: Yue Zenglin <e0575902@u.nus.edu>; State change <state_change@noreply.github.com>
主题: Re: [PaddlePaddle/PARL] 1.3版本的Bug (#442)

        - External Email -



我们的软件发版本都是有经过测试的哈，在teamcity上面会跑所有的测试服务，我们目前覆盖到了ubuntu系列的2.7/3.6/3.7 python版本

**Comment by yueyue-yue** [comment]
系y版本是ubuntu20.04，python3.8
________________________________
发件人: Bo Zhou <notifications@github.com>
发送时间: 2020年11月16日 10:42
收件人: PaddlePaddle/PARL <PARL@noreply.github.com>
抄送: Yue Zenglin <e0575902@u.nus.edu>; State change <state_change@noreply.github.com>
主题: Re: [PaddlePaddle/PARL] 1.3版本的Bug (#442)

        - External Email -



hello，今天周一了：）
请提供下你的系统版本，我在Ubuntu 1604上面无法复现你提到的问题，比如我跑quickstart是可以跑的。

―

**Comment by TomorrowIsAnOtherDay** [comment]
> 你好， 我也不知爲何，前兩天突然可以用了，我以爲你們突然熬夜修復了😳,

我们没有熬夜修复哈哈哈，我估计是环境同时存在两个版本的paddle问题，下次如果有类似问题，建议使用anaconda 创建一个新环境试试看能否跑起来，如果可以跑起来的话应该就是旧环境的问题。我先关闭issue啦，等可以稳定复现这个问题的时候才能定位并修复问题。

再次感谢你的反馈：）

**Comment by TomorrowIsAnOtherDay** [comment]
hello，我们最近在本地复现了类似的问题，定位到是paddle的安装问题。
我们在parl里面已经新增了深度学习框架安装的提示。再次感谢：）
