### ISSUE TITLE
DDPG如何输出1,2,3,4这样的动作

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/PARL#445]
这里输出的是一个-1到1的连续结果，希望是输出1 或者2 或者3 或者4 或者5 

https://github.com/PaddlePaddle/PARL/blob/c9be73a87b6618e5a3b2c945327478f365caab74/examples/DDPG/train.py#L42-L47

**Comment by TomorrowIsAnOtherDay** [comment]
你可以把输出从【-1，1】映射到【1，5】的区间，然后对结果取整，就可以得到你想要的了。

**Comment by yeyupiaoling** [comment]
@TomorrowIsAnOtherDay 好的，谢谢。我试试。高斯分布是一定要的吗？

**Comment by TomorrowIsAnOtherDay** [comment]
要的，用来做sampling。话说记得star关注下我们的后续发版：）

**Comment by yeyupiaoling** [comment]
@yeyupiaoling 好的。   star啦~
