### ISSUE TITLE
PPO的模型学习率我可以写一个固定值吗？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/PARL#448]
我看这个学习率都在通过obs_dim计算的，我可以自己给一个其他值吗？因为输入的是图片，obs_dim是（1， 112， 122）这样的，安装它这个计算不行吧？

https://github.com/PaddlePaddle/PARL/blob/ddc414e824cf1fa94aef9215196ebfff9b1781b3/examples/PPO/mujoco_model.py#L43-L47

**Comment by TomorrowIsAnOtherDay** [comment]
这个learning rate是可以改的。自信点，先试试再说：）

**Comment by yeyupiaoling** [comment]
@TomorrowIsAnOtherDay 谢谢，看到你这样说我就放心了。
