### ISSUE TITLE
关于Policy Gradient训练

### ISSUE THREAD

**Issue by Steven0HH** [PaddlePaddle/PARL#449]
目前正在学习用PARL搭建一个关于MsPacman-v0的atari强化学习项目，model采用了三层卷积层+两层全连接层，将游戏界面的Image裁剪后作为输入，采用的是PARL的PG算法，但是遇到了模型不收敛的问题。想请问可以从哪些方面去排查问题或者调参呢？有什么相关建议吗？谢谢。

![cost](https://user-images.githubusercontent.com/74641210/99516769-8a46e780-29c9-11eb-9d94-3228dfeb65f2.png)
![reward](https://user-images.githubusercontent.com/74641210/99516774-8c10ab00-29c9-11eb-8bbc-9b5df1c854f9.png)

**Comment by TomorrowIsAnOtherDay** [comment]
如果之前没有调试太多强化学习算法经验的话，我建议你先切换成DQN算法试试看，因为它在Atari这类游戏上面的表现效果很好，也相对容易调试。

**Comment by Steven0HH** [comment]
好的谢谢
