### ISSUE TITLE
pip install 报错

### ISSUE THREAD

**Issue by W-yk** [PaddlePaddle/PARL#45]
按照quickstart的说明进入目录运行pip install . 时出现如下错误，不知道如何解决。。
![image](https://user-images.githubusercontent.com/32806173/51437509-42c27800-1cda-11e9-87ef-848ef3039cf5.png)

**Comment by TomorrowIsAnOtherDay** [comment]
这个命令行交互界面看着像是windows 系统的呢，麻烦描述下目前使用的操作系统，方便定位问题：）
我们在发版本之前， 在mac 以及一般linux 机器（ubuntu/centos）上测试验证过了，但没在windows机器上测试过。另外不建议用Windows系统呢，原因是底层的paddle 计算框架不支持。

**Comment by W-yk** [comment]
谢谢回复 ，是在windows系统，我换成osx和linux服务器试了下都安装成功了，， 祝好

**Comment by TomorrowIsAnOtherDay** [comment]
：）

**Comment by kosoraYintai** [comment]
windows可以直接copy整个项目源码，亲测可使用
