### ISSUE TITLE
请问PPO算法图像作为输入数据，如何添加时间步长特征？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/PARL#451]
PPO算法图像作为输入数据，如何添加时间步长特征 和 图像的比例。我的输入图像的shape为(1, 112, 112)。时间步长 和 scale observations 都是必须的吗？

https://github.com/PaddlePaddle/PARL/blob/ddc414e824cf1fa94aef9215196ebfff9b1781b3/examples/PPO/train.py#L35-L37

**Comment by TomorrowIsAnOtherDay** [comment]
如果需要更改输入，你只需要更改model、agent这部分，PPO algorithm 可以直接复用。

**Comment by yeyupiaoling** [comment]
@TomorrowIsAnOtherDay obs的shape和这`[[step]]`都不一样

**Comment by TomorrowIsAnOtherDay** [comment]
你可以把图像经过多层卷积之后，得到一个vector表示，再concat 这个step就好了。

**Comment by yeyupiaoling** [comment]
@TomorrowIsAnOtherDay 假设卷积之后的shape为（-1， 63， 18， 18），要使用flatten() 将它展开，还是用fc 将它变成（-1， size）？

**Comment by TomorrowIsAnOtherDay** [comment]
使用flatten展开之后就可，fc可加可不加。

**Comment by yeyupiaoling** [comment]
好的，之后试试
