### ISSUE TITLE
使用DDPG训练飞翔的小鸟，模型只会输出一个动作，这是什么原因？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/PARL#453]
这个是我基于DDPG模型写的代码，包括了游戏的环境，只需要安装pygame就可以运行，麻烦帮我看看是那里出了问题，随着训练，模型输出的结果不是只会往上飞， 就是玩下飞。 
[temp2.zip](https://github.com/PaddlePaddle/PARL/files/5565154/temp2.zip)

其中在训练时对输出的结果这样处理，正常的动作不是0就是1，我通过这样方式取整可以的吗，有没有错？
```python
        # 预测动作
        action = agent.predict(obs.astype('float32'))

        # 利用高斯分布添加噪声
        action = np.clip(np.random.normal(action, 1.0), -1.0, 1.0)
        # 获取动作，把结果固定输出在(-1, 1)，取整就得到了动作
        action = int(action_mapping(action, -1.0, 1.0) + 1 - 1e-4)

        # 把动作标签转换为实际的游戏动作
        next_obs, reward, terminal = env.step(action)
        next_obs = preprocess(next_obs, render)
```

**Comment by TomorrowIsAnOtherDay** [comment]
这个issue 与PARL使用无关，我关闭了。

**Comment by yeyupiaoling** [comment]
@TomorrowIsAnOtherDay 有关呐，这不是使用问题？

**Comment by yeyupiaoling** [comment]
@TomorrowIsAnOtherDay 这就是用PARL训练时输出的action，但是例子中的是一个连续的浮点数组，我的是0或者1的数组，我想问处理方式是否正确。

**Comment by btobab** [comment]
老兄怎么老看见你~==~
建议看一下 #525 中我的回复

**Comment by btobab** [comment]
@yeyupiaoling
