### ISSUE TITLE
动态图版本什么时候出呀？

### ISSUE THREAD

**Issue by universea** [PaddlePaddle/PARL#456]
请问动态图版本什么时候出呀？

**Comment by TomorrowIsAnOtherDay** [comment]
Hello，感谢对于PARL的关注。
我们预计会在12月中旬发布动态图预览版，并提供部分算法示例。

**Comment by universea** [comment]
> Hello，感谢对于PARL的关注。

Hi, thank you so much !

**Comment by btobab** [comment]
@TomorrowIsAnOtherDay 可以自己使用动态图实现某些用静态图编写的类吗？然后引入parl的algrithm运行。

**Comment by TomorrowIsAnOtherDay** [comment]
不行的，目前静态图和动态图还是相对割裂，比较初步的状态，尽管飞桨的最终目标是动静结合。
请期待我们的动态图版本。

**Comment by btobab** [comment]
好的，非常期待。

**Comment by humbert2018** [comment]
Paddle 2.0 RC1发布了。催下PARL哦~

**Comment by universea** [comment]
动态图的模型是还没更新完成吗~

**Comment by humbert2018** [comment]
1.3还是静态图。新版本还没有出



----------------------

孙浩  清华大学车辆运载学院 iDLab 课题组

SUN Hao Ph.D. iDLab, School of Vehicle and Mobility, Tsinghua University, Beijing

Tel & WeChat：18810661722

在2020年12月21日 20:53，universea<notifications@github.com> 写道：

动态图的模型是还没更新完成吗~

**Comment by TomorrowIsAnOtherDay** [comment]
正式版本终于发布啦～前段时间我们虽然提供了动态图的example，但是由于数量还不够多，等着到年中才正式发布。
再次感谢大家对于PARL的关注！
