### ISSUE TITLE
examples中NeurIPS2019的可视化

### ISSUE THREAD

**Issue by mycode2021** [PaddlePaddle/PARL#458]
您好，NeurIPS2019-Learn-to-Move-Challenge项目中，final_submit下的test.py如何在运行期间调用可视化窗口？类似gym的env.render()。我查看了osim-rl里面osim.py的OsimEnv类虽然定义了render方法但是内容为空，导致调用env.render()无任何输出，或者有其它方法可以实现可视化？

**Comment by zenghsh3** [comment]
执行下面命令即可：
```
python test.py --vis
```

**Comment by mycode2021** [comment]
> 执行下面命令即可:
> 
> ```
> python test.py --vis
> ```

谢谢
