### ISSUE TITLE
DDPG的预测结果只会偏向一个值

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/PARL#462]
我这里使用PARL写了一个使用DDPG训练飞翔的小鸟，随着训练，结果只会偏向一个动作。
https://github.com/yeyupiaoling/FlappyBird_DDPG

**Comment by TomorrowIsAnOtherDay** [comment]
可能的原因有以下几个：
1）模型代码有bug
2）模型不够复杂，难以表征当前图像
3）超参数不对，比如学习率太大了，导致模型直接学崩了

**Comment by yeyupiaoling** [comment]
@TomorrowIsAnOtherDay 
1. 模型代码应该没有问题，我没有换游戏环境之后也能正常训练
2. 特征应该能正常提取，因为我使用DQN训练非常正常，可以得到很高分：https://github.com/yeyupiaoling/ReinforcementLearning/tree/main/course2
3. 我试试更小的超参数

**Comment by btobab** [comment]
建议看一下我在 #525 中的回复

**Comment by btobab** [comment]
@yeyupiaoling
