### ISSUE TITLE
override fluid.program_guard for parl.Agent

### ISSUE THREAD

**Issue by YuechengLiu** [PaddlePaddle/PARL#463]
In this case, only agent2 could load its parameters successfully. 
```python
agent1 = Agent()
agent1.restore('model1.ckpt')
agent2 = Agent()
agent2.restore('model2.ckpt')
```
and now it is able to load parameters successfully for both agents in the following manner,
```python
agent1 = Agent()
agent2 = Agent()
agent1.restore('model1.ckpt')
agent2.restore('model2.ckpt')
```
### Problem
- The problem is caused by the `default_startup_program` in `parl.Agent`

**Comment by TomorrowIsAnOtherDay** [comment]
It seems to be a problem of repeatedly creating the same computation graph.
This problem will not be an issue if we use the eager mode.
Since we are supporting the eager mode, I think we can ignore this issue now.

**Comment by TomorrowIsAnOtherDay** [comment]
I'm going to close the issue since PARL supports eager mode by default.
