### ISSUE TITLE
DQN的算法实现问题

### ISSUE THREAD

**Issue by btobab** [PaddlePaddle/PARL#470]
DQN的algrithm部分的learn函数，为什么要使用按元素乘的方法实现？是为了更高的效率吗？可是使用index的话，时间复杂度是o(1),应该更快丫

**Comment by btobab** [comment]
![Screenshot from 2020-12-05 16-01-24](https://user-images.githubusercontent.com/66876429/101237659-934bee80-3715-11eb-872a-97618ee552ed.png)

**Comment by TomorrowIsAnOtherDay** [comment]
好久没看到这种性能方面的讨论了，点个赞。
这个主要是考虑到gradient 回传的问题，通过这种方式我们的计算可以表达成数学公式，这样可以直接求导。

**Comment by btobab** [comment]
这种设计太精妙了。

**Comment by TomorrowIsAnOtherDay** [comment]
我先关闭issue了：）欢迎再讨论
