### ISSUE TITLE
运行时报错张量维度问题

### ISSUE THREAD

**Issue by btobab** [PaddlePaddle/PARL#474]
https://paste.ubuntu.com/p/79GNKCVB3Y/

**Comment by btobab** [comment]
与AiStudio上的代码对照了一下午，实在是找不出问题在哪

**Comment by YuechengLiu** [comment]
应该是没有手动调用parl.Agent的__init__，导致graph没有初始化。在`class Agent`的`__init__()`首行添加`super(Agent, self)__init__()`

**Comment by btobab** [comment]
@liuyuecheng-github  
![Screenshot from 2020-12-07 16-17-08](https://user-images.githubusercontent.com/66876429/101326362-1bfa9400-38a8-11eb-8e60-1cabc75c71cf.png)
我在后面调用了super函数

**Comment by btobab** [comment]
![Screenshot from 2020-12-07 16-17-30](https://user-images.githubusercontent.com/66876429/101326464-43e9f780-38a8-11eb-82bc-0bff6b6179c7.png)
![Screenshot from 2020-12-07 16-17-45](https://user-images.githubusercontent.com/66876429/101326466-451b2480-38a8-11eb-90da-5af3a8069cdf.png)
然后如果放在第一行的话，会报错。因为经过调试我发现在调用super时会调用build_program()函数
![Screenshot from 2020-12-07 16-24-54](https://user-images.githubusercontent.com/66876429/101326981-0043bd80-38a9-11eb-8ebb-8baf0efdcb2b.png)
而build_program()函数会用到self.obs_dim这个变量，这个变量是在__init__函数中的super()函数之后赋值的。
![Screenshot from 2020-12-07 16-25-22](https://user-images.githubusercontent.com/66876429/101327159-44cf5900-38a9-11eb-8a0b-94cf6d84b58f.png)

**Comment by YuechengLiu** [comment]
维度不一致在哪里出现的呢？有相关报错信息吗？

**Comment by btobab** [comment]
调试发现在这里出现:
![Screenshot from 2020-12-07 18-46-01](https://user-images.githubusercontent.com/66876429/101342083-02b01280-38bd-11eb-9a53-91f97caf661f.png)
报错:
![Screenshot from 2020-12-07 18-44-59](https://user-images.githubusercontent.com/66876429/101342108-10659800-38bd-11eb-8a25-0608b4d52c56.png)
代码在第一条comment，您也可以自己跑一下。

**Comment by YuechengLiu** [comment]
将line77的`fluid.data`替换为`layers.data`，问题就可以解决。parl对原始fluid的部分模块进行了重新封装。

**Comment by TomorrowIsAnOtherDay** [comment]
刚我们讨论了下，parl里面封装的是`fluid.layers.data`，新增的`fluid.data` 这个方法与 `fluid.layers.data`不同。
建议使用@liuyuecheng-github 的解决方案哈

**Comment by btobab** [comment]
好的，谢谢大佬们
