### ISSUE TITLE
在Ubuntu保存的模型在windows不能直接加载

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/PARL#477]
我保存的方式如下
```
agent.save(args.model_path)
```
这是保存的模型：
![image](https://user-images.githubusercontent.com/26297768/101425892-e2bd3500-3936-11eb-8c49-2bf89f13cf07.png)

但是在windows 加载的时候就报错了
```
UnavailableError: LoadCombine operator fails to open file .\model.ckpt/, please check whether the model file is complete or damaged.
  [Hint: Expected static_cast<bool>(fin) == true, but received static_cast<bool>(fin):0 != true:1.] at (D:/1.8.2/paddle\paddle/fluid/operators/load_combine_op.h:50)
  [operator < load_combine > error]
```

而我在windows上训练保存的模型格式是这样的：
![image](https://user-images.githubusercontent.com/26297768/101426152-6545f480-3937-11eb-9658-524a243dc13f.png)

**Comment by TomorrowIsAnOtherDay** [comment]
我们在#416 升级了模型的保存以及存储方式，这样可以更好地保存PPO这些actor-critic 模型。
从文件类型来看，你的Windows版本不是安装的最新版本。

**Comment by yeyupiaoling** [comment]
@TomorrowIsAnOtherDay 的确，是我windows的版本太低了，我之前有源码安装，以为安装成功了。我用这个`python setup.py install` 安装的
```
  Found existing installation: parl 1.3.1
    Uninstalling parl-1.3.1:
      Successfully uninstalled parl-1.3.1
Successfully installed parl-1.3.3 pyarrow-0.17.1
```

用`pip install .`这个命令安装失败：
```
...............
amples\\Prioritized_DQN\\utils.py', 'symbolic link privilege not held')]
```

**Comment by TomorrowIsAnOtherDay** [comment]
pip install 不会安装examples里面的代码，请截图看下具体的错误提示。
另外，最新版本的源码应该不依赖pyarrow了，请确认你的源码是最新版本。

**Comment by yeyupiaoling** [comment]
![image](https://user-images.githubusercontent.com/26297768/101432731-5a459100-3944-11eb-8a86-f71752794646.png)

**Comment by yeyupiaoling** [comment]
我试试重新拉取源码吧，我刚才试过强制覆盖本地也不行
```
git fetch --all && git reset --hard origin/master && git pull
```

**Comment by zenghsh3** [comment]
symbolic link privilege not held问题可以看下下面建议是否可行：
https://github.com/explosion/spaCy/issues/895#issuecomment-289198926
https://github.com/explosion/spaCy/issues/895#issuecomment-309054937

**Comment by TomorrowIsAnOtherDay** [comment]
另外，建议在Windows下使用conda来安装。

**Comment by yeyupiaoling** [comment]
@zenghsh3 谢谢，我删掉了之前的源码，正在重新拉取，如果不行，那就按照你的方式解决

**Comment by yeyupiaoling** [comment]
我使用管理员的身份打开powershell，这样安装成功了。
