### ISSUE TITLE
关于clip与gaussian噪声的疑问

### ISSUE THREAD

**Issue by kosoraYintai** [PaddlePaddle/PARL#48]
看了一下DDPG与PPO例子，有两个细节不太清楚。

1、无论是DDPG还是PPO，都采取了"train阶段加clip和action_mapping，而test阶段只加action_mapping"的方式，代码如下所示：
```
        #train
        action = agent.policy_sample(obs)
        action = np.clip(action, -1.0, 1.0)
        action = action_mapping(action, env.action_space.low[0],
                                env.action_space.high[0])

       #test
        action = agent.policy_predict(obs)
        action = action_mapping(action, env.action_space.low[0],
                                env.action_space.high[0])
```
由于agent和model层并未进行action的clip，这样能保证test阶段action的预测值在(-1.0,1.0)之间吗？如果不能保证，直接action_mapping会不会有偏差？

2、DDPG与PPO加高斯噪声的时机不一样。
DDPG在模型之外加的噪声:
```
        # Add exploration noise, and clip to [-1.0, 1.0]
        action = np.clip(np.random.normal(action, 1.0), -1.0, 1.0)
        action = action_mapping(action, env.action_space.low[0],
                                env.action_space.high[0])
```
PPO在模型内部加的噪声:

```
    def sample(self, obs):
        means, logvars = self.policy(obs)
        sampled_act = means + (             
            layers.exp(logvars / 2.0) *  # stddev
            layers.gaussian_random(shape=(self.act_dim, ), dtype='float32'))
        return sampled_act
```
这两种不同的策略是微调出来的经验，还是都可以使用？另外，直接在model层对于action进行fluid.clip(action,low,high)的方式是不是也可以？

**Comment by zenghsh3** [comment]
1. DDPG和PPO的策略模型（policy/actor）的最后一层全连接网络（fc）的激活函数都是tanh，这个是会保证输出范围在(-1, 1)；所以在测试阶段不用做clip。

2. DDPG和PPO加噪声的方式不一样，这是跟算法相关的，DDPG只是通过action加噪声来进行探索；而PPO算法需要用到policy的mean和vars（方差）来进行action的概率、KL值计算，因此需要在模型层对policy的方差进行建模，所以我们就直接在model层根据方差进行sample。

3. 采样时也可以在model层做clip的。

**Comment by TomorrowIsAnOtherDay** [comment]
上面的回答偏实现细节，我补充回答下这个问题：
> 2、DDPG与PPO加高斯噪声的时机不一样

本质上，这两者都是添加的高斯噪声，这两种方式的区别是是否对噪声的大小建模。  
这么做的主要原因是PPO 是个on-policy 的算法，on-policy 算法学习的过程中learning-policy 是趋向于 behaviour-policy 的。为了让模型逐步收敛，我们需要保证behaviour-policy 产生的样本里包含的噪声要逐步减小，所以我们把对高斯噪声的方差建模，让噪声大小在收敛过程中逐步下降。  
至于DDPG，它是个off-policy 算法，收敛效果从理论上看不受噪声的大小的影响，所以不对噪声建模，直接添加在action上了。

**Comment by kosoraYintai** [comment]
哦，layers.exp(logvars / 2.0) *XXX，噪声的自动衰减就体现在这里吧？

**Comment by TomorrowIsAnOtherDay** [comment]
主要体现在优化policy网络的时候，梯度会回传到方差上面。
https://github.com/PaddlePaddle/PARL/blob/6fdf4448d820e6f1b7fd194ae9664cf27206dc0a/parl/algorithms/ppo.py#L56
从这行代码上看，训练policy模型的过程中，为了最小化loss，网络会更新policy部分的参数并且减少方差。

**Comment by TomorrowIsAnOtherDay** [comment]
十分感谢提出的疑惑，这部分确实看着不直观，我们后续会update 文档说明这个做法的原因：）
有时候为了复现论文级别的指标我们会引用一些paper里面没有提到的trick，比如会用huber_loss 代替传统的square_loss 来拟合Q function，但是核心的算法还是严格参照paper来的。

**Comment by kosoraYintai** [comment]
谢谢大佬们的指导

**Comment by TomorrowIsAnOtherDay** [comment]
谢谢支持。
另外我们已经收到了你在公众号上面的评论，上面提到将 PARL 应用到**flappy bird** 这个benchmark的收敛速度问题，这个我们已经找到paddle底层的同学和我们一起定位问题。由于临近年关，大家都陆续休假了，这个性能问题会放在春节后高优先级去定位以及解决。
再次感谢你的使用反馈，新年快乐。

**Comment by kosoraYintai** [comment]
新年快乐！

**Comment by TomorrowIsAnOtherDay** [comment]
@kosoraYintai 抱歉回复晚了，近期我们和paddlepaddle的同学定位了CNN的性能差距问题，目前给出的建议（这个方案用起来确实挺麻烦的，paddle的同学反馈是在1.4版本修复这个问题）是：

采用ParallelExecutor 而不是传统的Executor，具体配置参照下方的代码示例。

至于PARL框架层面的优化，我们希望是在等后续paddle 合并ParallelExecutor与Executor 之后再进行，现阶段这个优化写法实在是太丑了。

**Comment by TomorrowIsAnOtherDay** [comment]
```python
    exec_strategy = fluid.ExecutionStrategy()
    exec_strategy.allow_op_delay = True
    exec_strategy.use_experimental_executor = True
    exec_strategy.num_threads = 20
    build_strategy = fluid.BuildStrategy()
    build_strategy.remove_unnecessary_lock = True

    train_exe = fluid.ParallelExecutor(
            use_cuda=False,
            main_program=train_program,
            build_strategy=build_strategy,
            exec_strategy=exec_strategy)

    # train_exe = fluid.Executor(fluid.CPUPlace())
    #exe = fluid.Executor(fluid.CUDAPlace(0))
    exe = fluid.Executor(fluid.CPUPlace())
    exe.run(fluid.default_startup_program())
```
