### ISSUE TITLE
模型无法收敛，感觉是梯度无法传播导致的

### ISSUE THREAD

**Issue by btobab** [PaddlePaddle/PARL#495]
[DDPG.zip](https://github.com/PaddlePaddle/PARL/files/5695297/DDPG.zip)
我自己搭了一个扫雷的gym环境，mines.py文件在gym的classic_control目录中，用的是python原生的minesweeper库，try.py历经艰辛终于能跑了，但模型始终无法收敛。调试发现是agent一直在点击同一个扫雷点，我给每次点击同一点施加了-1000的reward,并改成每step一次都learn一次，但还是没用。

**Comment by TomorrowIsAnOtherDay** [comment]
-> 【感觉是】梯度无法传播导致的 
你可以通过agent.get_weights()获得当前的参数，在每次learn之后，再次通过这个接口获得参数。
如果对比两份参数发现不一致，说明梯度是有回传并且更新模型的。

**Comment by TomorrowIsAnOtherDay** [comment]
你可以参考 #462 ，调试算法的问题得要自己多尝试增加经验。
