### ISSUE TITLE
重新安装老是提示 cannot import name 'layers' from 'parl'

### ISSUE THREAD

**Issue by ywh309392024** [PaddlePaddle/PARL#498]
您好！这二天重新安装提示：ImportError: cannot import name 'layers' from 'parl' (C:\Users\86189\AppData\Roaming\Python\Python37\site-packages\parl\__init__.py)
系统是 win10 64位 专业版  20H2，anaconda3(python3.8版本和python3.7都有试过），spyder 4.2.0 和4.1.5 也都试过
paddle 1.6  1.8.5 也都试过

**Comment by TomorrowIsAnOtherDay** [comment]
你能正确import paddle吗？

**Comment by yueyue-yue** [comment]
试试这个 pip3 install paddlepaddle==1.8.5

**Comment by YsanZyh** [comment]
请问有dalao解决了吗？

**Comment by TomorrowIsAnOtherDay** [comment]
请参考上面的解决方案：
`pip3 install paddlepaddle==1.8.5`

**Comment by HarryUP-rhy** [comment]
版本的问题，可以anaconda里创建一个虚拟环境（python3.6）然后安装paddle paddle1.6.3、parl1.3.1以及gym然后在运行代码应该就可以了
