### ISSUE TITLE
NeurIPS2020-Learning-to-Run-a-Power-Network-Challenge的grid2op问题

### ISSUE THREAD

**Issue by mycode2021** [PaddlePaddle/PARL#512]
track1和track2中运行evaluate.py，grid2op.make方法environment的l2rpn_neurips_2020_track1_small和l2rpn_neurips_2020_track1_small报异常大概意思是第一次使用需要下载数据之类的，这个是类似电子游戏那种ROM吗，怎么获取呢？

**Comment by YuechengLiu** [comment]
调用`grid2op.make(env_name)`时，`grid2op`会前往默认路径下寻找该环境对应文件，若不存在环境文件，则会自动下载该环境文件（默认路径为`~/data_grid2op`)。出现报错的话大概率是网络问题，挂代理翻墙应该可以解决这个问题~

你可以通过以下方式查看grid2op环境文件默认存放路径：
```python
grid2op.get_current_local_dir()
```
通过以下方式修改grid2op环境文件默认路径：
```python
grid2op.change_local_dir(new_dir)
```
详细可以参考API哈：
[github](https://github.com/rte-france/Grid2Op)，[API](https://grid2op.readthedocs.io/en/latest/)

**Comment by mycode2021** [comment]
谢谢
