### ISSUE TITLE
第二部分没看明白，请教下

### ISSUE THREAD

**Issue by janyChan** [PaddlePaddle/PARL#52]
请问下，我看到几种target实现分为server和client，意思是一个在服务器上运行，一个在客户端运行吗？client中看到了target的运行速度，但是server中并没有写出。请我我该怎么理解这部分的意思？

**Comment by zenghsh3** [comment]
1. server/client：这个主要是为了加速训练数据的收集，采用了分布式训练的方法。server主要使用GPU负责模型的训练和预测（预测主要是接受client发过来的observation，返回模型预测的action）；而client主要是用来运行仿真环境（Simulator），例如同时在128个CPU上跑128个client，它们会分别和server进行交互，并行地收集训练数据。
2. target速度在client这边主要用来计算reward，另外client返回给server的observation、info字段也会包含target速度相关信息。

**Comment by janyChan** [comment]
> 1. server/client：这个主要是为了加速训练数据的收集，采用了分布式训练的方法。server主要使用GPU负责模型的训练和预测（预测主要是接受client发过来的observation，返回模型预测的action）；而client主要是用来运行仿真环境（Simulator），例如同时在128个CPU上跑128个client，它们会分别和server进行交互，并行地收集训练数据。
> 2. target速度在client这边主要用来计算reward，另外client返回给server的observation、info字段也会包含target速度相关信息。

请问具体实现时候的意思是：
python simulator_server.py --port [PORT] --ensemble_num 1    这部分代码在server端电脑运行
python simulator_client.py --port [PORT] --ip [SERVER_IP] --reward_type RunFastest  这部分代码在client端电脑运行
然后，port随便用一个没被占用的，ip用server_ip的吗？

**Comment by zenghsh3** [comment]
对的，ip是指server端电脑的ip地址，端口是server端电脑使用的一个没占用的port（server和client的port参数应该是一样的）

**Comment by janyChan** [comment]
> 对的，ip是指server端电脑的ip地址，端口是server端电脑使用的一个没占用的port（server和client的port参数应该是一样的）

我看到client中有ip和port的默认值，server中没有port的默认值，这个是出于什么原因？

**Comment by janyChan** [comment]
> 对的，ip是指server端电脑的ip地址，端口是server端电脑使用的一个没占用的port（server和client的port参数应该是一样的）

感谢！🙏如果我只是在一台电脑上训练，没有用到分布式，这里参数应该如何设置呢？

**Comment by zenghsh3** [comment]
一样的，在一台电脑上分别启动server和client，ip设为该台电脑ip即可（但这个任务由于Simulator仿真速度比较慢，单个client收敛速度会很慢）
