### ISSUE TITLE
模型再训练和使用

### ISSUE THREAD

**Issue by VVIZE-ops** [PaddlePaddle/PARL#520]
模型训练结束后已经保存了，请问后面怎么再次训练或者使用模型

**Comment by rical730** [comment]
Hi, 使用`agent.save('model_dir')`保存模型之后，可以使用`agent.restore('./model_dir')`加载已保存的模型

可参考 https://github.com/PaddlePaddle/PARL/blob/develop/examples/QuickStart/train.py#L61

**Comment by VVIZE-ops** [comment]
> Hi, 使用`agent.save('model_dir')`保存模型之后，可以使用`agent.restore('./model_dir')`加载已保存的模型
> 
> 可参考 https://github.com/PaddlePaddle/PARL/blob/develop/examples/QuickStart/train.py#L61

我看了DQN代码里面保存为‘’dqn_model.ckpt‘’这种.ckpt格式，，这两个不一样么，使用哪个比较好

**Comment by rical730** [comment]
> 我看了DQN代码里面保存为‘’dqn_model.ckpt‘’这种.ckpt格式，，这两个不一样么，使用哪个比较好

PARL 1.3.3版本之前的agent.save默认会将learn_program参数保存至一个文件中，一般以.ckpt为后缀。从PARL 1.3.3 版本开始，agent.save会将所有program的模型参数都保存至一个文件夹中，更通用一些。

**Comment by VVIZE-ops** [comment]
> > 我看了DQN代码里面保存为‘’dqn_model.ckpt‘’这种.ckpt格式，，这两个不一样么，使用哪个比较好
> 
> PARL 1.3.3版本之前的agent.save默认会将learn_program参数保存至一个文件中，一般以.ckpt为后缀。从PARL 1.3.3 版本开始，agent.save会将所有program的模型参数都保存至一个文件夹中，更通用一些。
原来就是保存到文件夹啊，十分感谢！
那个我还想再请教一个问题，如果可以的话希望能够抽时间帮我解惑。我在使用DQN训练自己的一个应用场景的时候训练结果不稳定，而且loss十分巨大，anget和环境交互了几千步的时候还是10八次方这么大，请问这种情况我应该是修改网络模型还是调节学习率等超参数，再次感谢！

**Comment by rical730** [comment]
> 我在使用DQN训练自己的一个应用场景的时候训练结果不稳定，而且loss十分巨大，anget和环境交互了几千步的时候还是10八次方这么大，请问这种情况我应该是修改网络模型还是调节学习率等超参数

算法结果不符合预期，原因可能有很多，可以参考 https://github.com/PaddlePaddle/PARL/issues/462 ，需要自己多多尝试增加经验，加油！

**Comment by VVIZE-ops** [comment]
> > 我在使用DQN训练自己的一个应用场景的时候训练结果不稳定，而且loss十分巨大，anget和环境交互了几千步的时候还是10八次方这么大，请问这种情况我应该是修改网络模型还是调节学习率等超参数
> 
> 算法结果不符合预期，原因可能有很多，可以参考 #462 ，需要自己多多尝试增加经验，加油！

好的，多谢多谢！！！
