### ISSUE TITLE
请问关于examples中DDPG的问题？

### ISSUE THREAD

**Issue by Hins** [PaddlePaddle/PARL#525]
PARL/examples/DDPG/mujoco_agent.py的predict()函数中为什么每次都选第一个action作为不同state的预测结果呢？

**Comment by btobab** [comment]
@Hins  这是DDPG算法本身的问题，这个算法每次根据当前的state选择概率最大的action，可能这个action对环境的影响比较小，state矩阵没什么变化，所以喂给模型下一个state，还是输出跟之前相同的action。
如果要解决这个问题，建议使用SAC算法，这个算法加入了action分布的熵作为loss的一部分，目的是使action多样化，增强鲁棒性。
