### ISSUE TITLE
Invalid literal for int() with base 10: '200-beta0'

### ISSUE THREAD

**Issue by jiangjiajun** [PaddlePaddle/PARL#526]
错误提示如图所示
![image](https://user-images.githubusercontent.com/19339784/103336553-81aafc00-4ab3-11eb-9e12-6ce6dd9ab9c0.png)

**Comment by rical730** [comment]
Hi，这个问题已经在parl1.3.3版本修复，但目前parl1.3.3及以前的版本仅支持paddle静态图。
