### ISSUE TITLE
三个问题,什么时候支持paddlepaddle2

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PARL#528]
一、什么时候支持paddlepaddle2,哪怕是2.0.0rc1，因为GPU问题，要新版本
二、什么时候有https://parl.readthedocs.io/en/latest/index.html，这样的中文说明文档，
github自带的中文文档没有英文版详细，是不重视中国的开发人员？
三、百度AI社区没有PARL，是不重视PARL？有没交流QQ群？

**Comment by universea** [comment]
同问，那些常用的模型什么时候可以有动态图的版本呀？好像之前说的12月中旬哦

**Comment by TomorrowIsAnOtherDay** [comment]
十分感谢两位对于PARL的关注与支持，我逐个解答两位的问题。
1. 2.0目前已经支持了，但是example还没有完全迁移过去。这里的**支持**是指用户可以通过复用model/algorithm/agent 来开发自己的RL算法。
2. 我们的中文文档都统一托管到GitHub上（https://github.com/PaddlePaddle/PARL/blob/develop/docs/zh_CN/Overview.md ）， 采用markdown的方式，而非英文版本的readthedocs。主要原因是后者对于【中文】的文档显示不友好，编译生成文档过程中经常出现问题。至于提到的详细程度问题，目前除了API层面，在使用方式的文档这块，中英文两者几乎一致的。
3. 我们当然是很重视PARL的发展，这也是我们开源的最主要目标，目前的主要交流方式走issue，工作日时间点我们都会回复很快的。另外，我们之前在公开课期间组建了很多微信群，有兴趣可以到这个页面下：https://www.bilibili.com/video/BV1yv411i7xd 回复下微信号，后续我联系运营人员添加你。

**Comment by TomorrowIsAnOtherDay** [comment]
> 同问，那些常用的模型什么时候可以有动态图的版本呀？好像之前说的12月中旬哦

我们对example的重视程度是很高的，这也是PARL最为核心的特性之一：复现性。
我们在大部分的实验环境上跑了3组实验才验收通过发布的，这块需要时间逐步复现，毕竟之前提供的十几个算法模型都花了一整年时间逐个提供。我们会在这个季度逐步复现验收所有的example。

指标没有对齐论文，我们需要尝试不同超参数，这些都需要时间、计算资源去应对的。
这也是为了更好保障PARL的算法质量，请大家理解：）
