### ISSUE TITLE
I found two missing connections in the document README.md

### ISSUE THREAD

**Issue by Reatris** [PaddlePaddle/PARL#529]
https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/quickstart.md

Of the three forms of deployment at the end of the document, two are lost
the name '服务端部署' '侧端部署'

**Comment by TomorrowIsAnOtherDay** [comment]
Hello, it seems to be an issue of PaddleOCR. This is the PARL repository.
