### ISSUE TITLE
equires parl >= 1.4.1

### ISSUE THREAD

**Issue by andy2990** [PaddlePaddle/PARL#535]
parl的很多案例运行时显示：
from parl.utils import check_version_for_fluid  # requires parl >= 1.4.1
ImportError: cannot import name 'check_version_for_fluid'

目前parl的版本是1.4，请问什么时候更新1.4.1？

**Comment by TomorrowIsAnOtherDay** [comment]
抱歉造成这样的困扰，我们的发版计划是明天哈

**Comment by ddebby** [comment]
仍然没有新版本发布？

**Comment by zenghsh3** [comment]
已发布：https://pypi.org/project/parl/1.4.1/
