### ISSUE TITLE
ImportError: cannot import name 'layers' from 'parl' 

### ISSUE THREAD

**Issue by CastleDream** [PaddlePaddle/PARL#547]
库版本
```bash
paddlepaddle-gpu==2.0.0rc1.post110
parl==1.4.1
```
错误信息：
`
[01-25 13:50:20 MainThread @utils.py:79] WRN paddlepaddle version: 2.0.0-rc1. The dynamic graph version of PARL is under development, not fully tested and supported
Traceback (most recent call last):
  File "C:XXXXXX.py", line 8, in <module>
    from parl import layers
ImportError: cannot import name 'layers' from 'parl' (C:\software\anaconda\envs\rl37\lib\site-packages\parl\__init__.py)
Process finished with exit code 1
`
所以paddlepaddle2.0版本和parl1.4还是不兼容的吗？那如果我想安装11.0的GPU版本的情况下运行parl，是否有推荐的版本安装组合？

**Comment by TomorrowIsAnOtherDay** [comment]
我们目前的example 是针对静态图版本的，动态图 paddle 目前不建议配合PARL 使用。
建议paddle 版本与 这里对齐：https://github.com/PaddlePaddle/PARL#dependencies
也就是1.8.5 版本

**Comment by yueyue-yue** [comment]
是的 我也这个错误 pip3 install paddlepaddle==1.8.5就好了
