### ISSUE TITLE
periodical integrity test

### ISSUE THREAD

**Issue by TomorrowIsAnOtherDay** [PaddlePaddle/PARL#555]
The integrity test has some potential problems. It cannot guarantee that the latest code can run correctly.
For example, the developer A and B modify the code based on the version `V0` at the same time.
Then A submits the PR1 and B submits the PR2.
Both PRs can pass the unit tests, and they can be merged into the master branch.
But some bugs occur when their modifications are combined, which cannot be detected by our integrity test.

One of the solutions to this issue is to run the integrity test periodically.

**Comment by TomorrowIsAnOtherDay** [comment]
note1: After removing paddlepaddle from the test environment, the errors cannot be reproduced. 
note2: The errors reported in Linux now consist with that in Windows.

**Comment by zenghsh3** [comment]
Added a unit test pipeline that runs nightly.
