### ISSUE TITLE
对PARL的dqn默认实现代码中的一点疑问

### ISSUE THREAD

**Issue by ouyangshixiong** [PaddlePaddle/PARL#557]
`    
def learn(self, obs, action, reward, next_obs, terminal):

    pred_value = self.model(obs).gather(1, action)
`

dqn算法中有这样一句，它的self.model传入了obs对象，但是我看model类定义的此位置参数含义为act_dim。为啥这里把obs传递进去了，请大佬解惑，谢谢

class AtariModel(parl.Model):
  def __init__(self, act_dim, algo='DQN'):
    self.act_dim = act_dim

**Comment by TomorrowIsAnOtherDay** [comment]
hello，感谢对于PARL的关注。
你现在看的代码应该是动态图版本的吧？
根据model类的定义，此处确实是`act_dim`。
但是一定我们实例化这个类之后，我们直接调用这个类:self.model(obs)，这个调用的就是里面的forward函数。
请注意区分实例化一个对象用于初始化和调用已经初始化好的类。
对于这部分如果有进一步了解的想法，请查阅python类的`__call__`函数。

**Comment by ouyangshixiong** [comment]
谢谢大佬解惑！
