### ISSUE TITLE
请教PARL模型评估&部署问题

### ISSUE THREAD

**Issue by ouyangshixiong** [PaddlePaddle/PARL#558]
我在issues中搜索并没有找到类似的问题，如果提问重复，请删除。It's OK.
问题描述：
1. 使用DDQN，A2C算法分别对手机游戏（并不是模拟器）智能体进行训练。速度太慢
2. 自己编写了模拟器，脱离了游戏本身的限制，仍然采用DDQN和A2C算法训练。从vusialdl看训练过程，都是正常的。
3. 已经获得了四个模型文件。请问如何评估？部署？

![微信截图_20210222080346](https://user-images.githubusercontent.com/2086862/108643234-9d93b280-74e4-11eb-891a-f95044364509.png)

BTW，程序有个warning，烦请大佬帮忙看看：
`c:\users\edz\.conda\envs\paddle-gpu\lib\site-packages\paddle\fluid\io.py:208: UserWarning: The input is a CompiledProgram, this is not recommended.
  "The input is a CompiledProgram, this is not recommended.")`

**Comment by TomorrowIsAnOtherDay** [comment]
抱歉，忘记看GitHub的邮件了，回复略晚。
关于评估：请参考我们的[文档](https://github.com/PaddlePaddle/PARL/blob/develop/docs/zh_CN/tutorial/param.md)，调用`load`接口加载模型参数，然后与环境进行评估交互即可。
关于部署：建议先熟悉飞桨生态中的paddle-lite，然后导出PARL的模型，用lite加载跑起来。
https://github.com/PaddlePaddle/Paddle-Lite

**Comment by TomorrowIsAnOtherDay** [comment]
warning这个问题，建议去飞桨核心框架的仓库中提问相关问题哈，我们这边主要负责强化学习方向的工作，关于底层计算框架的问题，那个仓库的开发同学更熟悉以及专业点。

**Comment by ouyangshixiong** [comment]
好的，您列举的文档我都看了，怎么说呢，略显简陋了。
Paddle-Lite我试过飞桨的目标检测类的部署，如果是类似的应该没问题。
然后那个warning，说的是模型是已编译的，这个我就不确定了，不知道已编译有什么坑没有？
非常感谢您的回复。

**Comment by TomorrowIsAnOtherDay** [comment]
抱歉，这个确实太粗糙了，我新增一个能跑的示范，这样用户直接copy代码就可以跑起来。
为了进一步完善文档，后续我们会新增一个tutorial：如何相关的导出模型用于paddle-lite的部署。
这个工作预期动态图迁移完成之后才做这个工作，因为动态图的部署和当前静态图版本会有所区别。
