### ISSUE TITLE
如何实现日志按时间或者大小分割？

### ISSUE THREAD

**Issue by YeFeiyangx** [PaddlePaddle/PARL#562]
使用parl.untils 种的logger时，可以自己设置日志的分卷标准吗？譬如按时间或者按大小分文件存储。

**Comment by TomorrowIsAnOtherDay** [comment]
目前PARL没有提供相应的接口。理论上是可以做到的，底层实现是基于python的[logging模块](https://docs.python.org/zh-cn/3.7/library/logging.html)，这块可以参考下。也欢迎给我们贡献代码。
建议参考：https://www.jianshu.com/p/5a4e226444bd
