### ISSUE TITLE
dqn和ddqn的带权误差接口

### ISSUE THREAD

**Issue by ElemTran** [PaddlePaddle/PARL#564]
使用Prioritized Replay memory时，没有ddqn学习过程没有对应weight(采样数据的权重）的接口。btw：paddle好像也没有带权的mse。
当然Prioritized Replay memory没有对应的sumTree的实现

**Comment by btobab** [comment]
@ElemTran 
建议深入了解一下rainbow,DQN一共有7个tip优化，DDQN是其中一种，对Replay memory的优化，将重要的经验加权也是其中一种，当然可以两个tip一起用，七个一起用也可以~

**Comment by TomorrowIsAnOtherDay** [comment]
感谢楼上的协助解答，DDQN 和Prioritized Replay memory 确实是两个独立的工作来的。
DDQN: https://arxiv.org/abs/1509.06461
Prioritized Replay memory:  https://arxiv.org/abs/1511.05952
PARL 目前复现的算法是以paper为单位的，这样也是方便大家根据paper里面提到的算法来查找对应的代码。

**Comment by TomorrowIsAnOtherDay** [comment]
另外关于带权重的MSE loss，这个应该是相当容易实现的。
你先把不带权重的square loss 计算出来，然后乘以权重，这样就是带权重的loss了。
之后调用minimize这个接口来最小化loss即可。
