### ISSUE TITLE
关于Paddle版本

### ISSUE THREAD

**Issue by Sharpiless** [PaddlePaddle/PARL#567]
请问PARL现在支持2.0版本吗？

**Comment by TomorrowIsAnOtherDay** [comment]
感谢你对于PARL的关注：）
目前的主干分支是支持2.0版本的，但是支持的算法并没有静态图那么多，2.0正式版刚发布不久，目前还有10个左右的算法在等待复现。
动态图版本的example 参考这里：https://github.com/PaddlePaddle/PARL/tree/develop/benchmark/paddle

**Comment by TomorrowIsAnOtherDay** [comment]
hello，目前PARL已经全面迁移到动态图版本，请参考我们的最新文档进行使用。
