### ISSUE TITLE
使用paddlepaddle-gpu时GPU占用少，CPU占用大的情况

### ISSUE THREAD

**Issue by rgs6655** [PaddlePaddle/PARL#579]
RT，使用paddlepaddle跑D3QN的强化学习代码，三层的网络
1.请问如何更好的利用GPU？
2.请问为什么CPU占用率这么高？

环境：Ubuntu 18.04.5 LTS
我的paddlepaddle和parl版本号如下：
`paddlepaddle-gpu       2.0.1.post101`
`parl                   1.3.1`
输入python -m paddle.distributed.launch train.py后显示
![image](https://user-images.githubusercontent.com/21187385/110937311-275cd000-836d-11eb-8a22-36179b16b9bd.png)
![image](https://user-images.githubusercontent.com/21187385/110937322-2deb4780-836d-11eb-991e-ea6046620cca.png)

**Comment by TomorrowIsAnOtherDay** [comment]
Hello：）
这个情况是合理的，CPU占用高是因为需要跑交互（Atari游戏只能在CPU上）。
GPU使用率不高是因为使用GPU进行训练，训练速度很快，一下子就更新完模型了，然后程序又进行到和游戏交互了（CPU使用率高）。

**Comment by rgs6655** [comment]
> Hello：）
> 这个情况是合理的，CPU占用高是因为需要跑交互（Atari游戏只能在CPU上）。
> GPU使用率不高是因为使用GPU进行训练，训练速度很快，一下子就更新完模型了，然后程序又进行到和游戏交互了（CPU使用率高）。

谢谢你的回复~
