### ISSUE TITLE
IMPALA如何启动多个learner

### ISSUE THREAD

**Issue by LJianlin** [PaddlePaddle/PARL#583]
我现在完成了IMPALA算法单个learner的调试，我现在想同时启动多个learner进行训练，请问我该如何编写代码？在原代码的基础上需要进行哪些改动？

**Comment by zenghsh3** [comment]
目前我们IMPALA示例是单learner+多actor的训练模式，之前测试在Tesla P40 GPU（单learner）上支持64+ CPU（actor）的训练。请问现在需要启动多个learner训练的原因是？

**Comment by LJianlin** [comment]
现在一个learner训练只能在一张卡上面启动，看到论文中可以进行多个Learner的训练，所以我想试一试，在PARL下如何同时启动多个learner进行训练，充分利用一台机器上的资源。想请问下PARL是否有相关的例程，或者我在给定的单learner example下如何修改

**Comment by TomorrowIsAnOtherDay** [comment]
目前没有的呢。多个learner一起训练的实现方式我们之前调研过，训练速度并没有加快多少，所以没有开源出来。

**Comment by TomorrowIsAnOtherDay** [comment]
现阶段强化学习用的模型比较小，单卡训练足以，在learner这块做的训练加速工作并不会有很大提升。
如果某天强化学习的模型有BERT那么大，多个learner才有必要的使用场景。

**Comment by LJianlin** [comment]
好的，谢谢
