### ISSUE TITLE
有Save和Load的代码示例吗？我本地试验失败

### ISSUE THREAD

**Issue by kosoraYintai** [PaddlePaddle/PARL#59]
win7环境
本地使用DQN算法训练迷宫问题，训练完成后达到了最优解，并save模型；
重新运行程序，load模型，得到的结果并不是最优解；
效果在这里：
https://github.com/kosoraYintai/PARL-Sample/blob/master/dqn_dnn/README.md
不知道错在哪里
DDPG、DQN、PPO等示例均未找到save和load模型的示例，可否提供代码模板？

**Comment by zenghsh3** [comment]
你的dqn_dnn代码里的save/load参数这块是没有问题的，示例可以参考[Paddle官网 fluid.io](http://paddlepaddle.org/documentation/docs/zh/1.3/api_cn/io_cn.html)

问题出在你在train和test分别建立了两个model，它们的参数名是不一样的，我在Fluid 1.3.0跑你的dqn_dnn，像下面一样跑完train后，用test的model去load的话是会抛出找不到参数错误的。
```
train()
test()
```

如果你是跑完train后，像下面一样进行测试的话是没问题的，因为这时候只创建了一个model，参数名是会和训练时创建的model 的参数名一致，测试结果也和训练后得到的最优解一致
```
#train()
test()
```

你可以通过Model里的parameter_names属性进行查看参数名，例如下面：
```
model1 = MazeModel()
print(model1. parameter_names)
# model1 (相当于你代码里train里面model)参数：[fc.w_0, fc.b_0, fc.w_1, fc.b_1, fc.w_2, fc.b_2]

model2 = MazeModel()
print(model2. parameter_names)
# model2（相当于你代码里test里面model）参数:  [fc.w_3, fc.b_3, fc.w_4, fc.b_4, fc.w_5, fc.b_5]
```

**Comment by kosoraYintai** [comment]
谢谢，更新了paddle库，可以了
