### ISSUE TITLE
When will the maddpg of the dynamic graph version be updated?

### ISSUE THREAD

**Issue by universea** [PaddlePaddle/PARL#598]
Thanks!

**Comment by TomorrowIsAnOtherDay** [comment]
Hi @universea , thanks for your interest in dynamic graph version. 
We are currently working on updating our examples for eager-mode paddle.
Our plan is to update the algorithms of single-agent at first (progress bar 80%).
The next step after single-agent is multi-agent algorithms such as MADDPG. Hopefully, it will be finished at the beginning of May.

**Comment by universea** [comment]
Thank you very much !

**Comment by TomorrowIsAnOtherDay** [comment]
added at #660 .
