### ISSUE TITLE
多机多卡训练

### ISSUE THREAD

**Issue by LJianlin** [PaddlePaddle/PARL#599]
您好，我想咨询下，你们做过多机多卡训练强化学习的实验吗？因为我发现大部分论文里都说使用了多少GPU和CPU，但是并没人解释该如何使用大量的GPU进行训练。
我最近在尝试开发多机多卡进行强化学习算法的训练，但是我发现两台机器之间的数据通信非常耗时，远远要比单机多卡训练要慢，请问你们那边有过这样的情况发生吗？我想知道多机多卡训练是否是一条比较好的解决方案。

**Comment by TomorrowIsAnOtherDay** [comment]
> 我想知道多机多卡训练是否是一条比较好的解决方案。

抱歉，清明节期间没有及时回复。你的结论是没有问题的：两台机器之间的数据通信非常耗时，远远要比单机多卡训练要慢。
这个主要的原因是当前强化学习的模型太小了，单卡训练已经足够。DQN的模型参数也只是在几十万的级别，远远小于NLP领域的预训练模型BERT。
可以参考#583 的讨论。

**Comment by LJianlin** [comment]
非常感谢您的回复，我想请教您一点问题，如果一个强化学习环境过于复杂，一台机器已经训练不了的时候，这时我应该采用多机的方案还是应该想办法简化模型呢？以及有没有一种方法可以评估某个问题训练时，应该用到多少台机器呢？是否应该使用分布式的方法进行训练？

**Comment by TomorrowIsAnOtherDay** [comment]
如果追求问题最终的效果，则只需考虑多机器并行（CPU 并行），简化模型一般会带来效果的下降。

以及有没有一种方法可以评估某个问题训练时，应该用到多少台机器呢
--------------
没有的，我建议你先精简问题规模，先在一个相对简单的问题上验证算法可行性，然后提升问题规模，等数据遇到瓶颈了再引入多机器训练。

**Comment by LJianlin** [comment]
好的，明白了，非常感谢您的解惑！

**Comment by TomorrowIsAnOtherDay** [comment]
我先关闭issue了，有问题欢迎交流：）同时也希望你推广下PARL。
