### ISSUE TITLE
ubantu anaconda 没有源可以装parl

### ISSUE THREAD

**Issue by YeFeiyangx** [PaddlePaddle/PARL#610]
清华源 科大源 conda主站，都没有parl的源可以装，请问有什么办法吗？用git的方式，速度好慢。

**Comment by TomorrowIsAnOtherDay** [comment]
hello，感谢你的反馈。
目前我们是没有在conda上发布我们的源，但是即便是在conda环境上，我们依然可以通过pip 安装。
请参考我们的[安装文档](https://github.com/PaddlePaddle/PARL/blob/develop/docs/zh_CN/Overview.md#%E5%AE%89%E8%A3%85-1)，里面包含pip 清华源以及使用国内代码镜像加速安装的方法。

**Comment by YeFeiyangx** [comment]
觉得parl非常好用，支持也都很好，怎么就没火呢。。。对于小白自学，我补充一下，在linux系统里需要配置pythonpath的环境变量才可以用pip把parl装上。
