### ISSUE TITLE
工程老师，我把xparl当多进程使用了，但是在docker镜像中跑一段时间会自动退出。

### ISSUE THREAD

**Issue by YeFeiyangx** [PaddlePaddle/PARL#627]
python原生的多进程效率太低，用xparl做并行计算时，感觉十分爽。但是现在发现一个问题，正常在centos的环境下，我启用python的并行计算服务，长期运行都是没问题的。当我把服务放在docker中，运行短暂的约15秒，之后的计算服务请求就会卡住。请问这个有社么解决思路吗？xparl实在太香了。

**Comment by TomorrowIsAnOtherDay** [comment]
hahaha，感谢**真香**赞美。
问下方便提供下docker镜像吗？可以把你的镜像push到dockerhub上面，然后我们这边pull下来复现定位下问题。
