### ISSUE TITLE
Cannot find available GPU devices, using CPU or other devices now

### ISSUE THREAD

**Issue by roshanthink** [PaddlePaddle/PARL#634]
系统： WIN10
Paddle：2.1 GPU
PARL：1.4.3及develop 均测试

现象：
Paddle自身检测GPU无问题，但PARL运行时提示
“Cannot find available GPU devices, using CPU or other devices now”

**Comment by TomorrowIsAnOtherDay** [comment]
十分感谢你的反馈，我们这边先去复现下。

**Comment by zenghsh3** [comment]
你好，这边可以正常执行`nvidia-smi -L`命令吗？

**Comment by roshanthink** [comment]
> 你好，这边可以正常执行`nvidia-smi -L`命令吗？

感谢！解决了！把：

> C:\Program Files\NVIDIA Corporation\NVSMI

加入到环境变量就可以了！

**Comment by roshanthink** [comment]
> 十分感谢你的反馈，我们这边先去复现下。

已经解决，感谢回答

**Comment by TomorrowIsAnOtherDay** [comment]
十分感谢你的反馈。
我们已经在 #635 中新增错误信息帮助用户定位问题。
