### ISSUE TITLE
请问Parl的说明文档现在有吗？想看看Parl里的函数

### ISSUE THREAD

**Issue by ZhuGeComing** [PaddlePaddle/PARL#64]

**Comment by TomorrowIsAnOtherDay** [comment]
目前了解PARL的最好方式是通过我们的[quick start](https://github.com/PaddlePaddle/PARL/tree/develop/examples/QuickStart)呢
建议先看model，再看algorithm，agent，结合首页的readme 很容易熟悉这个框架的。
相应的函数文档也比较齐全，在代码里面可以看到。
具体的文档页面我们后续会推出的：）
看代码过程中有问题请随时提出来。

**Comment by ZhuGeComing** [comment]
> 
> 
> 目前了解PARL的最好方式是通过我们的[quick start](https://github.com/PaddlePaddle/PARL/tree/develop/examples/QuickStart)呢
> 建议先看model，在看algorithm，agent，结合首页的readme 很容易熟悉这个框架的。
> 相应的函数文档也比较齐全，在代码里面可以看到。
> 具体的文档页面我们后续会推出的：）
> 看代码过程中有问题请随时提出来。

好的，谢谢^_^
