### ISSUE TITLE
wrap_deepmind() got an unexpected keyword argument 'test'

### ISSUE THREAD

**Issue by Gjunze** [PaddlePaddle/PARL#656]
跑 example 里面的DQN_variant里面的例子时候，train.py 调用了 parl.env里面的 wrap_deepmind(), 总是报wrap_deepmind() got an unexpected keyword argument 'test' 错误, 找到函数定义地方没发现问题，请教老师
环境是： win 10 , padddlepaddle-gpu 2.1.0    parl 2.0

**Comment by rical730** [comment]
噢抱歉带来困扰，我们近期升级了wrap_deepmind()的接口还未发版，建议可以git clone仓库下来，在仓库根目录下使用`pip install -U .`源码安装的方式安装parl，可以解决这个问题。

**Comment by Gjunze** [comment]
感谢，感谢，自己捣鼓了好久

**Comment by rical730** [comment]
抱歉带来糟糕的体验😰，我们会尽快发小版本解决这个问题。

**Comment by rical730** [comment]
Hi，由于DQN_variant是我们近期新增的example，为了适配example升级了wrap_deepmind()的接口，因此2.0.0版本无法跑通examples/DQN_variant，目前我们已经发了小版本parl==2.0.1来解决这个问题，欢迎继续使用parl开发调试 ^_^

**Comment by TomorrowIsAnOtherDay** [comment]
已经发版，感谢反馈：）
