### ISSUE TITLE
【core】 check if the user has implemented the required functions in parl.Model

### ISSUE THREAD

**Issue by TomorrowIsAnOtherDay** [PaddlePaddle/PARL#658]
Users are expected to implement the `forward` function for the value-based algorithms such as DQN.
For actor-critic functions, the users should implement both `policy` and `value` functions.
Currently, there is no documentation describing the needed functions. 
We can add some tests at the initialization function for each provided algorithms.

**Comment by rical730** [comment]
done in https://github.com/PaddlePaddle/PARL/pull/682
