### ISSUE TITLE
关于并行环境采样的问题

### ISSUE THREAD

**Issue by crvz6182** [PaddlePaddle/PARL#661]
您好，我有两个问题想请教一下
1.训练时如果想并行多个环境进行采样，相关的并行逻辑和数据处理等部分是否没有做封装需要自己写
2.PARL自带的PPO算法是否都只能用于连续动作空间

**Comment by TomorrowIsAnOtherDay** [comment]
1. 这个可以参考我们的XPARL 并行文档来自行开发，开发的成本不高，因为我们的并行接口使用起来和单机类似。
2. 是的，目前只针对连续控制进行开发，因为相比主流的离散控制算法，PPO的效果还是差距很大的，无法和APE-x、IMPALA、R2D2等算法相比较。

**Comment by crvz6182** [comment]
好的，谢谢
