### ISSUE TITLE
疑似错误

### ISSUE THREAD

**Issue by meadewaking** [PaddlePaddle/PARL#687]
在/parl/algorithms/torch/dqn.py与/parl/algorithms/torch/ddqn.py中第44行
为   self.target_model = copy.deepcopy(model)
是否应该为    self.target_model = copy.deepcopy(self.model)   ？

**Comment by rical730** [comment]
感谢对PARL的关注，第44行这么写是没问题的，因为第43行有self.model=model，所以您提出的两种写法是等价的。

https://github.com/PaddlePaddle/PARL/blob/develop/parl/algorithms/torch/dqn.py#L43
