### ISSUE TITLE
DDPG的表现

### ISSUE THREAD

**Issue by IanWangg** [PaddlePaddle/PARL#688]
在TD3和SAC论文里DDPG在Hopper环境里在1e6 gradient step后约为1200~2000分，为什么paddle_DDPG能达到2500并且基本稳定在2000～2500？是增加了什么优化吗

**Comment by TomorrowIsAnOtherDay** [comment]
hello，我们算法的实现是参考作者的开源代码的。
我们适当调整了下超参数，没有做额外的优化。
