### ISSUE TITLE
Ubuntu18.04环境中PARL2.x无法使用GPU算力

### ISSUE THREAD

**Issue by ouyangshixiong** [PaddlePaddle/PARL#689]
### 环境：
1. Ubuntu18.04 (PaddlePaddle官方指定版本)
2. CUDA 10
3. cudnn 7
4. GPU  GTX 1030ti
5. PaddlePaddle 2.0.2
6. parl 2.0.2

### 问题截图：

1. 飞桨官方脚本输出信息
![WechatIMG90](https://user-images.githubusercontent.com/2086862/126090497-5d0b940b-5867-4b1e-ad77-8399a61ed0dd.jpeg)

2. GPU信息
![WechatIMG87](https://user-images.githubusercontent.com/2086862/126090538-46a9f7a4-6d2d-4642-afcb-d163031b1bea.jpeg)

3. PaddlePaddle和PARL版本信息
![WechatIMG89](https://user-images.githubusercontent.com/2086862/126090618-9cab179a-3be4-4eec-a2f2-cf3b67b1ebf5.jpeg)

4. 启动xparl报错信息
![WechatIMG88](https://user-images.githubusercontent.com/2086862/126090697-6eec06b8-b081-4eda-8906-ea00d44b6402.jpeg)

我不仅仅试过paddlepaddle-gpu 2.0.2 parl2.0.2 CUDA10 cudnn7， 其他版本比如paddlepaddle-gpu 2.1.1 CUDA11 cudnn8我都试过，都无法正确使用GPU算力。请尽快修复。

**Comment by TomorrowIsAnOtherDay** [comment]
hello，十分感谢你的反馈。
xparl默认是关闭GPU进行并行的，这个的出发点是担心用户启动太多节点同时运行，GPU显存被撑爆的情况出现。
请问你运行[DQN+atari](https://github.com/PaddlePaddle/PARL/tree/develop/examples/DQN_variant)是否可以看到GPU正常使用呢？

**Comment by ouyangshixiong** [comment]
谢谢您的回复。我刚刚测试过，example项目 DQN+atari是可以正常使用GPU
![WechatIMG91](https://user-images.githubusercontent.com/2086862/126099326-52da8400-b6a7-4d1c-8e60-f966ae054d6c.jpeg)
我下一步应该怎么做呢？

**Comment by TomorrowIsAnOtherDay** [comment]
那这说明PARL现在是正常运行的哈。
xparl 启动集群是为了分布式并行计算用的，主要是使用CPU，目前这个提示不影响正常使用的。

**Comment by ouyangshixiong** [comment]
已测试过训练程序确实可以用GPU算力。谢谢！
