### ISSUE TITLE
xparl能不能把一个实体GPU拆成几个虚拟的GPU?

### ISSUE THREAD

**Issue by EastSmith** [PaddlePaddle/PARL#696]
xparl牛的地方是可以解锁Python的GIL，开启多线程使用CPU集群并行训练，我不清楚的地方是xparl能不能把一个实体GPU拆成几个虚拟的GPU，每个虚拟的GPU都独立进行前向运算以及反向传播?

**Comment by TomorrowIsAnOtherDay** [comment]
这个暂时没有噢。我们的并行主要是针对CPU层面的，因为RL需要采集大量的交互数据。
感谢你对xparl的认可哈哈哈哈，欢迎继续使用。

**Comment by EastSmith** [comment]
好的，感谢解答。我可以这样理解，智能体的探索主要是用CPU，训练可以用GPU，然后保持cpu数量（算力）与GPU数量（算力）之间有一个合理的比例

**Comment by TomorrowIsAnOtherDay** [comment]
理解很透彻，对的！
