### ISSUE TITLE
请问老师，py3.7.1可以用parl/xparl的全部功能吗

### ISSUE THREAD

**Issue by yglpyn8888** [PaddlePaddle/PARL#697]
因为在文档看到一句
依赖
Python 3.6+. (Python 3.8+ 更适合用于并行训练)

我项目还有其他的库 综合后目前我项目使用的PYTHON版本是3.7.1
能否使用parl/xparl全部 加速 OR 并行的功能？谢谢。

**Comment by TomorrowIsAnOtherDay** [comment]
没问题的。并行功能，py3.7/3.8都可以使用我们的并行，只是3.8新增的特性可以使得通讯效率更高，并行更快。
3.7如果需要增加并行速度的话，可以自行安装pyarrow来增加速度，参考如下命令：
```python
pip install pyarrow==2.0.0
```

**Comment by yglpyn8888** [comment]
谢谢老师！
