### ISSUE TITLE
试写动态图ddpg 遇到错误 ValueError: super(YourLayer, self).__init__() should be called first

### ISSUE THREAD

**Issue by ZerounNet** [PaddlePaddle/PARL#698]
site-packages\paddle\fluid\dygraph\layers.py", line 1083, in __setattr__
    raise ValueError(
ValueError: super(YourLayer, self).__init__() should be called first

**Comment by TomorrowIsAnOtherDay** [comment]
hello，这个看起来像是你model定义的问题。
请参考我们quick_start 里的写法：https://github.com/PaddlePaddle/PARL/blob/develop/examples/QuickStart/cartpole_model.py
