### ISSUE TITLE
安装parl1.3.1失败

### ISSUE THREAD

**Issue by ZhaiYHong** [PaddlePaddle/PARL#703]
高版本parl可以安装 但是parl1.3.1安装出错：ERROR：No matching distribution found for pyarrow==0.13.0                  OSError:'git' was not found  请问这种怎么解决？

**Comment by TomorrowIsAnOtherDay** [comment]
hello，问下你的环境是在Windows系统还是别的系统呢？

**Comment by ZhaiYHong** [comment]
> hello，问下你的环境是在Windows系统还是别的系统呢？

你好 我的是在windows8 下的anaconda里装的

**Comment by TomorrowIsAnOtherDay** [comment]
python版本号是多少呢？ pyarrow在Windows上支持python3.7+的

**Comment by TomorrowIsAnOtherDay** [comment]
pyarrow这个序列化的库兼容性很一般。我们在最新版本里面用python原生的库替换掉了它，所以新版本不存在这个问题。

**Comment by ZhaiYHong** [comment]
> python版本号是多少呢？ pyarrow在Windows上支持python3.7+的

python是3.8.8

**Comment by ZhaiYHong** [comment]
> pyarrow这个序列化的库兼容性很一般。我们在最新版本里面用python原生的库替换掉了它，所以新版本不存在这个问题。

那我是不是没法安装低版本的parl了

**Comment by TomorrowIsAnOtherDay** [comment]
建议更换python 版本为3.6的尝试下哈，我刚查了pyarrow的官网，写着py3.6+。
windows8的时候，还没有出来python3.8，估计pyarrow不支持。

**Comment by ZhaiYHong** [comment]
> 建议更换python 版本为3.6的尝试下哈，我刚查了pyarrow的官网，写着py3.6+。
> windows8的时候，还没有出来python3.8，估计pyarrow不支持。

windows10我也试了，报错是一样的，那我更换python版本试试  谢谢

**Comment by TomorrowIsAnOtherDay** [comment]
我刚看了下，建议你安装1.4版本哈，1.4的时候已经移除掉了pyarrow的依赖，还是使用的静态图，可以支持B站课程的代码运行。

**Comment by ZhaiYHong** [comment]
好的  感谢 我去试试

**Comment by ZhaiYHong** [comment]
> 我刚看了下，建议你安装1.4版本哈，1.4的时候已经移除掉了pyarrow的依赖，还是使用的静态图，可以支持B站课程的代码运行。

你好  parl1.4里面的utils包是不是没有action_mapping文件呀   我在做四轴飞行器大作业时候import失败这个py文件

**Comment by TomorrowIsAnOtherDay** [comment]
啊，我们确实在#476 移除掉了action_mapping，取而代之的是一个wrapper。
现阶段我建议你直接用下面这个实现就好
```python
def action_mapping(model_output_act, low_bound, high_bound):
    """ mapping action space [-1, 1] of model output 
        to new action space [low_bound, high_bound].
    Args:
        model_output_act: np.array, which value is in [-1, 1]
        low_bound: float, low bound of env action space
        high_bound: float, high bound of env action space
    Returns:
        action: np.array, which value is in [low_bound, high_bound]
    """
    assert np.all(((model_output_act<=1.0 + 1e-3), (model_output_act>=-1.0 - 1e-3))), \
        'the action should be in range [-1.0, 1.0]'
    assert high_bound > low_bound
    action = low_bound + (model_output_act - (-1.0)) * (
        (high_bound - low_bound) / 2.0)
    action = np.clip(action, low_bound, high_bound)
    return action
```

**Comment by ZhaiYHong** [comment]
> 啊，我们确实在#476 移除掉了action_mapping，取而代之的是一个wrapper。
> 现阶段我建议你直接用下面这个实现就好
> 
> ```python
> def action_mapping(model_output_act, low_bound, high_bound):
>     """ mapping action space [-1, 1] of model output 
>         to new action space [low_bound, high_bound].
>     Args:
>         model_output_act: np.array, which value is in [-1, 1]
>         low_bound: float, low bound of env action space
>         high_bound: float, high bound of env action space
>     Returns:
>         action: np.array, which value is in [low_bound, high_bound]
>     """
>     assert np.all(((model_output_act<=1.0 + 1e-3), (model_output_act>=-1.0 - 1e-3))), \
>         'the action should be in range [-1.0, 1.0]'
>     assert high_bound > low_bound
>     action = low_bound + (model_output_act - (-1.0)) * (
>         (high_bound - low_bound) / 2.0)
>     action = np.clip(action, low_bound, high_bound)
>     return action
> ```

> 啊，我们确实在#476 移除掉了action_mapping，取而代之的是一个wrapper。
> 现阶段我建议你直接用下面这个实现就好
> 
> ```python
> def action_mapping(model_output_act, low_bound, high_bound):
>     """ mapping action space [-1, 1] of model output 
>         to new action space [low_bound, high_bound].
>     Args:
>         model_output_act: np.array, which value is in [-1, 1]
>         low_bound: float, low bound of env action space
>         high_bound: float, high bound of env action space
>     Returns:
>         action: np.array, which value is in [low_bound, high_bound]
>     """
>     assert np.all(((model_output_act<=1.0 + 1e-3), (model_output_act>=-1.0 - 1e-3))), \
>         'the action should be in range [-1.0, 1.0]'
>     assert high_bound > low_bound
>     action = low_bound + (model_output_act - (-1.0)) * (
>         (high_bound - low_bound) / 2.0)
>     action = np.clip(action, low_bound, high_bound)
>     return action
> ```

好的 谢谢
