### ISSUE TITLE
运行速度慢

### ISSUE THREAD

**Issue by ZhaiYHong** [PaddlePaddle/PARL#708]
你好  我在examples下的DQN_variant 使用DDQN   程序运行速度特别慢   大概3.4it/S  请问这是哪里出问题了啊？

**Comment by TomorrowIsAnOtherDay** [comment]
请问下你是在GPU上运行代码吗？
DQN_variant 里面涉及到图像相关的卷积计算，在CPU上计算速度比较慢。
