### ISSUE TITLE
benchmark示例中的图表怎么生成啊

### ISSUE THREAD

**Issue by Czzzzzzh** [PaddlePaddle/PARL#712]
readme里面的benchmark里的那个reward的趋势图可以生成吗，还是仅仅作为一个例子呈现在那里

**Comment by zenghsh3** [comment]
你好，具体指那个示例呢？

**Comment by Czzzzzzh** [comment]
<img width="460" alt="Screen Shot 2021-08-29 at 12 02 56" src="https://user-images.githubusercontent.com/81168721/131237951-69613edc-8815-4682-b40d-ac73e31764b1.png">

**Comment by Czzzzzzh** [comment]
这个这个

**Comment by zenghsh3** [comment]
可以提供下github链接吗？

**Comment by Czzzzzzh** [comment]
https://github.com/PaddlePaddle/PARL/blob/r1.3/examples/LiftSim_baseline/DQN/rl_10.png

**Comment by TomorrowIsAnOtherDay** [comment]
这个是记录数据到本地，使用matplotlib重新绘制的。
