### ISSUE TITLE
关于actor和learner自由选择device的问题

### ISSUE THREAD

**Issue by cjdjr** [PaddlePaddle/PARL#713]
我是将torch作为backend，通过@parl.remote_class修饰符进行并行运算。
我发现actor和learner默认都会用同一块gpu，导致增加actor数量会使得gpu显存爆炸，请问以下两个问题有解决方法吗？
1、能否设置不同actor工作在不同的gpu上？
2、能否设置actor工作在cpu上？

**Comment by TomorrowIsAnOtherDay** [comment]
hello，感谢你的反馈，目前是默认不使用CPU的。也就是你提到的第二点：
https://github.com/PaddlePaddle/PARL/blob/7a910d3c586b01f18523ad45e4f8ecc7b49a249f/parl/remote/job.py#L17
