### ISSUE TITLE
ImportError: cannot import name 'layers'

### ISSUE THREAD

**Issue by sofiathefirst** [PaddlePaddle/PARL#714]
Envirment:
ubuntu 18
Python 3.6.9
paddlepaddle                      2.1.2
pandas                            1.1.5
parl                              2.0.2

**Comment by zenghsh3** [comment]
`from parl import layers` is only supported in paddle static graph (paddlepaddle < 2.0).

**Comment by TomorrowIsAnOtherDay** [comment]
Solve the problem with the following command:
`pip install paddlepaddle==1.8.5`

**Comment by sofiathefirst** [comment]
the readme  told me :  [paddlepaddle>=2.0]

**Comment by TomorrowIsAnOtherDay** [comment]
Sorry, I didn't notice that you have installed the PARL 2.0+. 
Which example did you run?

**Comment by sofiathefirst** [comment]
PARL-2.0.0  


\PARL-2.0.0\examples\tutorials\lesson3\dqn>python train.py
[32m[09-01 15:47:32 MainThread @logger.py:242][0m Argv: train.py
[32m[09-01 15:47:33 MainThread @utils.py:73][0m paddlepaddle version: 2.1.2.
Traceback (most recent call last):
  File "train.py", line 23, in <module>
    from model import Model
  File "C:\Users\hp\PARL-2.0.0\examples\tutorials\lesson3\dqn\model.py", line 18, in <module>
    from parl import layers  # 封装了 paddle.fluid.layers 的API
ImportError: cannot import name 'layers' from 'parl' (C:\Users\hp\.conda\envs\paddle\lib\site-packages\parl\__init__.py)

**Comment by TomorrowIsAnOtherDay** [comment]
Please follow the [instruction](https://github.com/PaddlePaddle/PARL/tree/develop/examples/tutorials#%E5%AE%89%E8%A3%85%E4%BE%9D%E8%B5%96%E6%B3%A8%E6%84%8F%E8%AF%B7%E5%8A%A1%E5%BF%85%E5%AE%89%E8%A3%85%E5%AF%B9%E5%BA%94%E7%9A%84%E7%89%88%E6%9C%AC) in the folder. 
We did not support paddle 2.0 when we develop the course. So you should install the required versions of parl and paddle.
