### ISSUE TITLE
PARL采用pytorch做后端 有例子么？

### ISSUE THREAD

**Issue by xmgfx** [PaddlePaddle/PARL#717]
**全框架兼容¶
PARL的并行可以兼容目前市场上的任何深度学习框架，比如tensorflow、pytorch、mxnet等。通过增加并行修饰符 @parl.remote_class ，用户就可以把他们之前的代码转换成并行代码**

现有代码是pytorch的，想直接用PARL框架直接并行

**Comment by TomorrowIsAnOtherDay** [comment]
可以参考下torch的A2C实现。
https://github.com/PaddlePaddle/PARL/tree/develop/benchmark/torch/a2c
