### ISSUE TITLE
请问xparl start命令是在哪运行的？  我是WIN10系统，CMD中提示没有此命令？

### ISSUE THREAD

**Issue by yglpyn8888** [PaddlePaddle/PARL#720]
请问xparl start命令是在哪运行的？  我是WIN10系统，CMD中提示没有此命令？

**Comment by TomorrowIsAnOtherDay** [comment]
安装好parl之后就会有的，注意下Windows系统仅支持python3.6+的版本。

**Comment by yglpyn8888** [comment]
老师， 我parl装了2.02的  py=3.7.1 win10x64 在CMD和pycharm终端里都找不到xparl命令啊

**Comment by TomorrowIsAnOtherDay** [comment]
那现在python里面能import parl吗？看起来像是是你的安装有问题或者使用的python路径不对。

**Comment by yglpyn8888** [comment]
可以import 

Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
import parl
[10-04 21:03:55 MainThread @utils.py:73] paddlepaddle version: 2.1.1.

C:\Users\Y\Documents\code\superduo>xparl
'xparl' 不是内部或外部命令，也不是可运行的程序
或批处理文件。


安装的话直接pip install的 。 路径方面的问题我应该怎么核查呢？ 谢谢！

**Comment by TomorrowIsAnOtherDay** [comment]
抱歉，国庆节期间回复不及时。问下你现在使用的是原生python安装吗？建议使用anaconda进行安装

**Comment by yglpyn8888** [comment]
不是原生也不是anaconda 用的vnconda  什么叫用anaconda进行安装呢？ 我现在把PARL卸载了重新用pip安装一下可以吗？
