### ISSUE TITLE
PARL能否增加D3QN 和discretePPO算法？

### ISSUE THREAD

**Issue by yglpyn8888** [PaddlePaddle/PARL#721]
目前的场景动作空间为离散，所以需要上述两算法来跑，，看了PARL好像还没实现这两个？ 能不能安排版本实现呢？谢谢！

**Comment by TomorrowIsAnOtherDay** [comment]
谢谢你的反馈，我们近期的计划是提供离线强化学习相关的算法，关于你的建议，我们内部讨论下再决定的：）
