### ISSUE TITLE
建议基于parl 2.0版重新录制强化学习的课程

### ISSUE THREAD

**Issue by amocken** [PaddlePaddle/PARL#723]
现在的那个飞桨的强化学习课程所用的代码不太适用于parl 2.0版。或者出一个文字教程也行

**Comment by TomorrowIsAnOtherDay** [comment]
十分感谢反馈：）我们很早之前就注意到这个问题，公开课直播的时候是基于PARL的1.X版本，当下PARL2.0是基于动态图的。
为了缓解这个问题，我们特意在课程配套的文件夹里面新增了readme说明，以及强制限定了运行代码时候对应的PARL版本。

关于您的建议，我们与科老师商量下。

**Comment by amocken** [comment]
> 

如果要重新录制的画建议再讲一下MADDPG算法和SAC算法

**Comment by TomorrowIsAnOtherDay** [comment]
感谢您的反馈：）目前已经提供了动态图版本的代码，关于新版本的课程制作，目前是待定状态，还请继续关注我们。
