### ISSUE TITLE
首页最后一张四旋翼的环境是什么

### ISSUE THREAD

**Issue by mumuyanyan** [PaddlePaddle/PARL#727]
你好，请问首页最后一张图的四旋翼仿真环境是什么？
<img width="862" alt="截屏2021-10-16 下午7 27 57" src="https://user-images.githubusercontent.com/13342178/137585680-ab75c44a-71e6-497e-9eb6-ae6476f326ae.png">

**Comment by mumuyanyan** [comment]
what is the environment of the last graph of the project?

**Comment by TomorrowIsAnOtherDay** [comment]
It's our work in 2018 that leverages expert intervention for safe reinforcement learning. It was accepted by CoRL: https://arxiv.org/abs/1811.06187.

**Comment by TomorrowIsAnOtherDay** [comment]
We tested the proposed algorithm in Gazebo + Ros simulator.

**Comment by mumuyanyan** [comment]
> We tested the proposed algorithm in Gazebo + Ros simulator.
thanks

**Comment by mumuyanyan** [comment]
> We tested the proposed algorithm in Gazebo + Ros simulator.

thanks
