### ISSUE TITLE
It seems that the tutorial in the document for PARL is not compatible for the recent PARL version

### ISSUE THREAD

**Issue by Sensenzhl** [PaddlePaddle/PARL#729]
I read the tutorial and tried to implement the _Cartpole_  game on BML platform.

However, the compiler told me that I have to state the function of _**build_program**_ or the PARL kernel did not work.

Is the version of PARL has been updated so that an additional function needs to be stated?

This problem can be referred in the snapshot below.

![Screenshot 2021-10-24 at 10 56 23 PM](https://user-images.githubusercontent.com/25093984/138599662-6b92ca80-3090-48a4-969f-00fdf2f06df0.png)

Although there might be some imperfection, I think it doesn't effect that this is an  brilliant project.

**Comment by TomorrowIsAnOtherDay** [comment]
Hi, @Sensenzhl , thanks for your feedback!
It seems that you have installed an older version of paddlepaddle.
Please follow the instruction in [readme](https://github.com/PaddlePaddle/PARL#dependencies) and install the paddle >=2.0.

**Comment by Sensenzhl** [comment]
Thanks Zhou @TomorrowIsAnOtherDay.
I have updated the version of paddle for CUDA 10.1 while it seems that it doesn't work. 
Same ERROR that requests me to state the function of **_build_program_**.

**Comment by TomorrowIsAnOtherDay** [comment]
Could you check the version of your paddle by running the following command ?
```shell
pip list |grep paddle
```

**Comment by Sensenzhl** [comment]
![image](https://user-images.githubusercontent.com/25093984/138637695-7461acda-4792-4bc1-a05f-031e051a6414.png)

Is this version OK?
Thanks

**Comment by TomorrowIsAnOtherDay** [comment]
Good. Can you provide the parl version in your  environment? 
```shell
pip list |grep parl
```

**Comment by Sensenzhl** [comment]
![image](https://user-images.githubusercontent.com/25093984/138645200-bfdca9d9-3a97-4cd2-adfa-0659b3fe40e1.png)

I try to define an empty function of **_build_program_** like _def build_program: pass_.  While this time, it reports some fetch problems in the file /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py like the following snapshot
![image](https://user-images.githubusercontent.com/25093984/138645593-317e396d-00de-4a02-bd18-f595c418f623.png)

**Comment by TomorrowIsAnOtherDay** [comment]
Oh, got it. You should install the newest PARL.
PARL 1.XXX is not compatible with paddle 2.0.

**Comment by Sensenzhl** [comment]
Cool! It works. 
Thanks.

**Comment by Sensenzhl** [comment]
One more question:

Does **_BML_** notebook platform support the display functions such as _env.render()_ in OpenAI Gym for PARL?

It means that can I use fake screen to get videos about what happens in the gym game or my own game?

Since users are not authorized to access the root of **_BML_** notebook platform and GPU backstage, how can I configure so that I can see the video.

**Comment by TomorrowIsAnOtherDay** [comment]
Sorry. The BML platform **does not** support the `render()` function since it is a remote server without any display device.
You can run the function in your local machine to check the performance of the model trained in BML.
