### ISSUE TITLE
初始奖励定义

### ISSUE THREAD

**Issue by styledyy** [PaddlePaddle/PARL#740]
请问，初始时刻，每个格子对应的奖励在哪里定义的？

**Comment by TomorrowIsAnOtherDay** [comment]
hello，我们格子环境是基于openai-gym 提供的`frozen_lake`环境，相关reward的信息可以在这份代码中找到：
https://github.com/openai/gym/blob/103b7633f564a60062a25cc640ed1e189e99ddb7/gym/envs/toy_text/frozen_lake.py#L89
