### ISSUE TITLE
希望提供一个类似于export_model脚本这样支持导出 inference 模型用于部署推理场景

### ISSUE THREAD

**Issue by csy0225** [PaddlePaddle/PARL#743]
静态图用 static.save_inference_model
动态图用 jit.save
可以参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/02_paddle2.0_develop/08_model_save_load_cn.html#dongtaitumoxing-canshubaocunzairu-xunliantuili

**Comment by TomorrowIsAnOtherDay** [comment]
收到，我们提供下

**Comment by csy0225** [comment]
你好，这个如果有进展，可以更新一下哈~

**Comment by TomorrowIsAnOtherDay** [comment]
PR 已发，#745，添加单元测试代码中。

**Comment by TomorrowIsAnOtherDay** [comment]
已合入
