### ISSUE TITLE
离线强化学习

### ISSUE THREAD

**Issue by lguowang** [PaddlePaddle/PARL#746]
你好，我现在在做一个工业控制项目，想用强化学习去做控制决策，但只有设备运行数据的日志，没有办法去模拟真实的运行环境，请问又什么好的方法推荐吗？

**Comment by TomorrowIsAnOtherDay** [comment]
可以使用我们的离线强化学习算法尝试下，最近开发完成，review 修改后就可以合并到主干了 #744

**Comment by lguowang** [comment]
> 可以使用我们的离线强化学习算法尝试下，最近开发完成，review 修改后就可以合并到主干了 #744


大概什么时候可以合并到主干  # # @TomorrowIsAnOtherDay

**Comment by TomorrowIsAnOtherDay** [comment]
预计下周的。如果着急使用的话，可以使用如下方式安装:
```shell
git clone https://github.com/Jiukaishi/PARL
cd PARL 
pip install .
```
具体的使用方式可以查下如下页面：
https://github.com/Jiukaishi/PARL/tree/develop/examples/CQL

**Comment by styledyy** [comment]
你好，我最近也在做一个和你类似的项目，可以加我QQ:2751168686一起探讨一下吗？或者微信：13156726563

**Comment by forrestneo** [comment]
可以用revive这个框架生成离线环境，然后再用parl这个框架去做算法部分
