### ISSUE TITLE
No registered env with id: Pong-v0

### ISSUE THREAD

**Issue by styledyy** [PaddlePaddle/PARL#747]
环境：Python3.8，paddlepaddle==1.8.5，parl==1.4.1，gym==0.21.0
gym.error.UnregisteredEnv: No registered env with id: Pong-v0请问如何解决？

**Comment by TomorrowIsAnOtherDay** [comment]
hello，我们的环境要求里面还有atari-py的，缺少这个依赖是无法跑起来的。
https://github.com/PaddlePaddle/PARL/tree/develop/examples/DQN_variant#dependencies
