### ISSUE TITLE
env.py

### ISSUE THREAD

**Issue by styledyy** [PaddlePaddle/PARL#748]
我在运行train.py时报了这个错误，这是env.py中的 def step(self, action)
line 91, in step
    assert self.action_space.contains(action), \
AssertionError: array([-0.03169392]) (<class 'numpy.ndarray'>) invalid
请问这是什么原因？

**Comment by TomorrowIsAnOtherDay** [comment]
这是运行哪份代码呢？ 基本上每个example都有train.py 0.0
