### ISSUE TITLE
如果用NES模拟器，玩超级马里奥，如何配置环境

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PARL#749]
PARL感觉还不能脱离gym的环境
自己的游戏搭建gym太费劲了

PARL 有没 模拟学习的
可以识别这个NES模拟器的画面和按键来训练
然后预测的时候 通过界面来操作键盘来操作

```
# VirtuaNES 
# https://www.emulator-zone.com/doc.php/nes/virtuanes.html

# Super Mario Bros ROM
# https://wowroms.com/en/roms/nintendo-entertainment-system/download-super-mario-bros./23755.html
```
<img width="365" alt="1111111111111111" src="https://user-images.githubusercontent.com/6490927/141612947-6b361d4b-1a5f-4a29-9f7a-b233ec319c0f.png">

**Comment by TomorrowIsAnOtherDay** [comment]
目前没有，PARL 毕竟还是面向大众提供算法的稳定复现以及高性能并行，提升调研效率为主。像你这种场景专门针对自己游戏的，可以参考B站上的一些案例，有些同学用强化学习玩只狼，他们也是自己识别图像和自定义按键映射的。

**Comment by monkeycc** [comment]
B站都是用其他框架实现，不是用PARL

用PARL的 基本上没
有也是依赖于GYM环境

建议增加这类 脱离GYM环境的教程 
创建PARL自己环境也行

而不是只能在OpenAI Gym环境中实现
脱离这个OpenAI Gym环境，什么都干不了

**Comment by TomorrowIsAnOtherDay** [comment]
Gym不是环境，而是一个通用的强化学习接口，强化学习社区统一使用这个接口是为了更好的迁移算法，而不是限制在Gym接口。
举个例子，我们最近参与的顶会赛事：能源调度。
它的传统调度方案和强化学习没任何关联，但是研究者们为了加速强化学习在这个领域的应用，主动用python封装了c++底层，并且用gym的接口方式统一对外提供。

**Comment by monkeycc** [comment]
谢谢

原来如此 学习了

所以如果用自己的游戏

看来 还是要对接GYM的接口了
