### ISSUE TITLE
如何训练NeurIPS 2020电网调度模型

### ISSUE THREAD

**Issue by Allvey** [PaddlePaddle/PARL#750]
请问我应该如何训练电网调度模型，在源码中没有找到相对应的训练代码，希望大佬能够指点

**Comment by TomorrowIsAnOtherDay** [comment]
训练代码目前没有开源，公司目前在能源调度上有商业化的布局，完整的代码不适合公开哈。
如需复现，请参考我们上半年被ECML/PKDD 2021 接收的工作。
https://arxiv.org/abs/2106.15200

**Comment by TomorrowIsAnOtherDay** [comment]
在论文复现过程中，有任何问题，欢迎提issue。
