### ISSUE TITLE
强化学习如何利用现有数据？

### ISSUE THREAD

**Issue by styledyy** [PaddlePaddle/PARL#751]
请问，如果我有一些原始的数据，想要用强行学习得到一个最佳策略方法，这些原始数据在强化学习哪里使用呢？放经验池里面还是环境里面？还是其他地方？

**Comment by TomorrowIsAnOtherDay** [comment]
你这个情况可以考虑使用离线强化学习的，可以参考 #746 的讨论。

**Comment by styledyy** [comment]
请问您们开发的离线强化学习算法合并到主干了吗？

**Comment by TomorrowIsAnOtherDay** [comment]
还没有的，开发的同学这几天休假回家了，暂时没有跟进这个线条。
可以先参考我们issue上的安装方法

**Comment by styledyy** [comment]
我还有一个一直比较迷惑的问题，假如说现在要用强化学习训练一个推送最优路线的模型，我需要自己用代码编一个环境env用来训练模型吗？

**Comment by TomorrowIsAnOtherDay** [comment]
能构造相对真实的模拟环境进行在线训练肯定是最好的选择。
但是这个选择成本比较高，这也就有了offline-RL 的出现：减少仿真器的构建成本或者绕开sim-to-real的问题。

**Comment by forrestneo** [comment]
我建议你可以参考下revive这个框架的实现方式，先做环境的生成，然后再用parl的算法
