### ISSUE TITLE
强化学习新手的几点小请求

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/PARL#755]
1.强化学习教程是用parl1写的代码，希望你们可以写一份parl2的代码，放在同样的教程项目中。要让你们重新录制一个内容差不多的parl2视频，估计你们一时半会也不会做的，那就弄份代码吧，各位大佬，这个请求对你们来说应该就是一天的精力而已吧。写几个代码比录视频容易多了吧，大佬们。parl我不清楚，但是paddlex，clas等等，他们的动态图版本，代码量比起静态图版本少了非常多，这非常有助于学者入门。说白了，动态图最牛逼的点还是在于进一步封装，代码量非常少，对新手非常友好。还有个叫做雨哥的大佬出过相关视频教程，让很多人知道了动态图封装性大幅提高。
2.谁都知道强化学习兴起，引起世界学者研究热潮一个很重要的时间点就是谷歌的阿尔法狗打败几个顶尖围棋的人类。现在最牛逼的棋类引擎主要是两种算法，一种是nnue+AB剪枝，一种是强化深度学习训练一个网络+mcts。围棋就属卡塔狗引擎最牛逼，有人把他改成五子棋，跳棋等各种棋类，五子棋使用2060训练一天，棋力就超过AB剪枝作者多年的心血。而且听说卡塔狗的算法比起阿尔法zero效率提高百倍以上，也就是相同训练时间，棋力 大幅提高。另一点，有人把卡塔狗改编成五子棋等其他棋类，基本只是改游戏规则，并不复杂，也是效果超群，希望你们可以研究下卡塔狗的论文和代码，引入他的算法，我相信，他的算法是很牛逼的，而且是经过实践证明的了。他的算法绝对不仅仅只能用于棋类，从五子棋引擎作者改编卡塔狗围棋引擎，并且效果超群就能看出来，这个强化学习算法泛化能力极强，而且效率，性能都非常牛逼，这才是你们应该优先引入的算法，毕竟这是世界第一的算法，通过实践证明了的。谷歌多少人研究相关算法，还不如一个小团队，这种算法不应该尽早引入我们的parl库吗？各位大佬们，可能这个请求比较耗费时间精力，跪求。要是有个算法，定义好规则，奖励机制，就可以在极短训练量情况下得到很牛逼的性能，这是强化学习梦寐以求的终极算法吧。据我所知，围棋引擎改编成五子棋引擎，主要也是修改规则而已，算法部分，无论是mcts，还是神经网络部分，都没有一丝改动，你们要是封装这个算法，让我们只需要定义一个规则，结果就很牛逼，那就爽歪歪了。

**Comment by yuwoyizhan** [comment]
还有一个建议，我不知道各位大佬是如何评估一个算法的好坏的，我建议可以用20*20无禁五子棋作为研究对象。算法在相同训练量下性能如何？算法经过充分训练，能否成为超人算法？算法是否在训练量不大情况下就超过人类顶尖水准。无禁五子棋非常简单，无论是状态，可行动作，胜负和判断，比起围棋容易得多，围棋那个胜负和判断，还有在状态下选择哪个动作就比五子棋难多了，AB剪枝的围棋引擎多年来无法取得突破，无法战胜人类顶尖棋手，根本原因就在于评估函数太难写了。一个位置属于黑的势力范围还是白的势力范围，这点极难判断。而且20*20无禁五子棋的复杂度也是很高的了，完全可以用于评估算法了。关于上面的第2个建议，真心希望有一天可以一个算法走天下，我只需要定义游戏规则，其他什么事情都不用做，一天跑下来，引擎牛逼哄哄，哈哈哈哈。据我所知，围棋引擎改成五子棋后，就变成了只需要改规则就能轻轻松松成为其他棋类的牛逼算法了，包括六子棋，你们教程里的重力四子棋，跳棋，象棋等等。卡塔狗那个算法泛化能力实在牛逼哄哄，效率牛逼哄哄，性能牛逼哄哄。三大牛逼哄哄。

**Comment by forrestneo** [comment]
部分同意，确实paddle2的部分需要补课

**Comment by TomorrowIsAnOtherDay** [comment]
Hello, @yuwoyizhan ，十分感谢你对于咱们仓库/课程的关注以及建议，我逐个回复下你的建议。

#### 关于动态图配套课程

我们在今年升级为2.0后，已经关注到这个问题，之前团队也讨论过备选的解决方案：

- 制作进阶版的动态图课程
- 替换课程中的静态图代码讲解：重新录制视频，剪辑后发布
- 提供PARL 2.0的动态图代码（如你所建议的）

短期内我们先采取第三个方案，先提供代码。接下来就是方案一和二的取舍了，方案一的制作周期长，科老师花费了整整一个季度+一个月的时间来制作课程。方案二的周期相对短，目前更倾向于方案二。

#### 关于围棋算法

我们目前是有提供alphazero 这一算法的，[参考链接](https://github.com/PaddlePaddle/PARL/tree/develop/examples/AlphaZero)。至于你提到的“三大牛逼哄哄”算法，不在我们的计划中。目前我们的精力更多是放在社区关注度更高的领域中，比如离线强化学习、多智能体强化学习等。并行框架的进一步升级也是我们在准备的事情。

**Comment by yuwoyizhan** [comment]
请问一下，你说的打算采取第三个方案，几时才能完全生效，看到视频涉及的所有代码呢？有具体时间吗？代码可以放在教程里面吗？

**Comment by TomorrowIsAnOtherDay** [comment]
所有tutorial下涉及paddle的代码都会升级。关于时间的问题，刚与科老师确认了下，预计本周内搞定。科老师最近还在忙着做一些idea的验证实验，只能抽时间升级代码了。

**Comment by TomorrowIsAnOtherDay** [comment]
动态图版本代码已经同步到仓库，请见[路径](https://github.com/PaddlePaddle/PARL/tree/develop/examples/tutorials/parl2_dygraph)。
感谢科老师的升级：）
