### ISSUE TITLE
lesson5代码运行报错，求大佬帮忙解决

### ISSUE THREAD

**Issue by qq104836** [PaddlePaddle/PARL#756]
在python3.6环境安装了parl1.4版本和paddlepaddle1.6.3版本，然后跑lesson5代码出错，具体报错内容为AssertionError: array([-0.00309599]) (<class 'numpy.ndarray'>) invalid，还有 DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.for plugin in metadata.entry_points().get(entry_point, []):还有"Box bound precision lowered by casting to {}".format(self.dtype)，这些错误不知道怎么更改，求大佬帮帮忙。前四个lesson代码都能跑。

**Comment by TomorrowIsAnOtherDay** [comment]
hello，请问能提供下完整的报错信息吗？目前的信息看不到是哪一行代码出错了。

**Comment by qq104836** [comment]
就是这个错误，该怎么解决，照片在附件


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PARL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月30日(星期二) 晚上8:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PARL] lesson5代码运行报错，求大佬帮忙解决 (Issue #756)





 
hello，请问能提供下完整的报错信息吗？目前的信息看不到是哪一行代码出错了。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by TomorrowIsAnOtherDay** [comment]
你是通过邮件回复的吗？GitHub网页上没有看到邮件。

**Comment by qq104836** [comment]
对的，github上我不知道怎么发图片，于是就用邮箱回复了，截图在附件里




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PARL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月1日(星期三) 上午9:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PARL] lesson5代码运行报错，求大佬帮忙解决 (Issue #756)





 
你是通过邮件回复的吗？GitHub网页上没有看到邮件。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by TomorrowIsAnOtherDay** [comment]
这种回复方式是看不到附件的...

**Comment by qq104836** [comment]
那怎么才能把截图发给你们呢？你们有交流群吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PARL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月1日(星期三) 中午11:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PARL] lesson5代码运行报错，求大佬帮忙解决 (Issue #756)





 
这种回复方式是看不到附件的...
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by TomorrowIsAnOtherDay** [comment]
目前没有在运营交流群了，在GitHub【网页】上直接把图片拉到回复框即可的。

**Comment by qq104836** [comment]
![53b020f662be2922b2810bf3a317b0b](https://user-images.githubusercontent.com/74463593/144167360-f34d1833-bdee-40de-a109-06411385567e.png)

**Comment by qq104836** [comment]
。。。原来可以这样啊

**Comment by TomorrowIsAnOtherDay** [comment]
囧，你才发现啊

---------------

问下你的gym版本是多少呢？

**Comment by qq104836** [comment]
![ff9da964faf6ae2460afbf5b292300f](https://user-images.githubusercontent.com/74463593/144167547-7593453f-d072-4862-b086-bcb428bb4620.png)

**Comment by qq104836** [comment]
![image](https://user-images.githubusercontent.com/74463593/144167618-03b432e2-8776-4d46-bc16-222f3726c5d7.png)

**Comment by TomorrowIsAnOtherDay** [comment]
gym尝试下安装旧版本：0.18.0

**Comment by TomorrowIsAnOtherDay** [comment]
B站上也有很多反馈是gym版本的问题，我们会更新readme上的gym版本安装指引。

十分感谢您的反馈：）

**Comment by qq104836** [comment]
![image](https://user-images.githubusercontent.com/74463593/144168067-3765d148-6fb1-4e65-a5e4-3f4b168fe8f7.png)

**Comment by qq104836** [comment]
![image](https://user-images.githubusercontent.com/74463593/144168098-0ca288df-84b5-4660-9797-5cc8c9db3a26.png)

**Comment by qq104836** [comment]
不太会装

**Comment by TomorrowIsAnOtherDay** [comment]
查看下这个：https://stackoverflow.com/questions/66642705/why-requests-raise-this-exception-check-hostname-requires-server-hostname

解决方案:
```shell
pip install urllib3==1.25.11
pip install gym==0.18.0
```

**Comment by qq104836** [comment]
我把VPN关了就能安装了。。。代码已经可以跑了，lesson5的代码运行是没有图的吗，底下已经有结果了，但是没有动图

**Comment by TomorrowIsAnOtherDay** [comment]
默认是没有可视化界面的，你得跑`env.render()`才可以

**Comment by TomorrowIsAnOtherDay** [comment]
已经新增版本限制，感谢反馈：） #757
