### ISSUE TITLE
运行xparl并行使用教程时报错

### ISSUE THREAD

**Issue by ZanliangD** [PaddlePaddle/PARL#758]
![1638361881](https://user-images.githubusercontent.com/58019587/144234937-226bbdcf-fbe1-45e1-b38b-a7ec913bbeba.png)
按照教程运行以上并行程序时报错如下：
![1638361973(1)](https://user-images.githubusercontent.com/58019587/144235055-af0c162b-f823-4d4a-81ad-708368d35bf1.png)
不明白哪里出问题了，恳请指教。
另外还有一个问题是master node在Windows上，是否无法加入mac os的CPU资源，因为我尝试了xparl connect命令也不成功，我检查了master地址没问题。

**Comment by TomorrowIsAnOtherDay** [comment]
十分感谢你的反馈：）
请提供下你的环境信息：

- 系统版本
- python 版本
- parl版本

**Comment by TomorrowIsAnOtherDay** [comment]
由于原issue owner长时间未回复，先关闭该issue，欢迎随时reopen。

**Comment by ZanliangD** [comment]
不好意思看到的有点晚了
用的win10, python3.7, parl 2.0.2

**Comment by TomorrowIsAnOtherDay** [comment]
请问是使用conda安装的环境吗？

**Comment by ZanliangD** [comment]
是的
