### ISSUE TITLE
使用paddlepaddle可以求解旅行商问题吗？

### ISSUE THREAD

**Issue by qq104836** [PaddlePaddle/PARL#762]
使用paddlepaddle可以求解旅行商问题吗？如果可以，可以出个视频或者帖子教学一下吗，想知道怎么将机器学习应用到运筹学的问题上。

**Comment by TomorrowIsAnOtherDay** [comment]
可以求解的，我们在3年前调研过RL用于组合优化的问题，这个线条我们后面没有持续投入了。
建议参考论文：https://arxiv.org/abs/1611.09940

**Comment by TomorrowIsAnOtherDay** [comment]
当时有复现过这个工作，是可以达到作者提及的效果的。

**Comment by qq104836** [comment]
请问，有代码吗？

**Comment by TomorrowIsAnOtherDay** [comment]
年代有点久远了，没法找到（sad）。而且当时是使用静态图版本的paddle写的。

**Comment by qq104836** [comment]
那用新版paddlepaddle也可以写吧，新版paddlepaddle的用法在哪？在官网吗？

**Comment by TomorrowIsAnOtherDay** [comment]
可以写的，paddle的使用请查看官网。
