### ISSUE TITLE
新手建议和提问

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/PARL#764]
1.parl更新速度有点慢，希望加快更新速度，6个月都未必更新一次。
2.parl针对AlphaZero的四子棋案例，似乎缺少一个kaggle数据集，可以补上吗？parl似乎没有针对AlphaZero的算法实现封装，DQN等算法好像都实现了一定程度的封装，能封装一下AlphaZero算法吗？
3.那个学习教程，从第三课开始就有神经网络了。使用的都是几层全链接神经网络，参数大，速度慢，拟合效果应该也不如CNN等网络。我想问下，现在使用parl做强化学习，那步骤是不是针对具体项目选择parl中的某种算法，比如DQN还是DDPG等，假设选择了DQN算法，那就根据你们提供的DQNdemo例子，进行一些代码更改，然后就可以跑训练和推理了？这个步骤对吗？还是说有更好的步骤？还有一点疑问，你们例子中使用的神经网络结构都比较简单，如果我使用相同算法，但是使用了比较牛逼的神经网络，比如使用ResNet101代替demo中的几层小网络，是不是效果会好很多？我的意思是，相同训练资源情况下，相同训练时间的话，ResNet等比较深比较大的网络，在多数例子中，是不是比起很小的网络，比如2层全连接网络，得分更高，loss更小。
4.我之前提议，那个教程做个动态图代码，我经过测试，基本没什么问题，但我觉得代码量不少啊。我以前看过雨哥的高层API教学，一个很吸引我的关键点就在于动态图比起静态图少了很多代码，我想问问，对于parl来说，使用动态图版本，代码量会少很多吗？我觉得你们的封装程度还可以大幅度提高。
5.刚入门parl不久，我想知道，我目前要是有一个任务，我该选择哪种算法。我想知道哪种算法是SOTA。你们说你们得到很多强化学习的冠军，用的是什么算法？什么神经网络呢？

**Comment by TomorrowIsAnOtherDay** [comment]
这两天在外地出差宣传新工作，抱歉回复晚了。关于你的问题，我逐个回复下。

- 目前在推进PARL 3.0的研发：全新的多智能体框架设计以及并行能力的进一步突破。这两项工作都非短期就可以研发完成的，频繁的低质量发版没意义，除了挣些吆喝。
- kaggle的数据集可以自行登陆kaggle官网下载，这个不建议放到仓库中，免得仓库过于臃肿，下载时间长。
- 对的，按照我们提供的example进行更改，适配到新的环境就可以跑训练和推理。第二个问题，Resnet这些复杂的网络在CV领域效果确实很好，在RL里面也是可以使用的。但是在Atari这个场景下，普通的CNN 模型就已经可以提取重要的特征并完成决策了，后面的SOTA算法也是类似的CNN结构。所以在Atari游戏上，没必要使用太过复杂的网络，可能会带来额外的训练成本（毕竟参数量、模型复杂度上升了）。
- 很感谢你的反馈以及对于我们动态图工作的认可。关于封装的便捷性和灵活性永远是一个trade-off，就好比tensorflow和keras，后者虽然代码量少，封装度高，但是灵活性显然不如原生的tensorflow。对于PARL的定位，肯定不是keras，因为强化学习领域需要经常适配不同的任务来单独训练，对灵活性要求是很高的。
- 我们的冠军方案以及代码都有开源，还有相关的paper，可自行查阅。

**Comment by yuwoyizhan** [comment]
1.您说的多智能体框架设计，指的是像王者荣耀，就10个智能体，并且互为合作体或者敌对体，还是像红色警戒，每个角色可以拥有几千甚至更多智能体呢？说到并行，指的是CPU并行还是GPU并行能力的提高，我认为对于多数人来说，目前能接触到的最高算力，基本就是百度的ai studio，除非租机，这个工作能否针对ai studio的16G，2线程和32G，4线程进行优化呢？
2.如果我有一项任务，有一大堆数据作为输入，数据维度比较高，我可以根据输入数据，得到一个可行的动作序列，但我没法用parl去跑这些动作进行，说白了，环境太过复杂，导致我无法模拟相关的环境。我只能提供一个不错的算法，根据输入的数据，来得到一个比较不错的动作，换句话说，我可以搞监督学习进行训练，因为我有了输入数据和最终选择的较好动作。我能否使用强化学习parl呢？如果可以，我应该使用哪个算法呢？这种任务是不是只能使用监督学习？
3.关于上面提到的第5点问题，我还是觉得您的回答太笼统了，这是官方回答啊。能否详细点说一下呢？

**Comment by yuwoyizhan** [comment]
@TomorrowIsAnOtherDay

**Comment by TomorrowIsAnOtherDay** [comment]
1. 多智能体的应用场景不仅仅适用于游戏AI。工业领域的能源调度、交通信号灯控制都可以的，比如多个发电站之间的协调，特别是在国家“双碳”的大背景下，如何在可再生能源比例上涨的情况下协调各个火力发电站显得尤为重要。我们针对的智能体数量从数十个到上万个不止，并不会针对特定的机器资源做优化，因为缺乏足够的机器资源无法解决复杂问题。
2. 这种情况，可以考虑模仿学习（behavior cloning），或者离线强化学习。
3. 你想了解的是如何选择算法对吧？我可以明确地说目前没有一种SOTA算法可以在各个场景通用的，至于选择的原则，我建议你了解和熟悉强化学习的主流算法后我们再来讨论：）
