### ISSUE TITLE
examples/tutorials/parl2_dygraph

### ISSUE THREAD

**Issue by xinzhao101** [PaddlePaddle/PARL#765]
动态图版本examples/tutorials/parl2_dygraph中lesson5运行时如下报错，求解决
assert self.action_space.contains(action), \
AssertionError: array([0.21840366]) (<class 'numpy.ndarray'>) invalid

**Comment by TomorrowIsAnOtherDay** [comment]
你好，请提供下相应的系统环境、python版本、parl/paddle版本等信息。

**Comment by xinzhao101** [comment]
mac pycharm ，python3.9 parl2.0.1 paddle2.2.0

**Comment by TomorrowIsAnOtherDay** [comment]
收到：）我们定位复现下问题。

**Comment by rical730** [comment]
gym版本呢？上一次我碰到这个问题还是在gym版本太高的时候（gym升级到0.21.0之后有一丢丢不向下兼容），按照readme里限制的那样用 `pip install gym==0.18.0` 重新安装gym后再跑跑看。

**Comment by xinzhao101** [comment]
换了 0.18.3后就可以了 感谢🙏

**Comment by TomorrowIsAnOtherDay** [comment]
> gym版本呢？上一次我碰到这个问题还是在gym版本太高的时候（gym升级到0.21.0之后有一丢丢不向下兼容），按照readme里限制的那样用 `pip install gym==0.18.0` 重新安装gym后再跑跑看。

目前动态图的实现中，没有限制gym 版本吗？

**Comment by rical730** [comment]
> 目前动态图的实现中，没有限制gym 版本吗？

有的，在这里
https://github.com/PaddlePaddle/PARL/blob/develop/examples/tutorials/parl2_dygraph/lesson5/ddpg/train.py#L23

可能这位同学把这几行限制给删了方便运行 0.0

**Comment by rical730** [comment]
问题已解决，我先关闭issue啦~ 有任何追加疑问都欢迎随时 reopen issue 来继续讨论。
