### ISSUE TITLE
parl2_dygraph/lesson5/homework 运行报错

### ISSUE THREAD

**Issue by xinzhao101** [PaddlePaddle/PARL#766]
parl2_dygraph/lesson5/homework 运行报错，求解决
raise Exception("rlschool.make_env is deprecated. Please do \"import rlschool.xxxenv\" and use gym.make instead")
Exception: rlschool.make_env is deprecated. Please do "import rlschool.xxxenv" and use gym.make instead

**Comment by TomorrowIsAnOtherDay** [comment]
请问你的rl_school是如何安装的呢？以及安装的对应版本是？

**Comment by xinzhao101** [comment]
用pycharm， 对应版本是1.0.3

**Comment by TomorrowIsAnOtherDay** [comment]
收到，感谢您的反馈：）

**Comment by rical730** [comment]
rlschool库的版本可以根据我们readme里提到的来哈：

pip install rlschool==0.3.1

**Comment by xinzhao101** [comment]
换 rlschool==0.3.1。
NSEventTrackingRunLoopMode = c_void_p.in_dll(appkit, 'NSEventTrackingRunLoopMode')
ValueError: dlsym(RTLD_DEFAULT, NSEventTrackingRunLoopMode): symbol not found

**Comment by xinzhao101** [comment]
换了之后还是报错
NSEventTrackingRunLoopMode = c_void_p.in_dll(appkit,'NSEventTrackingRunLoopMode')
ValueError: dlsym(RTLD_DEFAULT, NSEventTrackingRunLoopMode): symbol not found

**Comment by rical730** [comment]
请问您是在什么操作系统下运行代码的呢？我这边尝试在相同的环境下复现一下。

**Comment by xinzhao101** [comment]
macOS Big Sur 11.6.  用pycharm   gym0.18.3  rlshool 0.3.1    paddle和parl >2.0

**Comment by rical730** [comment]
我现在手头上没有MacOS Big Sur 系统的电脑，但我在PaddlePaddle/MetaGym仓库（前身是PaddlePaddle/RLSchool）的ISSUE中查到了类似的问题和解决方案：

from https://github.com/PaddlePaddle/MetaGym/issues/38

 > `ValueError: dlsym(RTLD_DEFAULT, NSEventTrackingRunLoopMode): symbol not found` 报错是由于Pyglet
1.5.0与big sur系统不兼容导致的，升级pyglet至最新1.5.15即可解决这个问题。


可以在您的电脑上尝试一下。

**Comment by xinzhao101** [comment]
可以了能运行了，感谢🙏，但是渲染画面好像出不来。

**Comment by rical730** [comment]
啊是报这个错吗？ `AttributeError: 'ActionMappingWrapper' object has no attribute 'render'` ，那是因为env被Wrapper封装了一层但是没有重写render接口。我这就提个PR补一下。

你可以在 `class ActionMappingWrapper` 下面多写一个接口

```
    def render(self):
        self.env.render()
```

**Comment by rical730** [comment]
可以参考这个PR https://github.com/PaddlePaddle/PARL/pull/768 ，设置 render=True 即可渲染。

**Comment by xinzhao101** [comment]
解决了，十分感谢！

**Comment by rical730** [comment]
PR已合入，现在下载最新代码就可以设置render=True来渲染啦，问题已解决，我先把issue关闭哈，有任何追加疑问可以随时 reopen
