### ISSUE TITLE
新手提问：飞浆AI Sdudio强化学习DQN的几点疑惑

### ISSUE THREAD

**Issue by yangluyi17** [PaddlePaddle/PARL#767]
这几天学习了科老师的百度强化学习课程，看到了DQN，有几点疑惑：

1. 视频中对倒立摆进行训练时，在训练效果展示的视频中，设置总episode为2000，但是当episode达到1800以后，test_reward反而没有之前好，科老师在视频中说“这种灾难性的结果是正常的”。 

自己很疑惑：为什么是正常的？是agent对环境探索得不够完全，所以导致学的模型不够好吗？虽然柯老师在视频中提到了不确定性，但是如果继续增加episode，test_reward会不会就不再发生这种“灾难性的结果”了？

如果无法避免这种“测试效果反而变差”的情况，那么确定最佳episode数，使得训练效果最好？

2. 自己的第2个问题是，如何确定DNQ中，Target_Q网络的网络层数和每一层网络的神经元个数？感觉在监督学习中，确定网络结构就需要花费很久时间调参。如果用网络来逼近Q表格，怎么能保证自己选择的网络是合适的呢？怎么才能知道自己训练的Target_Q网络，没有出现过拟合或者欠拟合的现象？

3. 自己的第3个问题是，在传统的表格型Q学习算法中，会不会出现第1个问题中的现象，训练效果随着episode增加反而下降？Q表格一定会收敛吗？

以上是自己的疑惑，还请各位老师百忙之中，不吝赐教！谢谢啦

**Comment by TomorrowIsAnOtherDay** [comment]
1. 请不用刻意关注特定的某个指标。强化学习本身训练过程中就有很大的不确定性，探索的时候如果一开始就探索到一个很不错的决策，那收敛速度就会很快。此外，由于用的是随机梯度下降法来更新模型，策略的更新也有不确定性。我建议初学者更多关注整体收敛趋势。关于效果的随机性，RL有别的方式来解决，不建议初学者过度关注。
2. 一般我们团队在做调研的时候，对于神经网络的制定，主要是根据问题的复杂程度来。对于初学者，我建议是参考paper或者已有的开源代码来设定即好。
3. Q表格的迭代算法必然收敛的，但是基于神经网络的收敛无法被证明。详细的理论推导可以查阅Neuro Dyamics Programming 这本书。

**Comment by yangluyi17** [comment]
> 1. 请不用刻意关注特定的某个指标。强化学习本身训练过程中就有很大的不确定性，探索的时候如果一开始就探索到一个很不错的决策，那收敛速度就会很快。此外，由于用的是随机梯度下降法来更新模型，策略的更新也有不确定性。我建议初学者更多关注整体收敛趋势。关于效果的随机性，RL有别的方式来解决，不建议初学者过度关注。
> 2. 一般我们团队在做调研的时候，对于神经网络的制定，主要是根据问题的复杂程度来。对于初学者，我建议是参考paper或者已有的开源代码来设定即好。
> 3. Q表格的迭代算法必然收敛的，但是基于神经网络的收敛无法被证明。详细的理论推导可以查阅Neuro Dyamics Programming 这本书。

> 

谢谢老师的解答！自己还想请教下，对于效果的随机性，老师提到“RL有别的方法”。请问这些别的方法大概有哪些？老师能否指一下路或者方向？

自己准备这段时间，花精力消化完RL入门课程后，再结合一些具体的方向进行深入研究，所以想先了解一下。

谢谢老师了！

**Comment by TomorrowIsAnOtherDay** [comment]
一是采用on-policy的SOTA 算法，比如PPO。在控制算法上，on-policy 算法相比off-policy 的bootstrap 更新方式更加鲁棒，目前机器人控制领域用的挺多的。
二是采用ensemble 的方式，即同时训练多个actor-critic 模型。先输出不同actor的action，然后以critic投票的方式选出最合适的action。具体可以参照我们18/19年NIPS 夺冠的开源工作。

也欢迎点个star 关注下我们仓库：）

**Comment by yangluyi17** [comment]
> 一是采用on-policy的SOTA 算法，比如PPO。在控制算法上，on-policy 算法相比off-policy 的bootstrap 更新方式更加鲁棒，目前机器人控制领域用的挺多的。 二是采用ensemble 的方式，即同时训练多个actor-critic 模型。先输出不同actor的action，然后以critic投票的方式选出最合适的action。具体可以参照我们18/19年NIPS 夺冠的开源工作。
> 
> 也欢迎点个star 关注下我们仓库：）

好的，谢谢老师！已点star关注
