### ISSUE TITLE
请问 PARL 动态图版本的 代码，源码除了 dqn、policy_gradient、ddqn之外，还有完成其他的可以学习嘛

### ISSUE THREAD

**Issue by A5230171** [PaddlePaddle/PARL#769]
https://github.com/PaddlePaddle/PARL/tree/develop/examples/tutorials/parl2_dygraph

上诉的链接，是之前在issues上，有看到，那请问一下，还有其他的算法嘛？

**Comment by TomorrowIsAnOtherDay** [comment]
其他的动态图算法都可以在这个[目录](https://github.com/PaddlePaddle/PARL/tree/develop/examples) 找到。
