### ISSUE TITLE
一些小疑问

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/PARL#770]
1.教程中，训练是不是基本都是输入图片，让算法训练，然后输出某个动作呢？
2.您说的离线强化学习，还有模仿学习，上线了吗？在哪里可以看到相关例子呢？离线强化学习目前有什么算法呢？你们实现了哪些算法？目前的SOTA算法是什么？我对于这个东西比较感兴趣。第一次接触强化学习，我一直以为必须有动作才能进行强化学习，可我做的项目，很多是动作极难实现，甚至根本无法实现动作，我想离线强化学习或许对我的工作很有帮助。我是做应用方向的，不是算法方向的，我希望知道离线强化学习，你们做了几个算法，分别有哪个例子，让我改改代码就可以用于我的工作中。
3.pytorch，tensorflow都是非常支持C++的，parl对于C++来说，支持效果好吗？如果目前支持效果不好，你们打算完善这方面吗？对于paddlex来说，无论是图像分类，目标检测，语义分割，实例分割，目前都可以做到0python代码应用，python代码用相关教程中的代码就可以了，改改batch，epochs，lr等几个重要参数，就可以训练出很不错的模型。部署方面也可以做到无需自己编写代码，无论是python部署，还是C++部署。可是对于强化学习来说，预测前的所有步骤，比如训练的所有相关定义，不可能全部用你们例子代码改吧，就想问问，我要是用parl做一个项目，能不能从头到尾用C++来编写代码，本地VS2022IDE？

**Comment by TomorrowIsAnOtherDay** [comment]
1. 教程中也有相当部分的非图像输入案例，比如cartpole、无人机控制，都是浮点数输入的。
2. 模仿学习和传统的监督训练类似，与强化学习训练方式还是有较大的差异的，所以我们没有提供在仓库中。离线强化学习目前已经实现好了，还在调参数对齐paper的指标，进展可以看这里: #744
3. 目前市面上，强化学习领域没有一个软件可以做到界面化操作就可以完成训练和部署的。cv领域的任务是十分明确的：给你一张图片，完成分类、分割等任务。强化学习领域因为适用的场景很多，而且每个场景的状态、奖励设置不一样，没法整合成统一的训练方案。关于c++部署这块，可以使用parl训练，导出模型后使用paddle-inference来进行推理和部署。
