### ISSUE TITLE
from parl import layers 和 import paddle.nn as nn怎么实现转换

### ISSUE THREAD

**Issue by chlyzzo** [PaddlePaddle/PARL#771]
我在跑如下代码时，发现from parl import layers出错，parl没有layers；
https://github.com/PaddlePaddle/PARL/blob/develop/examples/tutorials/lesson4/policy_gradient/model.py

查看其他比如dqn，发现用的是 import paddle.nn as nn；请问这两个如何实现转换呢？
parl用的是2.0.2版本，paddlepaddle          2.2.1

**Comment by TomorrowIsAnOtherDay** [comment]
https://github.com/PaddlePaddle/PARL/blob/e3da05d4f490312308e08b7bd0f0384a4502468b/examples/tutorials/lesson4/policy_gradient/train.py#L21
我们的初版课程是基于静态图的，已经限定了paddle版本是1.6的。
请使用对应版本的paddle哈，或者运行我们最近更新的动态图教程代码：
https://github.com/PaddlePaddle/PARL/tree/develop/examples/tutorials/parl2_dygraph
