### ISSUE TITLE
使用DQN代码运行的时候出现了问题

### ISSUE THREAD

**Issue by ShenAoChen2001** [PaddlePaddle/PARL#773]
Traceback (most recent call last):
  File "C:/Users/14760/Desktop/rlrl/DQN/train.py", line 122, in <module>
    main()
  File "C:/Users/14760/Desktop/rlrl/DQN/train.py", line 118, in main
    agent.save_inference_model(save_inference_path, input_shapes, input_dtypes)
AttributeError: 'CartpoleAgent' object has no attribute 'save_inference_model'

**Comment by TomorrowIsAnOtherDay** [comment]
hello，请提供下你的parl版本以及paddle版本。

**Comment by ShenAoChen2001** [comment]
paddlepaddle-gpu=2.2.1parl=2.0.2




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Bo ***@***.***&gt;; 
发送时间: 2021年12月29日(星期三) 下午4:56
收件人: ***@***.***&gt;; 
抄送: "(12N15L24) ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PARL] 使用DQN代码运行的时候出现了问题 (Issue #773)





 
hello，请提供下你的parl版本以及paddle版本。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by TomorrowIsAnOtherDay** [comment]
了解了，十分感谢反馈。这个问题我们马上修复，目前请先通过直接安装GitHub上最新的parl来解决该问题。
```shell
git clone https://github.com/PaddlePaddle/PARL
cd PARL
pip install .
```

**Comment by ShenAoChen2001** [comment]
sorry，我是windows系统，请问我该如何操作




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Bo ***@***.***&gt;; 
发送时间: 2021年12月30日(星期四) 上午9:33
收件人: ***@***.***&gt;; 
抄送: "(12N15L24) ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PARL] 使用DQN代码运行的时候出现了问题 (Issue #773)





 
了解了，十分感谢反馈。这个问题我们马上修复，目前请先通过直接安装GitHub上最新的parl来解决该问题。
 git clone https://github.com/PaddlePaddle/PARL cd PARL pip install .
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rical730** [comment]
也可以先把train.py的第118行注释掉或者删掉

**Comment by ShenAoChen2001** [comment]
thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月30日(星期四) 上午10:32
收件人: ***@***.***&gt;; 
抄送: "(12N15L24) ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PARL] 使用DQN代码运行的时候出现了问题 (Issue #773)





 
也可以先把train.py的第118行注释掉或者删掉
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rical730** [comment]
https://github.com/PaddlePaddle/PARL/blob/develop/examples/DQN/train.py#L118

这一行的save_inference_model()接口是我们在最新的develop分支增加的，所以现有的发版还不支持这个接口

**Comment by ShenAoChen2001** [comment]
对了，我刚刚把parl2.02删了，下了个parl2.0.0，然后它又报错显示：AttributeError: 'CartpoleModel' object has no attribute 'value'



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月30日(星期四) 上午10:32
收件人: ***@***.***&gt;; 
抄送: "(12N15L24) ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PARL] 使用DQN代码运行的时候出现了问题 (Issue #773)





 
也可以先把train.py的第118行注释掉或者删掉
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ShenAoChen2001** [comment]
嗯嗯，谢谢你




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月30日(星期四) 上午10:34
收件人: ***@***.***&gt;; 
抄送: "(12N15L24) ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PARL] 使用DQN代码运行的时候出现了问题 (Issue #773)





 
https://github.com/PaddlePaddle/PARL/blob/develop/examples/DQN/train.py#L118
 
这一行的save_inference_model()接口是我们在最新的develop分支增加的，所以现有的发版还不支持这个接口
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rical730** [comment]
> 对了，我刚刚把parl2.02删了，下了个parl2.0.0，然后它又报错显示：AttributeError: 'CartpoleModel' object has no attribute 'value'
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年12月30日(星期四) 上午10:32 收件人: ***@***.***&gt;; 抄送: "(12N15L24) ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [PaddlePaddle/PARL] 使用DQN代码运行的时候出现了问题 (Issue #773) 也可以先把train.py的第118行注释掉或者删掉 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


是的，我们的example都是适配最新的版本，所以尽可能的还是推荐大家安装最新版PARL
