### ISSUE TITLE
弱弱的问一句

### ISSUE THREAD

**Issue by fly2008begin** [PaddlePaddle/PARL#774]
你们首页的https://github.com/PaddlePaddle/PARL/Readme.md 中那个小飞机是啥？是有比赛还是啥？如果是它也是强化学习训练的操作的？那这种模拟环境要怎么搭建？

**Comment by TomorrowIsAnOtherDay** [comment]
hello，这是我们18年做的强化学习应用于无人机的工作，详情可以参考我们发表的[文章](https://arxiv.org/pdf/1811.06187.pdf)。
模拟环境使用的是gazebo + ros 。

**Comment by fly2008begin** [comment]
> hello，这是我们18年做的强化学习应用于无人机的工作，详情可以参考我们发表的[文章](https://arxiv.org/pdf/1811.06187.pdf)。 模拟环境使用的是gazebo + ros 。

thx
