### ISSUE TITLE
刷POJ、LeetCode(半人工半智能)的baseline已出

### ISSUE THREAD

**Issue by kosoraYintai** [PaddlePaddle/PARL#78]
经过N次的超参数调整，使用Rainbow（Double-Q + SegmentTree + Advantage）解决八数码问题的模型终于训练完毕。在不知道如何搜索最优解的情况下，根据reward的返回信息，从0开始训练，并自动生成了打表代码。没想到的是，居然冲到了LeetCode的Top1，成为了默认的submission！(虽然本地使用A*算法对拍正确率为98.6%，但并不影响AC，呵呵)
![top1](https://user-images.githubusercontent.com/31379401/58743064-6dc59100-845d-11e9-8daf-cdd6d842c7db.jpg)
所以，困扰我三年以上的一系列问题终于解决：
1、不少知乎大V认为：有了机器学习算法之后，传统《算法导论》了解即可，不需要精读，两者联系不大。
2、99%脉脉帖子认为：刷算法题只是为了应付面试而已，工作上用不到
3、如何使用机器学习解决传统图搜索和离散优化问题？又如何使用传统动态规划和树递归优化深度学习模型？
有了PARL后，以上困惑真的是迎刃而解了——两手抓两手都要硬即可，不仅要要刷更多的题，也要学习更多的模型。
最后，为PARL打call：
深度强化学习框架PARL——联结传统数据结构与算法和新兴深度学习算法的桥梁，算法工程师的不二选择！
O(∩_∩)O

**Comment by TomorrowIsAnOtherDay** [comment]
看了下我之前参赛ACM的时候在[POJ 1077](http://poj.org/problem?id=1077)上的做法是hash + BFS，勉强719ms水了过去（数据要是强一点的话估计就过不去了）
RL搜索 + 打表这个想法很棒啊，手动点赞@kosoraYintai
