### ISSUE TITLE
关于from parl.utils import logger的问题

### ISSUE THREAD

**Issue by ShenAoChen2001** [PaddlePaddle/PARL#780]
我想在别的程序里面使用logger.info，但是我发现只要加了from parl.utils import logger之后，程序就会卡在那里，把这句注释掉，使用print的时候程序很快就能运行

**Comment by TomorrowIsAnOtherDay** [comment]
十分感谢你的反馈：）我们之前在使用logger时候没有遇到过类似的问题。
能提供简单的代码给我们跑下吗？这样更好定位问题。

**Comment by ShenAoChen2001** [comment]
Sorry，这是我的错，我刚刚把电脑重新打开然后发现可以运行了，对不起




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Bo ***@***.***&gt;; 
发送时间: 2022年1月10日(星期一) 下午2:22
收件人: ***@***.***&gt;; 
抄送: "(12N15L24) ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PARL] 关于from parl.utils import logger的问题 (Issue #780)





 
十分感谢你的反馈：）我们之前在使用logger时候没有遇到过类似的问题。
 能提供简单的代码给我们跑下吗？这样更好定位问题。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by TomorrowIsAnOtherDay** [comment]
好的，有问题随时欢迎来提问：）

**Comment by chl1123** [comment]
您好，我也遇到这个问题了，程序一直卡顿，没有结果。
![image](https://github.com/PaddlePaddle/PARL/assets/76507914/219d4743-ed10-4b1d-a07c-6bab7dd12b3a)
