### ISSUE TITLE
关于离线强化学习环境生成的建议

### ISSUE THREAD

**Issue by forrestneo** [PaddlePaddle/PARL#789]
目前离线强化学习的一个主要问题就是在生成环境的时候很困难，只有很少的数据，没有env环境，也不知道怎么搞。我的建议是parl可以在生成环境方面做些文章，比如说导入观察空间动作和奖励，定义一下动作逻辑，通过对抗生成网络或者别的技术生成更多数据，然后训练出来一个环境，这样再结合现有的算法，可以减小落地难度，扩大强化学习落地场景的范围

**Comment by TomorrowIsAnOtherDay** [comment]
感谢您的反馈。我们目前也在积极跟进业界的最新技术，包括离线强化学习和基于环境模型的规划技术，希望这两项技术能够脱离仿真环境也能优化策略，降低RL落地门槛。
