### ISSUE TITLE
高度代码封装,在ai studio多搞点项目,站在小白角度上想想问题吧,parl不是只给百度高级研究员用的

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/PARL#790]
兄弟,深有同感.我对于parl代码高度封装说了不少话了,飞桨回答者找了一堆理由坚决反对高度封装.我不知道他是如何理解高度封装的.一个函数A内部包含很多个函数BCDEFG等函数,难道开发者就不能调用BCDEFG函数了?一个类A包含很多类BCDEFG等等类对象,难道开发者就不能使用BCDEFG类?只要飞桨愿意提供没经过封装的函数,那么开发者依然可以使用这些函数,而不是说只能使用高度封装后的函数.举个例子,找图算法,在一张大图片里面,查找跟一张小图片最匹配的点,有一种算法是模板匹配,参考opencv的6种模板匹配,模板匹配用的方法是总误差.找图还有一种方法,一个像素和另外一个像素是否匹配,根据这种算法来得出一张图片中和另外一张图片的相似度,我们把一个像素和另外一个像素是否匹配实现为一个函数B,把大图片中找小图片实现为另一个函数A,飞桨提供函数A,我们能调用,实现大图片找小图片的功能,如果飞桨愿意提供函数B,我们还是可以从底层入手.甚至自己写个类似的函数A.我就不知道,这种高度封装有什么问题?
我站在C++角度谈这些,python不懂,但我相信大同小异,只要飞桨parl愿意提供相关函数和算法,无论是底层,还是高层,都是可以调用的,不可能说弄了个高度封装的算法,底层就调用不了,这只能说飞桨parl代码组织能力差,出现大问题了.
强化学习,或者说深度强化学习发展的很好,起点可以认为是谷歌围棋的成功,谷歌围棋是算法的成功,而不是代码的成功,并没有使用高度难懂,难编写的代码,我就不相信使用keras无法写出谷歌那个围棋代码.
据我所知,谷歌围棋成功后,很多高手复现,改善相关算法,最牛逼的是katago算法.有人把katago围棋算法改成各种其他棋类的,基本上就是改了棋类规则,除了中国象棋和中国围棋之外,都改了,而且都实践过了,2060显卡跑一天,棋力远远超过不使用机器学习的算法.katago代码多少行,改动多少行可以做成其他棋类,parl自己算算,你们就知道代码高度封装或者弄多些项目多重要了.
看看ai studio的项目,最新项目有几个是parl?精品项目有几个是parl?ai studio 的项目,选择强化学习类别,能看到多少最近开发的项目?看看issue,parl有多少条目?平均多少天更新一条parl issue?我也是醉了,顶级学术论坛接收论文,强化学习占了一半,结果parl竟然连clas一个都比不过,笑死我了.
我在clas,dec等提问题,不会被删除,parl会.
我在parl提了几个问题,都是关于代码高度封装和离线强化学习.代码高度封装被拒绝了.到今时今日,我都不知道离线强化学习这个算法究竟复现完成了没有?我也不知道有没有相关项目,比较好理解简单代码不多的项目使用了离线强化学习这个算法.
paddlex,hub弄了项目合集,我使用paddlex,无论做图像分类,目标检测,语义分割,实例分割,改几行代码就可以完成训练和预测,比如图片路径改一下,训练epoch数量改一下,学习率改一下,超级简单,就可以训练,我真的懂得那些原理吗?我真的知道图片数据如何被clas,dec等处理吗?我真的知道预处理图片使用的具体算法吗?我真的会使用飞桨复现ResNet101?我都不知道,小白中的小白,但我会跑代码,图像分类等功能我就会用了.只要这些模块提供相关功能,一个功能弄几个项目,写点注释,我完全就会用了.飞桨能指望我自己去实现这么多功能才会用图像分类吗?parl有这么便捷吗?我觉得parl实现就是为了给那种万里挑一的程序员用的,他们得懂算法原理,甚至他们可以自己发明牛逼哄哄的算法,甚至能3天复现一个顶级学会论文的大佬才有资格使用,哈哈哈哈.C++随机数,封装成几个类,叫C++程序员实现这几个类,几个人会?他们得深刻理解什么是正态分布,什么是伯努利分布等等分布规则.他们还得知道计算机如何存储浮点数,如何存储整数.他们还得知道计算机产生随机数的几种算法,螺旋还是其他算法,等到这些都学会了,才能写出一个能生产随机数的函数?这完全就是在逗我.别的复杂东西可以高度封装,parl不行?一个DQN超级简单的算法,需要写几百行代码,哈哈哈哈.我还得买几本强化学习的书籍,学习英语,看一堆顶会论文,复现论文?那做飞桨干嘛,我自己复现就行了.
我真心觉得parl就是给百度研究人员用的,别的人,无论是小白,还是高手,都用不了.小白不可能一个项目自己写一堆代码.高手真的一定会选择飞桨parl?pytorch,tensorflow,等等,都有强化学习组件吧?为什么非要选择中文的飞桨parl?腾讯的强化学习搞定王者荣耀,飞桨parl搞定电网?搞定强化学习,每个人都懂的什么意思,搞定电网,几个人懂得什么意思?几个人关注?如果只是搞定电网的某个比赛,关注者就更少了.王者荣耀2亿用户,至少1千万人关注吧.至少5千万人跟强化学习得到的模型对战过吧,电网几个人关注,得到冠军很爽?而且你弄个电网冠军,我用的了这个东西吗?为了造福世界,我电价能低一点?
飞桨parl更新都不知道更新了什么内容,算法复现完成了没有我都不知道.
机器学习,本质上就是输入和输出.输入是图片,文字,或者一串数据,输出某种类型的结果,中间可以认为是个算法.对于离线强化学习,输入一组数据,或者一堆图片,经过你们复现论文的算法,或者你们自己研究出来的算法,让我得到一个模型,这个模型牛逼哄哄,超级厉害,这不能封装?这样做的话,不就可以做到一个很简单的项目搞定一个牛逼哄哄的算法.我只需要关注,我输入的图片的质量,或者我输入的数据的质量,不需要关心算法,不需要关心算法如何训练我输入的图片或者数据,不需要关心模型如何训练的,不需要写那么多代码.
看了parl的issue,提到离线强化学习是最多的,估计也是世界上最关注的,封装成一个函数做不到,那就封装成3个,10个名字有点不同的函数.C++随机数也是封装成几个类,而不是一个类,C++随机数一个类就弄一种算法,几个类就是几种算法,比如mt19937.
离线强化学习如果无法弄成一个函数,那就弄成多个函数,离线强化学习有多少种算法,弄几个函数不就好了.
你们非要把parl弄得只有很厉害的程序员才能使用,或者说,才用的好,我也没话说,无语.
围棋katago改编成五子棋,六子棋,作者就看规则相关代码,其他所有代码,无论是katago算法,上传对局代码,tensorrt,cuda代码,还是其他代码,都不去看.因为他就只改改规则,这才是真正的应用.
真心希望parl可以做到输入图片或者一串数据,就得到一个牛逼哄哄的模型,那就爽歪歪了.
叫我学习算法原理,数据如何组织,这真是我的责任吗?这应该是飞桨parl开发者的责任.
我连最简单的神经网络都不会写,但我可以依靠飞桨提供的个个开发套件加上项目,来掌握很多功能,比如图像分类,语义相似度等等.如果我真的把所有算法原理都掌握,甚至复现这些顶会论文,我还需要飞桨干嘛?就拿图像分类来说,掌握paddlex一个图像分类所有代码的人,有多少?能用paddlex做图像分类的功能的人有多少?完全不成比例.

**Comment by TomorrowIsAnOtherDay** [comment]
与issue https://github.com/PaddlePaddle/PARL/issues/789 的需求类似，我们会将高阶接口放到开发计划中。
另外目前离线强化学习CQL算法已经开源，可以在example目录中找到。

**Comment by TomorrowIsAnOtherDay** [comment]
关于高阶接口的开发进展，后续会在#789 同步，关闭重复的issue。
