### ISSUE TITLE
代码高度封装,跪求10行代码应用parl

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/PARL#791]
我说几点看法:
1.我不认为数据预处理算是强化学习的一个流程.这应该算是强化学习之前的步骤.paddlex也是几行代码搞定一个功能,比如图像分类,但是paddlex不会把数据预处理当成深度学习训练的一个流程.MNIST图片可以直接传入paddlex,其实还可以把mnist图片先做预处理,比如白色部分截下来,去除外部黑色部分,然后图片再扩大成28*28,这样准确率99+,不使用深度学习就99+.这是预处理数据过程,真的算是paddlex的一部分吗?我看未必,比方说这个预处理过程是可以用一万种编程语言来写的,不一定非要用python.
2.输入数据或者图片,定义一个小模型或者大模型,比如是2层的神经网络还是ResNet101,然后通过选择飞桨parl包装好的强化学习算法,进行训练,得到一个很厉害的模型,这才是应用开发者的方向吧.你们做parl如果是为了夺得世界冠军,你们可以把代码弄得很复杂,完全不封装,你们甚至还可以用C++去写,不用python啊.而且我也搞不懂,为什么高度封装就不能得到冠军?你们弄两套代码,一套高度封装,一个高层函数包含多个底层函数的代码,你们自己用底层函数的代码去得冠军不就行了?
3.我们作为应用开发者,只能应用API,或者是从一个简单几行代码去更改.我们根本不可能掌握强化学习算法原理,算法如何使得模型对数据进行训练,损失函数该如何选择,等等,我们真做不了.python著名的根本原因就是开发效率比C++快多了,你们开发一个库,要是需要使用者先掌握相关算法原理,甚至数据都要预处理,复现顶会论文算法,做一大堆工作,那为什么不自己写这些算法,还需要你们开发parl呢?我们没那个实力掌握那么多,只能在你们建好的大厦上去应用.有人开发了围棋katago,有人把围棋katago改成五子棋,六子棋等,只改了棋类规则,一样是世界冠军,他真的懂得katago的算法,看得懂katago那么多C++,python代码?懂得tensorrt,cuda代码如何写?他只是负责改棋类规则,还有极少量工作,然后就是显卡跑训练,2060训练一天,五子棋天下第一,六子棋天下第一,这不是冠军吗?这可是世界公认的冠军,一天,就显卡跑一天,改改规则,搞定.这个人真的懂得katago的算法?懂得katago比起阿尔法狗有什么长进?真的会编写一堆代码?还是简单的好啊,真的.你们说自己是世界冠军,你们现在弄个算法,2060跑一天,真的就是世界冠军吗?不相信.
4.我真心觉得你们应该比拼的是实现顶级算法的能力,paddleclas等合集都是有什么好算法,往往就包含进去.然后我们很容易使用,超级简单.parl算法,你们有没有试过棋类复现,能否达到世界冠军?打王者荣耀能否打败顶尖职业选手?我想你们都没做吧,主要就看atari游戏能否达到论文指标吧.
@TomorrowIsAnOtherDay
5.我非常希望,parl能像你说的,输入图片或者数据作为状态,有时候或者还需要动作或者结果,然后再自定义一个模型,选择parl封装好的算法,就可以训练,然后训练完还能输出相关指标.而不是编写很多代码,学习一堆算法原理等才能去应用.麻烦你们好好考虑我们这种应用开发者的需求.如何让项目变得简单,编写代码少,逻辑更加清晰,算法封装容易应用,这应该是parl开发者的责任,而不是我们这些应用者的责任.跪求高度封装,我坚信,就算是高度封装,只要你们实现的算法很牛逼,一样可以得到世界冠军.你们要是封装katago的算法,难道我把围棋规则改成五子棋规则,我就不能得到世界冠军?我不可能把整个katago代码都看懂才能得到世界冠军吧?
6.我手头有一堆数据,但我现在真不知道如何应用parl进行学习.项目不多,教程不多,parl封装做的不好,唉.问一下,离线强化学习完全复现好了吗?我使用这个算法,需要做什么?我可以参考哪个项目呢?

**Comment by TomorrowIsAnOtherDay** [comment]
与issue #789 的需求类似，我们会将高阶接口放到开发计划中。
另外目前离线强化学习CQL算法已经开源，可以在example目录中找到。
