### ISSUE TITLE
关于科科老师强化学习打卡营！

### ISSUE THREAD

**Issue by jingyile** [PaddlePaddle/PARL#794]
在科科老师的强化学习打卡营基础上问一个问题
是否可以通过lesson3的DQN算法去解决lesson2的小乌龟找出口问题。
可以的话方便吗，正在尝试但碰到了一些问题：
类似：
ValueError: (InvalidArgument) Input(Y) has error dim.Y'dims[0] must be equal to 1But received Y'dims[0] is 8

主要想问问同一段代码 改gym环境的话 修改简单方便吗

**Comment by TomorrowIsAnOtherDay** [comment]
这个想法..杀鸡用牛刀的即视感。
打表格的方法很适合用来解决这种格子类型的问题，DQN提出来是为了解决高维状态输入的难题。
建议还是根据问题选择合适的算法：）

如果你想尝试的话，不建议自己改gym环境，可以把gym环境的输出后处理一下。

**Comment by jingyile** [comment]
> 这个想法..杀鸡用牛刀的即视感。 打表格的方法很适合用来解决这种格子类型的问题，DQN提出来是为了解决高维状态输入的难题。 建议还是根据问题选择合适的算法：）
> 
> 如果你想尝试的话，不建议自己改gym环境，可以把gym环境的输出后处理一下。

哈哈哈哈 确实是想用牛刀杀鸡试试效果！
就单纯的想用DQN去和Q-Learning处理同一个问题看看。
就只是想简单的替换下环境，我觉得算法本身应该不用修改的吧。
比如将 env = gym.make('CartPole-v0')
替换为  env = gym.make('CliffWalking-v0')

然后因为两个环境的状态空间和动态空间不同。
需要改一些小地方应该，我不太会修改了。QAQ

**Comment by jingyile** [comment]
有熟悉代码的大佬可以动手试试这个小问题吗！(*╹▽╹*)
