### ISSUE TITLE
WRN No deep learning framework was found, but it’s ok for parallel computation.

### ISSUE THREAD

**Issue by IMZGforever** [PaddlePaddle/PARL#797]
WRN No deep learning framework was found, but it’s ok for parallel computation.

**Comment by IMZGforever** [comment]
another info:Cannot find available GPU devices, using CPU or other devices now.

**Comment by TomorrowIsAnOtherDay** [comment]
Hello. The log shows that parl cannot find any deep learning framework installed in the environment.

**Comment by IMZGforever** [comment]
> hallo ,but how to solve it

**Comment by TomorrowIsAnOtherDay** [comment]
if you would like to run our example, run the following command:
```shell
pip install paddlepaddle 
```
