### ISSUE TITLE
CARLA安装问题

### ISSUE THREAD

**Issue by ouyangshixiong** [PaddlePaddle/PARL#798]
按[PARL代码库中example中项目](https://github.com/PaddlePaddle/PARL/tree/develop/examples/CARLA_SAC)的文档说明下载并解释压缩对应版本的CARLA项目。获得:
- CarlaUE4.sh
- CarlaUE4目录

其中目录CarlaUE4中没有找到后续文档提到的"PythonAPI"目录。
麻烦完善一下文档，谢谢！

**Comment by TomorrowIsAnOtherDay** [comment]
感谢反馈！ 我们修复下

**Comment by rical730** [comment]
CARLA_0.9.6.tar.gz解压后包含13个文件和文件夹，其中包含"PythonAPI"文件夹，但确实文档对CARLA_0.9.6.tar.gz的解压过程说明得比较简略，已在 https://github.com/PaddlePaddle/PARL/pull/799 更新。

**Comment by ouyangshixiong** [comment]
Works for me ,thank you.
