### ISSUE TITLE
请问如何理解Sarsa中A'为下一个state的实际action

### ISSUE THREAD

**Issue by leshui1991** [PaddlePaddle/PARL#802]
![20200619122316836](https://user-images.githubusercontent.com/30827168/157577094-38bd2afa-8830-4b8a-8c49-47b9f0e9b074.png)
例如图中的位置和Q表格，假如我目前在位置10，我这一步选择了向下（1 down），那下一个state是14，下一个action是指对应最大值向右（2 right）吗，这一步选择时需要考虑epsilon的0.1导致可能在14处选择其他可能性吗？

**Comment by leshui1991** [comment]
如果在14处有两个Q相同的动作，A'是随机选择一个吗

**Comment by TomorrowIsAnOtherDay** [comment]
> 

是的，随机选一个执行。如果这次的动作并不好，导致后续拿到惩罚，那更新之后这个动作的Q值就会下降。
这样第二次再来到14处，就不存在两个一样的Q值动作了。

**Comment by leshui1991** [comment]
> 了
请问当我在10的，下一个state是14的时候，在选择14对应的A‘需要考虑epsilon的随机值吗

**Comment by TomorrowIsAnOtherDay** [comment]
训练的时候需要，评估的时候直接取max就好了。

**Comment by leshui1991** [comment]
@TomorrowIsAnOtherDay 
劳驾再问一下，就图中的Q表格，为什么在15的地方还会有向下的0.69的Q值，以及5/9等边缘位置，都有出地图的Q值，请问是环境FrozenLakeWapper或者gym的问题吗，当他们出了地图后面是怎么计算Q值的？如果我要自己写一个训练环境，需要提供一个GetEnableActionList吗？

**Comment by rical730** [comment]
智能体可以执行的4个动作（上下左右），在任何时刻任何格子中都可以执行，只是在边缘位置，某些动作执行了之后由于环境的限制无法生效，比如在15的位置，智能体可以执行向下的动作，但不会生效，所以训练到最后，向下的Q值并不高，智能体也就偏向于不去执行这种无效动作。
