### ISSUE TITLE
windows下c++部署，运行exe出错

### ISSUE THREAD

**Issue by yanhao1998** [PaddlePaddle/PARL#803]
windows下c++部署，PaddleClas-release-2.2，paddle_inference2.2，cpu+mlk。编译完成后运行exe出错。

=======Paddle Class inference config======
cls_model_path : /modelclas/GF/inference.pdmodel
cls_params_path : /modelclas/GF/inference.pdiparams
cpu_math_library_num_threads : 10
crop_size : 224
gpu_id : 0
gpu_mem : 4000
resize_short_size : 256
use_fp16 : 0
use_gpu : 0
use_mkldnn : 1
use_tensorrt : 0
=======End of Paddle Class inference config======
img_file_list length: 1

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
NotFoundError: Cannot open file /modelclas/GF/inference.pdmodel, please confirm whether the file is normal.
  [Hint: Expected static_cast<bool>(fin.is_open()) == true, but received static_cast<bool>(fin.is_open()):0 != true:1.] (at C:\home\workspace\Paddle_release\paddle\fluid\inference\api\analysis_predictor.cc:953)

**Comment by TomorrowIsAnOtherDay** [comment]
hello，部署问题请到飞桨官方仓库上提问：）
