### ISSUE TITLE
请问parl的MADDPG算法框架是不支持连续的动作空间的吗？

### ISSUE THREAD

**Issue by amocken** [PaddlePaddle/PARL#804]
如果我把动作空间设成gym.spaces.Box类型就会出错，提示动作空间必须为gym.spaces.Discrete或者multiagent.multi_discrete.MultiDiscrete类型
![image](https://user-images.githubusercontent.com/48198083/157819391-071aecb8-8b38-4d22-a79a-39dd4cb122a3.png)

**Comment by amocken** [comment]
@TomorrowIsAnOtherDay

**Comment by ollehhello** [comment]
你好，我也遇到了相同的问题，请问你解决了吗

**Comment by TomorrowIsAnOtherDay** [comment]
hello，抱歉之前一直忘记回复了。问题我们已经定位到了，将在近期修复：）

**Comment by ollehhello** [comment]
感谢，十分期待！

**Comment by ollehhello** [comment]
如果你们修复好，希望可以在该问题下提醒一下，谢谢

**Comment by amocken** [comment]
> 你好，我也遇到了相同的问题，请问你解决了吗

我现在试图修改MADDPG算法框架的源代码来解决

**Comment by amocken** [comment]
> 你好，我也遇到了相同的问题，请问你解决了吗

我现在正在尝试修改MADDPG算法框架的源代码来解决

**Comment by TomorrowIsAnOtherDay** [comment]
@amocken 如果修改好也可以提给PR回馈给社区哈

**Comment by TomorrowIsAnOtherDay** [comment]
更新：4.8号已支持。

**Comment by amocken** [comment]
> 更新：4.8号已支持。

但是你们似乎还没有在pip上发布新版的parl

**Comment by TomorrowIsAnOtherDay** [comment]
感谢提醒，我们本月会发版本哈，联合别的内容一起发版，现阶段只能通过拉源码安装最新版本。

**Comment by amocken** [comment]
> 感谢提醒，我们本月会发版本哈，联合别的内容一起发版，现阶段只能通过拉源码安装最新版本。

目前最新的代码这里的异常提示有点问题，漏写了gym.spaces.Box @rical730
![image](https://user-images.githubusercontent.com/48198083/168286643-99e77abd-926f-4cfa-b260-5a62b0c2139d.png)

**Comment by amocken** [comment]
> 感谢提醒，我们本月会发版本哈，联合别的内容一起发版，现阶段只能通过拉源码安装最新版本。

目前最新的代码这里的注释和异常提示有点问题，漏写了gym.spaces.Box @rical730
![image](https://user-images.githubusercontent.com/48198083/168287745-4c182de3-890c-4ce7-9d1e-a842516de109.png)

还有这里漏写了DiagGaussianDistribution
![image](https://user-images.githubusercontent.com/48198083/168287905-38d52c92-f1c2-4aa4-b9e5-5237a34fc20b.png)

**Comment by rical730** [comment]
>  目前最新的代码这里的注释和异常提示有点问题，漏写了gym.spaces.Box @rical730 

感谢指出，已提交PR，将在 https://github.com/PaddlePaddle/PARL/pull/877 中修复。
