### ISSUE TITLE
model的输入数据类型

### ISSUE THREAD

**Issue by MrLiuWinter** [PaddlePaddle/PARL#805]
TypeError: The type of input[0] in fc must be Variable, but received <class 'numpy.ndarray'>

Model文件下
value(obs)函数的网络层输入obs ，因为是通信环境的信道状态，所以输入的obs会是向量，或者矩阵这样类型的数据，方便批处理。不知道有没有对数据类型做泛化，我输入的是状态矩阵，错误提示输入数据的类型不对。

贴一段tensorflow代码做参考。s就是obs。我没学过，看不懂tensorflow。
s= {Tensor: (None 50)}Tensor("s:0", shape=(None, 50), dtype=float32)
    def create_dqn(self, s, name):
        with tf.variable_scope(name + '.0', reuse=reuse):
            w = self.variable_w([self.state_num, 128])
            b = self.variable_b([128])
            l = tf.nn.relu(tf.matmul(s, w) + b)
        with tf.variable_scope(name + '.1', reuse=reuse):
            w = self.variable_w([128, 64])
            b = self.variable_b([64])
            l = tf.nn.relu(tf.matmul(l, w) + b)
        with tf.variable_scope(name + '.2', reuse=reuse):
            w = self.variable_w([64, self.action_num])
            b = self.variable_b([self.action_num])
            q_hat = tf.matmul(l, w) + b
        return q_hat

**Comment by TomorrowIsAnOtherDay** [comment]
hello, 我没理解你的问题。你是运行我们的代码出问题了吗？我们的代码不包含tensorflow的
