### ISSUE TITLE
[feature request] distribute all the data of a folder 

### ISSUE THREAD

**Issue by TomorrowIsAnOtherDay** [PaddlePaddle/PARL#806]
Xparl cannot distribute a folder currently. Users may want to distribute a folder containing a lot of configuration files (e.g., cityflow).

**Comment by YuechengLiu** [comment]
It seems that xparl has been able to distribute a folder (together with its all subfiles recursively) like this: `parl.connect('xxx', distributed_files=['./folderA', './folderB/'])`.

https://github.com/PaddlePaddle/PARL/blob/846ebc97fff4e8bcbd9226c82222bef989c139d8/parl/remote/client.py#L123

**Comment by TomorrowIsAnOtherDay** [comment]
It works!
