### ISSUE TITLE
请问parl_baselines仓库,会不会包含parl所有算法呢?

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/PARL#809]
使用parl_baselines,是不是可以用少数代码实现强化学习了?

**Comment by yuwoyizhan** [comment]
还有一点,ai studio里面只有很少parl项目,甚至很久都没更新,你们考虑增加一些项目吗?使用parl_baselines的也行啊,拜托.弄个不太难的项目,然后把所有算法用上一遍,我估计,我也就会写相关代码了,甚至我直接照搬你们的代码了,哈哈哈哈,轻松+愉快.

**Comment by yuwoyizhan** [comment]
还有一个疑问,如果使用parl的离线强化学习算法,我需要准备什么东西呢?状态?状态下的很优秀的一个动作?状态下执行某个很优秀动作的预期或者期望的效果?还是需要准备什么数据?如果使用parl_baselines,我又该准备什么东西或者数据呢?

**Comment by yuwoyizhan** [comment]
@TomorrowIsAnOtherDay

**Comment by TomorrowIsAnOtherDay** [comment]
请关注我们的开发进度，第一版本计划预置少部分算法，先迭代好算法接口再跟进其余算法。PS：罗马帝国不是一日建成的。

**Comment by yuwoyizhan** [comment]
对于图像分类来说,输入图像,定义神经网络模型,损失函数,优化函数等等,类别总数量,训练,然后根据验证集的top1准确率选择最好的模型,部署预测,输出图像的具体类别.虽然选择学习率等超参数往往很繁琐,训练时间久,模型一开始也不太清楚应该选择哪个模型比较好,3层CNN,还是ResNet50还是swint模型.但是总体上来说,整个流程是很清晰的.
对于离线强化学习来说,比如五子棋这个游戏,我应该输入什么呢?我是不是应该使用一个非常厉害的五子棋引擎,引擎对战,得到质量非常高的对局,然后把对局编码为当前状态和下一步动作,输入状态和动作,让离线强化学习去学习呢?还是应该输入什么东西呢?
我想,你可以回答一下离线强化学习需要我准备什么数据这个问题,这个回答跟开发进度无关吧?我需要准备状态,还是状态和最优动作,还是状态和最优动作和预期结果,还是状态和最佳动作和应用该动作的结果?
我可以保证状态下的动作是很高质量的,而且数据比较大.
@TomorrowIsAnOtherDay
