### ISSUE TITLE
模型的Save和Load在AIStudio中试验失败

### ISSUE THREAD

**Issue by kosoraYintai** [PaddlePaddle/PARL#81]
目前Save、Load模型参数**在本地可以试验成功，但在AIStudio中会出现以下问题**：
1、调用fluid.io.save_params()函数后，模型参数的序号会变化，而不是从0开始：

![AIbug01](https://user-images.githubusercontent.com/31379401/59753231-4290cd80-92b6-11e9-80ec-d2f343ecc871.jpg)

2、将模型的参数拷贝到本地之后，是无法运行的；将他们的需要重命名为从0开始，本地才可以调用fluid.io.load_params()函数运行成功：

![AIbug02](https://user-images.githubusercontent.com/31379401/59753312-723fd580-92b6-11e9-84df-2816135bd180.jpg)

3、但是，无论是否重命名，AIStudio调用fluid.io.load_params()函数都会报错；而且，每次load的时候，序号都会发生改变，比如下图的12、16：

![AIBug04](https://user-images.githubusercontent.com/31379401/59753408-a61afb00-92b6-11e9-9eb8-6478ad9f341f.png)

![AIBUg05](https://user-images.githubusercontent.com/31379401/59753420-aa471880-92b6-11e9-9dfe-034aebc44c08.png)

项目地址：
https://aistudio.baidu.com/aistudio/projectdetail/63441?_=1560765585066
内含报错信息，麻烦解决一下。

**Comment by TomorrowIsAnOtherDay** [comment]
收到，我们这边先确认下是否是PARL引起的，如果不是的话我们会转交给AI Studio的同事跟进，感谢反馈。

**Comment by zenghsh3** [comment]
@kosoraYintai hi，问题定位到应该是在同一个程序里创建多个agent/model导致的。例如train过程创建了一个model和agent（假设layers的参数名是从0命名到9），然后同个程序里在test过程中又创建一遍model和agent的话（layers的参数名会从10命名到19），从而引起load_params参数找不到。

修改后的一个可跑版本：
https://aistudio.baidu.com/user/74287/72745/notebooks/72745.ipynb?redirects=1

![image](https://user-images.githubusercontent.com/5762635/59763442-3283e880-92cc-11e9-8693-3205bcfad7a9.png)

**Comment by TomorrowIsAnOtherDay** [comment]
我认为这个更多是静态图引起的歧义，未来支持动态图之后将更少出现这种情况。

**Comment by kosoraYintai** [comment]
这个可跑版本，相当于把train和test的过程绑在一起了，这样的话，只能将把train阶段产生的model/agent设置为的全局变量，以供后序的对拍和代码生成等功能使用，那么save/load函数就意义不大了；目前关闭页面后再load还是报错额，只能重新train一遍再test。是否有分离train与test过程的方法?(即：先train，train完save参数，再关闭项目或者关闭页面；然后重启项目或者刷新页面，直接load参数进行test)

**Comment by TomorrowIsAnOtherDay** [comment]
我理解你的疑惑。这个问题的来源是AI studio采用了类似Jupyter-notebook的方式来跑程序的，之前跑的程序是一直暂存在内存中(context），关闭页面并不代表关闭程序。

这个issue并不是PARL的相关bug导致的，我们即将关闭这个issue。

**Comment by zenghsh3** [comment]
或者可以显式地指定layers的参数名，从而创建多个agent时都是重用参数，例如下面:
![image](https://user-images.githubusercontent.com/5762635/59814055-76b3cf00-9346-11e9-8f3c-9363cefe3d60.png)

**Comment by kosoraYintai** [comment]
> 或者可以显式地指定layers的参数名，从而创建多个agent时都是重用参数，例如下面:
> ![image](https://user-images.githubusercontent.com/5762635/59814055-76b3cf00-9346-11e9-8f3c-9363cefe3d60.png)
终于解决了，不过bias也要加参数名

**Comment by kosoraYintai** [comment]
终于解决了，不过bias也要加参数名ParamAttr

**Comment by TomorrowIsAnOtherDay** [comment]
赞
