### ISSUE TITLE
请问有没有带CNN网络的强化学习算法的代码？

### ISSUE THREAD

**Issue by djjstyle** [PaddlePaddle/PARL#810]

**Comment by rical730** [comment]
examples里的DQN_variant和A2C的网络都是带CNN的

**Comment by rical730** [comment]
DQN_variant：https://github.com/PaddlePaddle/PARL/tree/develop/examples/DQN_variant
A2C：https://github.com/PaddlePaddle/PARL/tree/develop/examples/A2C

**Comment by TomorrowIsAnOtherDay** [comment]
https://github.com/PaddlePaddle/PARL/blob/846ebc97fff4e8bcbd9226c82222bef989c139d8/examples/DQN_variant/atari_model.py#L29
