### ISSUE TITLE
关于环境配置

### ISSUE THREAD

**Issue by a513254711** [PaddlePaddle/PARL#811]
python3.9，pip22.0.4， paddlepaddle2.2.0，应该安装怎么版本的parl呀

**Comment by TomorrowIsAnOtherDay** [comment]
https://github.com/PaddlePaddle/PARL/blob/develop/docs/zh_CN/Overview.md#%E5%AE%89%E8%A3%85-1
使用上述安装方式有什么问题吗？

**Comment by devilofshine** [comment]
pyzmp=18.1.1安装不上

**Comment by TomorrowIsAnOtherDay** [comment]
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/25046619/159848726-931b8cf1-38f8-4476-95bd-29cd25cb6e66.png">

@devilofshine 我这边测试了同样的环境，是可以正常安装的。你可以看下我上面的运行信息和版本。

**Comment by TomorrowIsAnOtherDay** [comment]
@devilofshine 你是哪个系统呢？Windows还是Linux？

**Comment by TomorrowIsAnOtherDay** [comment]
已解决Windows 系统安装问题，感谢各位的反馈
