### ISSUE TITLE
请问parl的文档和api在哪里啊

### ISSUE THREAD

**Issue by leshui1991** [PaddlePaddle/PARL#813]
在飞桨里面搜索不到啊
![微信截图_20220322235545](https://user-images.githubusercontent.com/30827168/159608489-e71b0331-1305-46f9-8cd9-5adbe13894e9.png)

**Comment by TomorrowIsAnOtherDay** [comment]
飞桨官方网站只有 【paddle】本体的使用文档。
PARL是基于飞桨开发的强化学习框架，是独立维护文档的，文档入口就在readme 的logo下方。
<img width="913" alt="image" src="https://user-images.githubusercontent.com/25046619/159610311-11d70c81-2b9f-4e02-bd58-da15e82c6c6b.png">
