### ISSUE TITLE
求使用飞桨ai studio复现强化学习相关书籍代码

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/PARL#814]
京东搜索强化学习,可以找到很多书籍,但是市面上应该没有一本专门讲飞桨强化学习的书籍,多数强化学习书籍也不是使用飞桨编写代码的.
现在很多人都是靠读书入门甚至深入学习强化学习,希望你们可以使用飞桨ai studio复现强化学习相关书籍的代码.
在ai studio上面弄一个项目合集,复现一本书籍代码,10个项目合集就是10本书籍代码.
https://aistudio.baidu.com/aistudio/projectdetail/231146,参考这个链接.
我相信,使用飞桨平台复现书籍代码,可以使得很多人投入飞桨的怀抱,毕竟很多人是靠这些书籍入门的.而且编写书籍代码的难度并不高,这些书籍讲的不可能是太高深的知识.还有一点理由,编写代码肯定比做视频教学容易得多.做视频需要录制视频,剪辑,删改,上字幕,做ppt,word等.
希望各位大佬可以考虑小弟这个建议,依小弟看,各位大佬复现代码书籍,一个人15天左右就可以复现一本书籍了,轻轻松松,哈哈哈哈.

**Comment by TomorrowIsAnOtherDay** [comment]
最近公司有团队在负责飞桨官方课程2.0的发布，会包含强化学习相关教程，我问问他们的计划。
