### ISSUE TITLE
PARL安装报错

### ISSUE THREAD

**Issue by devilofshine** [PaddlePaddle/PARL#815]
python==3.9.7
paddle==2.2.2
运行pip install parl时报错：
Building wheels for collected packages: pyzmq
  Building wheel for pyzmq (setup.py) ... error
Running setup.py clean for pyzmq
Failed to build pyzmq
Installing collected packages: pyzmq, psutil, flask-cors, cloudpickle, parl
    Running setup.py install for pyzmq ... error

**Comment by TomorrowIsAnOtherDay** [comment]
hello，看起来是pyzmq 暂时没有支持高版本的python。
建议你先使用3.7/8版本的python尝试下。

**Comment by TomorrowIsAnOtherDay** [comment]
@zenghsh3 请宏生确认下pyarrow对于python3.9的支持，看下我们是否有必要升级pyarrow版本

**Comment by zenghsh3** [comment]
pyzmq>=20.0.0开始支持python 3.9

**Comment by TomorrowIsAnOtherDay** [comment]
![image](https://user-images.githubusercontent.com/25046619/159850199-19f31609-6244-434e-ab07-2a7b69f1b2a9.png)
我刚在ubuntu上安装似乎没问题？

**Comment by TomorrowIsAnOtherDay** [comment]
> pyzmq>=20.0.0开始支持python 3.9

这个信息在哪获取到的呢？

**Comment by zenghsh3** [comment]
https://pypi.org/project/pyzmq/20.0.0/

**Comment by zenghsh3** [comment]
![image](https://user-images.githubusercontent.com/5762635/159855352-4eae33f2-5ee8-481c-b392-dcf94c8c029f.png)

**Comment by devilofshine** [comment]
win 10 系统

**Comment by wushuangpojun** [comment]
> ![图片](https://user-images.githubusercontent.com/5762635/159855352-4eae33f2-5ee8-481c-b392-dcf94c8c029f.png)

为啥我的python3.9.7可以安装pyzmq19.0.2，但是python3.10.2安装不了呢？

**Comment by TomorrowIsAnOtherDay** [comment]
https://pypi.org/project/pyzmq/
Pyzmq 目前最高支持版本是3.9

**Comment by TomorrowIsAnOtherDay** [comment]
https://pypi.org/project/pyzmq/
Pyzmq 目前最高支持版本是3.9

2022年4月7日 下午12:59，无双破军 ***@***.******@***.***>> 写道：



[图片]<https://user-images.githubusercontent.com/5762635/159855352-4eae33f2-5ee8-481c-b392-dcf94c8c029f.png>

为啥我的python3.9.7可以安装pyzmq19.0.2，但是python3.10.2安装不了呢？
