### ISSUE TITLE
PARL-develop\examples\DQN_variant\train.py中的batch_all_obs通道划分问题

### ISSUE THREAD

**Issue by djjstyle** [PaddlePaddle/PARL#818]
# train model
        if (rpm.size() > MEMORY_WARMUP_SIZE) and (step % UPDATE_FREQ == 0):#UPDATE_FREQ = 4
            # s,a,r,s',done
            (batch_all_obs, batch_action, batch_reward,
             batch_done) = rpm.sample_batch(BATCH_SIZE)#BATCH_SIZE = 32
            batch_obs = batch_all_obs[:, :CONTEXT_LEN, :, :]#CONTEXT_LEN = 4
            batch_next_obs = batch_all_obs[:, 1:, :, :]
请问1、为什么将batch_all_obs中前4个通道给batch_obs，2、batch_next_obs = batch_all_obs[:, 1:, :, :]这个怎么理解？3、这样做的目的或者优点是什么？

**Comment by TomorrowIsAnOtherDay** [comment]
这个问题提的很好。我先说下出发点，主要是为了节省内存。在atari游戏场景，obs的定义是最近4帧游戏。
第一个问题：前4个通道代表4张图像。
第二个问题：只有一个通道，表示一张图像。这一张图像后续会和【问题一】中的最后3张图像组成新的4张图像，表示next_obs。
