### ISSUE TITLE
在Pycharm下运行Example中的QuickStart代码，可以成功运行但是没有gym动画显示

### ISSUE THREAD

**Issue by Woodeeer** [PaddlePaddle/PARL#819]

**Comment by Woodeeer** [comment]
是不是必须安装tensorflow？

**Comment by TomorrowIsAnOtherDay** [comment]
https://github.com/PaddlePaddle/PARL/blob/846ebc97fff4e8bcbd9226c82222bef989c139d8/examples/QuickStart/train.py#L98
把这个的render 设置为true即可。

**Comment by Woodeeer** [comment]
谢谢，太感谢了
