### ISSUE TITLE
SAC算法加上卷积层后每次都输出同一个动作

### ISSUE THREAD

**Issue by djjstyle** [PaddlePaddle/PARL#820]
if rpm.size() < WARMUP_STEPS:
                action = np.random.uniform(-1, 1, size=action_dim)
            else:
                action = agent.sample(np.expand_dims(obs, axis=0))#obs：6*60*60的矩阵
请问我将您们这边SAC的算法加上卷积层，在rpm.size() > WARMUP_STEPS后，为什么 agent.sample每次输出的都是同一个动作？

**Comment by TomorrowIsAnOtherDay** [comment]
应该是学习率太大了导致模型训爆了，你可以先注释掉agent.learn这一步看看。
有两个选择：
1）降低学习率
2）对reward进行缩放

话说你的上一个issue如果解答了请自行关闭下。
