### ISSUE TITLE
请问下这里的alg在哪里可以看到源码，没看到alg的说明

### ISSUE THREAD

**Issue by liuchaohu** [PaddlePaddle/PARL#822]
https://github.com/PaddlePaddle/PARL/blob/50a173987159e6e8ff532319ca24de89bd1e72d2/benchmark/torch/dqn/agent.py#L80

**Comment by zenghsh3** [comment]
https://github.com/PaddlePaddle/PARL/blob/50a173987159e6e8ff532319ca24de89bd1e72d2/parl/algorithms/torch/dqn.py#L29

**Comment by liuchaohu** [comment]
> https://github.com/PaddlePaddle/PARL/blob/50a173987159e6e8ff532319ca24de89bd1e72d2/parl/algorithms/torch/dqn.py#L29

感谢及时、快速的回复~
