### ISSUE TITLE
判断有没有帧是结束帧

### ISSUE THREAD

**Issue by liuchaohu** [PaddlePaddle/PARL#823]
https://github.com/PaddlePaddle/PARL/blob/50a173987159e6e8ff532319ca24de89bd1e72d2/benchmark/torch/dqn/replay_memory.py#L69

您好，这里我不是很理解，希望您有空可以指导下：
随机抽取一条经验，这个经验的obs是4帧数据，在智能体做决策的时候，它是使用过去4帧做决策的；当我们随机抽取一条经验的时候，这条经验中的obs应该是采取那一下动作前的4帧画面，如果这4帧中有done的存在，那么是不是把done之前的数据变成0.
这样理解的话，那obs_idx = np.arange(idx, idx + self.context_len + 1) % self._curr_sizes是不是应该换成 idx, idx - context - 1呢？
另外有一点不太理解的是，为什么要从self.context_len - 2（1）也就是前两帧判断是否为done呢，后面两帧就不可能是done码？

**Comment by zenghsh3** [comment]
第一个问题的话，如下图，取action/reward/done是加了self.context_len - 1的
![image](https://user-images.githubusercontent.com/5762635/160630942-0b43843b-efbb-455a-a01e-74aeb3ecc9c5.png)
第二个问题的话，range(self.context_len - 2, -1, -1)的遍历是：2,1,0，是对前三帧进行判断，然后第四帧如果是done的话不影响

**Comment by liuchaohu** [comment]
> Reference in n

豁然开朗，感谢回复！
