### ISSUE TITLE
神经网络输出中经过状态的转移其中含非法动作

### ISSUE THREAD

**Issue by noc-turne** [PaddlePaddle/PARL#824]
举个例子
下围棋中, 一开始动作有361个, 但随着棋局的进行, 有些动作变成了非法动作(不能下在之前的棋子上)
请问这时候应该如何处理?
把这个动作直接设置为终止状态, 然后返回一个巨大的负reward, 效果似乎并不理想
请各位大佬指点.

**Comment by TomorrowIsAnOtherDay** [comment]
这里仅讨论PARL框架相关的问题，请前往强化学习社区进行类似讨论。

**Comment by noc-turne** [comment]
您好, 我就是用的parl框架做的, 用的policy gradient算法, 现在遇到了这个问题, 请问您能帮我解答吗?
问题如下:
神经网络的输出动作在某些状态下有些是非法的, 请问我应该在哪个部分处理这个问题
是在agent.sample/predict()里面吗?
但是我需要跟环境互动中才知道这个状态是否非法, 请问有什么好的解决办法吗?
非常感谢!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PARL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月30日(星期三) 晚上7:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PARL] 神经网络输出中经过状态的转移其中含非法动作 (Issue #824)





 
这里仅讨论PARL框架相关的问题，请前往强化学习社区进行类似讨论。

**Comment by TomorrowIsAnOtherDay** [comment]
AlphaGo是带planning的，他可以通过模拟未来的棋盘来直接过滤掉不合理的动作。
纯强化学习算法确实没有比较好的解决方案，可以查下TSP+RL相关的工作看看，TSP里面也面临着动作合法性的挑战。
