### ISSUE TITLE
pytorch

### ISSUE THREAD

**Issue by l-sf** [PaddlePaddle/PARL#825]
为什么parl(r2.0.3)框架里好多 import torch？我并没有安装pytorch但是他也不报错？这到底是啥意思？

**Comment by TomorrowIsAnOtherDay** [comment]
https://github.com/PaddlePaddle/PARL/blob/50a173987159e6e8ff532319ca24de89bd1e72d2/parl/__init__.py#L35

PARL 目前支持torch、fluid、paddle作为后端，优先加载paddle的。
