### ISSUE TITLE
关于DQN算法中，目标网络的问题。

### ISSUE THREAD

**Issue by leshui1991** [PaddlePaddle/PARL#827]
请问各位，DQN算法中要用Q网络逼近Q-target网络，Q-target网络的参数来源于Q网络的定期更新，比如说更新周期是100个episode，那就是说Q网络去逼近100个周期之间的目标网络，可是Q网络经过了100个周期的训练，不是应该更准确了吗，为什么要去逼近更不准确的网络。

**Comment by leshui1991** [comment]
上面那段里有个错字，“那就是说Q网络去逼近100个周期之间的目标网络”，应为“那就是说Q网络去逼近100个周期之前的目标网络”。

**Comment by TomorrowIsAnOtherDay** [comment]
Hello，建议去阅读DQN 原始论文，作者已经阐述了使用Q-target的作用。
