### ISSUE TITLE
请问examples-MADDPG中，对agent优化是用的每个agent各自的reward吗？不是全局的reward吗？

### ISSUE THREAD

**Issue by yecai123** [PaddlePaddle/PARL#829]
在simple_agent文件中，代码段如下：
        # sample batch
        rpm_sample_index = self.rpm.make_index(self.batch_size)
        for i in range(self.n):
            batch_obs, batch_act, _, batch_obs_next, _ \
                = agents[i].rpm.sample_batch_by_index(rpm_sample_index)
            batch_obs_n.append(batch_obs)
            batch_act_n.append(batch_act)
            batch_obs_next_n.append(batch_obs_next)
        _, _, batch_rew, _, batch_isOver = self.rpm.sample_batch_by_index(
            rpm_sample_index)

有2个问题：
Q1：送去优化的sample的经验是用的所有agent的obs, act, obs_next, 但是reward用的是每个agent各自的，寻优的就是agent各自最优，不是全局最优吧？这是不是属于分散训练，分散执行呢？
Q2：示例的MADDPG代码是适用于每个agent都是同类型（状态和动作一样）的是吗？
谢谢

**Comment by rical730** [comment]
Q1：集中式训练，分布式执行 指的是：训练时critic与actor的训练是知道全局信息的，critic需要其他智能体的策略信息，集中式学习训练指的是信息集中，而分布式执行指的是使用时actor只用知道局部信息就能运行。
Q2：示例的MADDPG代码也适用于每个agent是不同类型的（状态和动作空间不一样），可参考simple_speaker_listener的环境。

**Comment by rical730** [comment]
关于题目中的问题，example-MADDPG确实是用每个agent各自的reward来优化，这样使得MADDPG即可以适用于协作环境也可适用于对抗环境，如果是纯协作环境，可以考虑用全局reward来优化调试。

**Comment by yecai123** [comment]
> 

太感谢了！！！我懂了

**Comment by yecai123** [comment]
> Q1：集中式训练，分布式执行 指的是：训练时critic与actor的训练是知道全局信息的，critic需要其他智能体的策略信息，集中式学习训练指的是信息集中，而分布式执行指的是使用时actor只用知道局部信息就能运行。 Q2：示例的MADDPG代码也适用于每个agent是不同类型的（状态和动作空间不一样），可参考simple_speaker_listener的环境。
