### ISSUE TITLE
【paddle/DeprecationWarning】使用paddle创建张量时遇到NumPy的弃用警告

### ISSUE THREAD

**Issue by Senwei-Huang** [PaddlePaddle/PARL#830]
**代码：**
import paddle
print(paddle.to_tensor([0,1]))

**警告信息：**
In [13]: print(paddle.to_tensor([0,1]))
/home/senweihuang/anaconda3/lib/python3.9/site-packages/paddle/tensor/creation.py:130: **DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.** 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Tensor(shape=[2], dtype=int64, place=CPUPlace, stop_gradient=True,
       [0, 1])

**版本信息：**
Python 3.9.7
paddlepaddle 2.2.2
Ubuntu 18.04

**Comment by TomorrowIsAnOtherDay** [comment]
Hello，这是强化学习仓库PARL的issue专栏，paddle的安装和使用问题请到paddle官方仓库下进行提问。 
https://github.com/PaddlePaddle/Paddle
