### ISSUE TITLE
【paddle/W0412】验证paddle安装时有警告/错误信息

### ISSUE THREAD

**Issue by Senwei-Huang** [PaddlePaddle/PARL#831]
**代码：**
import paddle
paddle.utils.run_check()

**输出：**
In [11]: paddle.utils.run_check()
Running verify PaddlePaddle program ... 
PaddlePaddle works well on 1 CPU.
**W0412 23:16:06.400868 38450 fuse_all_reduce_op_pass.cc:76] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.**
PaddlePaddle works well on 2 CPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

**版本信息：**
Python 3.9.7
paddlepaddle 2.2.2
Ubuntu 18.04

**Comment by TomorrowIsAnOtherDay** [comment]
Hello，这是强化学习仓库PARL的issue专栏，paddle的安装和使用问题请到paddle官方仓库下进行提问。 
https://github.com/PaddlePaddle/Paddle
