### ISSUE TITLE
关于使用PARL框架实现手写汉字评价的咨询

### ISSUE THREAD

**Issue by oecy** [PaddlePaddle/PARL#834]
您好，我是一名高校的研究生，刚刚入门强化学习，也在使用PARL框架来完成自己的项目。
主要是 实现手写汉字的评价，如优良中及格等。
数据是一系列手写汉字图片。
目前的想法是使用 DQN 来完成决策系统，但是遇到了一些问题来向您咨询。
目前对于项目的构建是：
环境：其感知的数据是 标准优秀汉字灰度图 与 待评价汉字灰度图 
奖励：奖励基于待评价汉字与标准优秀汉字的各类特征的相似度，相似度越小奖励越大
动作：输出的是对这个汉字的评价 如 优良中及格。
由于这个环境下不满足马尔可夫性，动作的输出不会影响到环境的观测值（目前设计的另一个方案是 动作做出评价后，就选择对应评价组里的其他待评价同一汉字作为新的环境）
这个感觉上是强化学习的退化版，或者说是K-armed Bandit问题的拓展。
由于缺乏相关经验，请问当前的设计是否还是属于强化学习的范畴。

**Comment by TomorrowIsAnOtherDay** [comment]
hello，我们这里只讨论【框架】使用过程中遇到的问题，关于强化学习建模的讨论，请咨询身边的强化学习老师。
