### ISSUE TITLE
建议增加一个使用batch normalization的DDPG算法的例子

### ISSUE THREAD

**Issue by amocken** [PaddlePaddle/PARL#835]
我看到目前给的DDPG算法的例子是没有使用batch normalization的，但DDPG的原始论文里面使用了batch normalization。因此我建议再增加一个使用batch normalization的版本，给需要的用户一个参考

**Comment by TomorrowIsAnOtherDay** [comment]
hello，这个batch normalization确实是paper里面提及的，但是从我们的实现效果来看，并不关键，所以我们移除掉这个操作，尽可能提供精简的代码给到大家。

**Comment by amocken** [comment]
> hello，这个batch normalization确实是paper里面提及的，但是从我们的实现效果来看，并不关键，所以我们移除掉这个操作，尽可能提供精简的代码给到大家。

建议再增加一个带有batch normalization的版本，因为可能有些用户需要用到的，可以用来参考一下怎么写
