### ISSUE TITLE
不同初始状态的输出动作相同问题

### ISSUE THREAD

**Issue by djjstyle** [PaddlePaddle/PARL#837]
1、请问，初始状态不同，我想输出不同状态下最优的动作（动作空间一样）（如果最优动作的reward一样也可以输出相同动作），如何实现？
2、目前我用DQN和SAC算法，输入不同初始状态，得到的动作都是一样的，但这个动作的reward对初始状态而言不全是最优的，请问这是为什么？

**Comment by TomorrowIsAnOtherDay** [comment]
本issue只回答PARL框架使用过程中遇到的问题，不提供强化学习算法答疑，请前往合适的RL社区讨论：）
