### ISSUE TITLE
请问运行文档给的这段代码出现这种错误是怎么回事？

### ISSUE THREAD

**Issue by amocken** [PaddlePaddle/PARL#840]
https://parl.readthedocs.io/zh_CN/latest/parallel_training/setup.html
![image](https://user-images.githubusercontent.com/48198083/163822430-1f8c25f1-0d96-49e9-818d-5bc7404058f4.png)
我已经在命令行上执行了xparl start --port 6006，但运行这段代码就会出现AttributeError: 'NoneType' object has no attribute 'ZMQError'，并且执行完之后还会弹出Error: Can not import avx core while this file exists: D:\Programs\miniconda3\envs\python3_8\lib\site-packages\paddle\fluid\core_avx.pyd
![屏幕截图 2022-04-18 221008](https://user-images.githubusercontent.com/48198083/163822516-3172ad4b-6836-4309-98c6-91a50c365c00.png)
parl版本是2.0.3，paddlepaddle-gpu版本是2.1.0，Python版本是3.8.12，是在conda环境中执行

**Comment by TomorrowIsAnOtherDay** [comment]
十分感谢你的反馈。我们找个window机器测试下。

**Comment by zenghsh3** [comment]
你好，我们这边试了下，在python3.7 + parl最新版本（2.0.3）能正常运行，方便提供下你的python版本和parl版本吗？

**Comment by amocken** [comment]
> 你好，我们这边试了下，在python3.7 + parl最新版本（2.0.3）能正常运行，方便提供下你的python版本和parl版本吗？

parl版本是2.0.3，paddlepaddle-gpu版本是2.1.0，Python版本是3.8.12，是在conda环境中运行，系统是win 11 22000.613

**Comment by zenghsh3** [comment]
在python 3.8下试了也是正常运行的哈，可以尝试下使用pyzmq==18.1.1

**Comment by zenghsh3** [comment]
另外，这个错误是在程序运行完成，释放资源（__del__函数）时抛出的，可以忽略，不影响正常使用

**Comment by amocken** [comment]
> 在python 3.8下试了也是正常运行的哈，可以尝试下使用pyzmq==18.1.1

我的pyzmq版本就是18.1.1
![image](https://user-images.githubusercontent.com/48198083/163912910-f7309c03-fa3f-4688-9386-7c66f5741925.png)

**Comment by zenghsh3** [comment]
![image](https://user-images.githubusercontent.com/5762635/163913989-ac018116-5e8c-4d37-b041-e24a674c7b7c.png)
好的，这个文件的123行附近的代码能截图看下吗？

**Comment by amocken** [comment]
> ![image](https://user-images.githubusercontent.com/5762635/163913989-ac018116-5e8c-4d37-b041-e24a674c7b7c.png) 好的，这个文件的123行附近的代码能截图看下吗？

![image](https://user-images.githubusercontent.com/48198083/163914335-b53e7dda-875f-4088-910f-b9ca7380020f.png)

**Comment by zenghsh3** [comment]
看代码应该是parl最新版
由于我们这边复现不了，我们暂时也不好排查问题；
建议你可以先忽略这个问题，或可以把123行改成`except Exception`

**Comment by amocken** [comment]
> 看代码应该是parl最新版 由于我们这边复现不了，我们暂时也不好排查问题； 建议你可以先忽略这个问题，或可以把123行改成`except Exception`

那为啥我这边两台配置不同的电脑运行这个程序都有这个问题的呢？😅

**Comment by TomorrowIsAnOtherDay** [comment]
Hello，你把环境里的paddle删除掉试试看？我看你发的错误提示里有显示paddle的错误，可能是paddle安装有问题。
可以先把paddle卸载再跑上面的代码看看，这部分代码是不依赖于paddle的。

**Comment by amocken** [comment]
> Hello，你把环境里的paddle删除掉试试看？我看你发的错误提示里有显示paddle的错误，可能是paddle安装有问题。 可以先把paddle卸载再跑上面的代码看看，这部分代码是不依赖于paddle的。

果然，卸载了Paddle之后就没有这个错误
![image](https://user-images.githubusercontent.com/48198083/164701462-67e67276-5454-46e8-bfe2-4c3697759715.png)
