### ISSUE TITLE
tutorial 5

### ISSUE THREAD

**Issue by Woodeeer** [PaddlePaddle/PARL#841]
这个仿真是不是需要很长时间的训练时间，我训练了十个小时但是还没收敛，再问一下这个仿真的结束条件是啥

**Comment by rical730** [comment]
仿真结束条件是 `train_total_steps` 到达 `int(5e6)` 步时，可以通过手动修改该值来提前结束训练。

仿真的时间确实会比较长，但是是可以收敛的，关于收敛的问题可以参考 https://github.com/PaddlePaddle/PARL/issues/597 这个issue最后几段的讨论。

**Comment by Woodeeer** [comment]
谢谢您

**Comment by rical730** [comment]
可以看下这个aistudio项目，大概在25w个step的时候，就已经收敛到五六千分了。

https://aistudio.baidu.com/aistudio/projectdetail/3847018

![image](https://user-images.githubusercontent.com/11437453/164219434-454a073a-998d-4d44-8bee-9bbf14d84673.png)
