### ISSUE TITLE
parl并行计算测试代码报错：Fork support is only compatible with the epoll1 and poll polling strategies

### ISSUE THREAD

**Issue by Senwei-Huang** [PaddlePaddle/PARL#842]
# 代码：
```
import parl
import os

@parl.remote_class
class Agent(object):

    def say_hello(self):
        print("Hello World!")

    def sum(self, a, b):
        return a+b
os.system("nohup xparl start --port 8037")
os.system("xparl connect --address 192.168.30.138:8037")
parl.connect('localhost:8037')
agent = Agent()
agent.say_hello()
ans = agent.sum(1,5) # it runs remotely, without consuming any local computation resources
os.system("xparl stop")
```

# 报错：
[04-20 11:32:48 MainThread @logger.py:242] Argv: /mnt/hgfs/虚拟机/PaddleRobotics-main/QuadrupedalRobots/ETGRL/测试1.py
[04-20 11:32:49 MainThread @utils.py:73] paddlepaddle version: 2.2.2.
[04-20 11:32:51 MainThread @logger.py:242] Argv: /home/senweihuang/anaconda3/bin/xparl start --port 8037
[04-20 11:32:52 MainThread @utils.py:73] paddlepaddle version: 2.2.2.

            # The Parl cluster is started at localhost:8037.

            # A local worker with 8 CPUs is connected to the cluster.    

            # Starting the cluster monitor...

        
        ## If you want to check cluster status, please view:

            http://192.168.30.138:44097

        or call:

            xparl status

        ## If you want to add more CPU resources, please call:

            xparl connect --address 192.168.30.138:8037

        ## If you want to shutdown the cluster, please call:

            xparl stop        
        
Checking status of log_server...
E0420 11:32:58.963996278    4545 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0420 11:32:58.972060615    4545 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0420 11:32:58.978974100    4545 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0420 11:32:58.985244783    4545 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0420 11:32:58.992011234    4545 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0420 11:32:58.999181098    4545 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0420 11:32:59.006111750    4545 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
Checking status of log_server...
 Start the log server sucessfully.
/home/senweihuang/anaconda3/lib/python3.9/site-packages/flask/json/__init__.py:211: DeprecationWarning: Importing 'itsdangerous.json' is deprecated and will be removed in ItsDangerous 2.1. Use Python's 'json' module instead.
  rv = _json.dumps(obj, **kwargs)
[04-20 11:33:01 MainThread @logger.py:242] Argv: /home/senweihuang/anaconda3/bin/xparl connect --address 192.168.30.138:8037
[04-20 11:33:03 MainThread @utils.py:73] paddlepaddle version: 2.2.2.
E0420 11:33:03.926602817    4800 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0420 11:33:03.935952224    4800 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0420 11:33:03.944185369    4800 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0420 11:33:03.952740336    4800 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0420 11:33:03.961959268    4800 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0420 11:33:03.971085496    4800 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0420 11:33:03.979988196    4800 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0420 11:33:03.989888434    4800 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
Checking status of log_server...
Checking status of log_server...
Checking status of log_server...
 Fail to start the log server.
[04-20 11:33:15 MainThread @client.py:439] Remote actors log url: http://192.168.30.138:44097/logs?client_id=192.168.30.138_40299_1650425595
[04-20 11:33:16 MainThread @logger.py:242] Argv: /home/senweihuang/anaconda3/bin/xparl stop
[04-20 11:33:21 MainThread @utils.py:73] paddlepaddle version: 2.2.2.
kill: (5053): 没有那个进程
kill: (5060): 没有那个进程
kill: (5066): 没有那个进程
kill: (5072): 没有那个进程
Exception ignored in: <function RemoteWrapper.__del__ at 0x7f85f30e1af0>
Traceback (most recent call last):
  File "/home/senweihuang/anaconda3/lib/python3.9/site-packages/parl/remote/remote_wrapper.py", line 123, in __del__
AttributeError: 'NoneType' object has no attribute 'ZMQError'

Process finished with exit code 0

# 环境：
Ubuntu 18.04
python 3.9.7
paddle 2.2.2
parl 2.0.3
pyzmq 18.1.1

# 总结：两个报错、一个警告

- E0420 11:32:58.963996278    4545 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies

- AttributeError: 'NoneType' object has no attribute 'ZMQError'
- DeprecationWarning: Importing 'itsdangerous.json' is deprecated and will be removed in ItsDangerous 2.1. Use Python's 'json' module instead.
  rv = _json.dumps(obj, **kwargs)

**Comment by TomorrowIsAnOtherDay** [comment]
Hello，这个问题看起来是python版本太高，没有合适的zmq版本兼容。你可以先尝试下使用conda + py3.8的环境。
3.9的环境兼容我们近期会补全，感谢您的反馈：）

**Comment by Senwei-Huang** [comment]
产生 

> AttributeError: 'NoneType' object has no attribute 'ZMQError'

 错误的原因有两个：一是python版本太高，二是安装了paddlepaddle（但是不知道为什么不能安装）。

@TomorrowIsAnOtherDay

**Comment by Senwei-Huang** [comment]
非常感谢您的及时回复，本人打算基于国产的深度强化学习框架做机器人控制的项目，但是新手入门，遇到较多的问题，目前网上关于这方面的资料也比较少，感觉上手困难，希望得到您的帮助。@TomorrowIsAnOtherDay 

# 但是
还是有下面这个错误

> E0421 17:23:06.531817985   45839 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies

同时还有一个新错误

> ImportError: sys.meta_path is None, Python is likely shutting down

另外，调用.say_hello()方法时为什么没有输出Hello World!

# 完整输出信息
[04-21 17:23:02 MainThread @logger.py:242] Argv: /mnt/hgfs/虚拟机/PaddleRobotics-main/QuadrupedalRobots/ETGRL/测试1.py
[04-21 17:23:03 MainThread @__init__.py:37] WRN No deep learning framework was found, but it's ok for parallel computation.
2.0.3
[04-21 17:23:03 MainThread @logger.py:242] Argv: /home/senweihuang/anaconda3/envs/parl/bin/xparl start --port 8037
[04-21 17:23:04 MainThread @__init__.py:37] WRN No deep learning framework was found, but it's ok for parallel computation.

            # The Parl cluster is started at localhost:8037.

            # A local worker with 8 CPUs is connected to the cluster.    

            # Starting the cluster monitor...

        
        ## If you want to check cluster status, please view:

            http://192.168.30.141:39287

        or call:

            xparl status

        ## If you want to add more CPU resources, please call:

            xparl connect --address 192.168.30.141:8037

        ## If you want to shutdown the cluster, please call:

            xparl stop        
        
E0421 17:23:06.531817985   45839 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0421 17:23:06.536868863   45839 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0421 17:23:06.544956367   45839 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0421 17:23:06.551351612   45839 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0421 17:23:06.556963576   45839 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0421 17:23:07.683243382   46137 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0421 17:23:07.688480555   46137 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0421 17:23:07.694671904   46137 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0421 17:23:07.701076750   46137 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0421 17:23:07.709953334   46137 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0421 17:23:07.717589249   46137 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0421 17:23:07.724079492   46137 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0421 17:23:07.732771682   46137 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
Checking status of log_server...
 Start the log server sucessfully.
[04-21 17:23:08 MainThread @logger.py:242] Argv: /home/senweihuang/anaconda3/envs/parl/bin/xparl connect --address 192.168.30.141:8037
[04-21 17:23:09 MainThread @__init__.py:37] WRN No deep learning framework was found, but it's ok for parallel computation.
E0421 17:23:10.542860914   46406 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0421 17:23:10.548620974   46406 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0421 17:23:10.553172264   46406 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0421 17:23:10.557855550   46406 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0421 17:23:10.563943203   46406 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0421 17:23:10.569450370   46406 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0421 17:23:10.575769917   46406 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0421 17:23:10.580918192   46406 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
Checking status of log_server...
 Start the log server sucessfully.
[04-21 17:23:12 MainThread @client.py:439] Remote actors log url: http://192.168.30.141:39287/logs?client_id=192.168.30.141_37167_1650532992
E0421 17:23:13.011117462   46705 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0421 17:23:13.031688764   46705 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0421 17:23:13.038102109   46705 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0421 17:23:13.044567352   46705 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0421 17:23:13.050223416   46705 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0421 17:23:13.055055999   46705 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0421 17:23:13.058959104   46705 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
E0421 17:23:13.064408772   46705 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
*********
6
[04-21 17:23:14 MainThread @logger.py:242] Argv: /home/senweihuang/anaconda3/envs/parl/bin/xparl stop
[04-21 17:23:20 MainThread @__init__.py:37] WRN No deep learning framework was found, but it's ok for parallel computation.
kill: (46930): 没有那个进程
kill: (46961): 没有那个进程
kill: (46967): 没有那个进程
kill: (46973): 没有那个进程
Exception ignored in: <function RemoteWrapper.__del__ at 0x7fe394699940>
Traceback (most recent call last):
  File "/home/senweihuang/anaconda3/envs/parl/lib/python3.8/site-packages/parl/remote/remote_wrapper.py", line 118, in __del__
  File "/home/senweihuang/anaconda3/envs/parl/lib/python3.8/site-packages/zmq/sugar/socket.py", line 475, in recv_multipart
  File "zmq/backend/cython/socket.pyx", line 791, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 827, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 191, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/socket.pyx", line 186, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/checkrc.pxd", line 18, in zmq.backend.cython.checkrc._check_rc
ImportError: sys.meta_path is None, Python is likely shutting down

Process finished with exit code 0


# 环境：

Ubuntu 18.04
python 3.8
parl 2.0.3

**Comment by TomorrowIsAnOtherDay** [comment]
hello，可以尝试下先开2个CPU节点看看，看log像开的节点数太多。
`xparl start --cpu_num 2`

------------------


为什么不输出hello，因为那行代码不在本进程执行，不会输出到终端。

**Comment by Senwei-Huang** [comment]
您好，开2个节点和1个节点我都试了，还是这两个问题。

> Fork support is only compatible with the epoll1 and poll polling strategies
> ImportError: sys.meta_path is None, Python is likely shutting down

# 代码
```
import parl
import os

@parl.remote_class
class Agent(object):

    def say_hello(self):
        print("Hello World!")

    def sum(self, a, b):
        return a+b
print(parl.__version__)
os.system("nohup xparl start --port 8037 --cpu_num 2")
os.system("xparl connect --address 192.168.30.141:8037")
parl.connect('localhost:8037')
agent = Agent()
agent.say_hello()
print('*********')
ans = agent.sum(1,5) # it runs remotely, without consuming any local computation resources
print(ans)
os.system("xparl stop")
```
@TomorrowIsAnOtherDay

**Comment by TomorrowIsAnOtherDay** [comment]
尝试下这个命令：
`pip install grpcio<=1.43.0` 

https://github.com/pulumi/pulumi/issues/9133

**Comment by Senwei-Huang** [comment]
# 牛！！！
解决了下面这个问题

> Fork support is only compatible with the epoll1 and poll polling strategies

但还是出现下面的错误，请问有没有解决的建议，非常感谢您！！！

> ImportError: sys.meta_path is None, Python is likely shutting down

# 完整错误信息：
[04-21 19:49:57 MainThread @logger.py:242] Argv: /home/senweihuang/anaconda3/envs/parl/bin/xparl stop
[04-21 19:49:58 MainThread @__init__.py:37] WRN No deep learning framework was found, but it's ok for parallel computation.
kill: (57058): 没有那个进程
kill: (57064): 没有那个进程
kill: (57070): 没有那个进程
kill: (57076): 没有那个进程
Exception ignored in: <function RemoteWrapper.__del__ at 0x7f5b2e410160>
Traceback (most recent call last):
  File "/home/senweihuang/anaconda3/envs/parl/lib/python3.8/site-packages/parl/remote/remote_wrapper.py", line 118, in __del__
  File "/home/senweihuang/anaconda3/envs/parl/lib/python3.8/site-packages/zmq/sugar/socket.py", line 475, in recv_multipart
  File "zmq/backend/cython/socket.pyx", line 791, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 827, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 191, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/socket.pyx", line 186, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/checkrc.pxd", line 18, in zmq.backend.cython.checkrc._check_rc
ImportError: sys.meta_path is None, Python is likely shutting down

Process finished with exit code 0


@TomorrowIsAnOtherDay

**Comment by TomorrowIsAnOtherDay** [comment]
你的pyzmq版本是多少呢？

**Comment by Senwei-Huang** [comment]
pyzmq 18.1.1

@TomorrowIsAnOtherDay

**Comment by TomorrowIsAnOtherDay** [comment]
看着都挺正常的，你这个conda环境是从3.9降级到3.8的？还是直接重新3.8 安装的呢？

**Comment by Senwei-Huang** [comment]
直接重新3.8 安装吧，因为我是新建了一个python3.8的conda虚拟环境，原来anaconda的python3.9的base环境没动。

@TomorrowIsAnOtherDay

**Comment by TomorrowIsAnOtherDay** [comment]
似乎还是grpc的问题，试试这个
`pip install --upgrade grpcio==1.43.0 `

**Comment by Senwei-Huang** [comment]
我当前grpcio的版本正是1.43.0的

```
(parl) senweihuang@senweihuang-virtual-machine:/mnt/hgfs/虚拟机/PaddleRobotics-main$ pip install --upgrade grpcio==1.43.0
Requirement already satisfied: grpcio==1.43.0 in /home/senweihuang/anaconda3/envs/parl/lib/python3.8/site-packages (1.43.0)
Requirement already satisfied: six>=1.5.2 in /home/senweihuang/anaconda3/envs/parl/lib/python3.8/site-packages (from grpcio==1.43.0) (1.16.0)
```
@TomorrowIsAnOtherDay

**Comment by TomorrowIsAnOtherDay** [comment]
hello，请使用如下命令导出python环境，明天我们尝试复现下:
```shell
conda env export > env.yaml
cat env.yaml
```

**Comment by Senwei-Huang** [comment]
我导出来了，但是不知道怎么发给您。我上传到了百度网盘，您看看能不能下载，麻烦您了。
链接：https://pan.baidu.com/s/1teVKySDG4Ajmkucfd75uMg 
提取码：nkq6

**Comment by TomorrowIsAnOtherDay** [comment]
我发现问题了，先说下结论，目前代码是正常运行的，这个报错也是合理的。
主要问题在于PARL的并行使用方式，PARL的集群启动应该在终端执行。
目前你在python代码执行xparl stop，会直接杀掉所有并行进程，导致不可预期的错误。

**Comment by Senwei-Huang** [comment]
确实，在终端执行就没报错了，完美解决。再次感谢耐心解答！！！
