### ISSUE TITLE
离散动作空间predict（）输出

### ISSUE THREAD

**Issue by dx3906123** [PaddlePaddle/PARL#843]
你好~
我是在parl的MADDPG算法基础上改进，结合自己的多智能体仿真环境训练的，其中我定义的一个智能体动作空间是Discrete(3,)，在train.py的run_episode()中执行到action_n = [agent.predict(obs) for agent, obs in zip(agents, obs_n)]这一步时，我想输出看一下每个智能体act的情况，如下所示，
```
def predict(self, obs, use_target_model=False):
        obs = paddle.to_tensor(np.array(obs).reshape(1, -1), dtype='float32')
        act = self.alg.predict(obs, use_target_model=use_target_model)
        print(act)
        act_numpy = act.detach().cpu().numpy().flatten()
        return act_numpy
```
我的任务中动作空间是，0：前进，1：左转，2：后退，我以为定义了Discrete(3,)，它会输出0或者1或者2，但发现是这里的act输出是三个小数，然后我选择了三个小数中最大的数对应的序列号为动作，请问可以这样处理吗？如果这样不对，请问有别的方法吗？
祝PARL越来越好~

**Comment by TomorrowIsAnOtherDay** [comment]
hello，如果询问使用问题建议先关注下PARL 仓库：）

**Comment by dx3906123** [comment]
哈哈哈哈用github不多，还不太会，已经star啦

**Comment by rical730** [comment]
> 但发现是这里的act输出是三个小数，然后我选择了三个小数中最大的数对应的序列号为动作，请问可以这样处理吗？


可以的，对于离散动作空间来说，MADDPG的输出就是需要按照你这种方式处理的，只是这部分的转换在 openai 论文提供的mpe环境里做了处理，所以MADDPG只需要输出3个浮点数即可。

**Comment by dx3906123** [comment]
原来是这样，明白了，非常感谢。
另外想问一下，如果训练中断了，想要继续接着之前保存的模型训练，我把args.restore设置为True，另外把save model那里的if判断注释了，如下：
```
# save model
#if not args.restore:
model_dir = args.model_dir
os.makedirs(os.path.dirname(model_dir), exist_ok=True)
for i in range(len(agents)):
    model_name = '/agent_' + str(i)
    agents[i].save(model_dir + model_name)
```
这样是实现了接续前面的模型继续训练的效果吗？但是这样log好像就会被替代，而不能连着前面的。

**Comment by rical730** [comment]
是的，你这样处理是没问题的，可以加载前面的模型继续训练，重启训练后log确实是无法连着前面的，因为是一份训练对应一份日志，total_episodes是从0开始计数。或者你也可以考虑修改total_episodes的初始值。

**Comment by dx3906123** [comment]
嗯嗯，明白了，谢谢
还有一个疑问，就是我在用tensorboard --logdir显示loss曲线时出现了问题，提示"No dashboards are active for the current data set."为方便描述问题，假设我将train_log放在桌面，目录结构为desktop/train_log/3vs1/，3vs1文件夹中包含两个文件，分别为events.out.tfevents.1650460573.LAPTOP-05298KL9，以及log.log
命令行输入如下：
```
(paddle2.2cuda11.1) C:\Users\14032\Desktop>tensorboard --logdir==./train_log/3vs1
TensorFlow installation not found - running with reduced feature set.
TensorBoard 1.15.0a20190801 at http://LAPTOP-05298KL9:6006/ (Press CTRL+C to quit)
```
但是打开网站显示"No dashboards are active for the current data set."，请问我这样处理有什么问题吗或者可能是什么原因导致这样呢？小白还想问问，tensorboard可视化，是根据log文件还是events.out.tfevents.文件呢？

**Comment by dx3906123** [comment]
我可能找到原因了，之前的train_log文件训练时，为了继续训练，

> 我把args.restore设置为True，另外把save model那里的if判断注释了
```
    # show model effect without training
        if args.restore and args.show:
            continue

        # learn policy
        for i, agent in enumerate(agents):
            critic_loss = agent.learn(agents)
            if critic_loss != 0.0:
                summary.add_scalar('critic_loss_%d' % i, critic_loss,
                                   agent.global_train_step)
```
但我同时把args.show设置为True了，所以没有执行learn policy部分，是因为这个原因吗？

**Comment by rical730** [comment]
1. tensorboard的可视化是根据events文件的。
2. 渲染动画会导致训练速度变慢很多，不太建议边训边看，如果有边训边看渲染的需求可以自行注释掉这两行代码
```
if args.restore and args.show:
            continue
```
3. 如果没有执行 `summary.add_scalar('critic_loss_%d' % i, critic_loss,agent.global_train_step)`这行代码，也就看不到loss曲线。

**Comment by dx3906123** [comment]
明白了，非常感谢
请问events文件一般什么时候生成呢？我刚刚注释掉这两行代码后
```
if args.restore and args.show:
            continue
```
目前已经重新训练了106个episode，并且设置的`STAT_RATE=100`，train_log文件夹中生成了log文件，但还没有events文件，请问是有什么问题吗？我比较担心运行了很久但其实还是没有训练到。

**Comment by dx3906123** [comment]
抱歉，我好像问了个傻问题，根据下面两行代码
```
if self.rpm.size() <= self.min_memory_size:
            return 0.0
```
```
# learn policy
        for i, agent in enumerate(agents):
            critic_loss = agent.learn(agents)
            if critic_loss != 0.0:
                summary.add_scalar('critic_loss_%d' % i, critic_loss,
                                   agent.global_train_step)
```
以及相关参数设置
```
agents_n=3
BATCH_SIZE = 1024
MAX_EPISODES = 10000  # stop condition:number of episodes
MAX_STEP_PER_EPISODE = 30  # maximum step per episode
STAT_RATE = 100  # statistical interval of save model or count reward

self.min_memory_size = batch_size * 25  
```
那就是要在episode约等于batch_size * 25/agents_n/MAX_STEP_PER_EPISODE的时候，才会有`critic_loss != 0.0`成立，执行`summary.add_scalar('critic_loss_%d' % i, critic_loss,agent.global_train_step)`，生成events文件，我这样理解对吗？
另外想问问对于`BATCH_SIZE`、`MAX_EPISODES` 、`MAX_STEP_PER_EPISODE`、`STAT_RATE`等参数的设置有什么建议吗？

**Comment by TomorrowIsAnOtherDay** [comment]
太case-by-case的问题请自行解决，issue主要是用来解答框架使用问题.

**Comment by dx3906123** [comment]
好的，了解了，非常感谢你们的解答~

**Comment by djjstyle** [comment]
请问Discrete(3,)形式的数据您是怎么自定义得到的？我自定义列表形式的数据会报错

**Comment by dx3906123** [comment]
大概是这样
```
from gym.spaces import Discrete
from gym.spaces import Box
class Pre(object): 
    def __init__(self):  
        self.n = 3#训练的agent数量
        self.obs_shape_n = [7,7,7]#每个agent的observation空间大小
        self.act_shape_n = [6,6,6]#每个agent的动作空间大小
        self.observation_space = [Box(-1, 1, (7,), np.float32), Box(-1, 1, (7,), np.float32), Box(-1, 1, (7,), np.float32)]
        self.action_space = [Discrete(6,), Discrete(6,), Discrete(6,)]
```

> 请问Discrete(3,)形式的数据您是怎么自定义得到的？我自定义列表形式的数据会报错

**Comment by haotiantianya** [comment]
> 你好~ 我是在parl的MADDPG算法基础上改进，结合自己的多智能体仿真环境训练的，其中我定义的一个智能体动作空间是Discrete(3,)，在train.py的run_episode()中执行到action_n = [agent.predict(obs) for agent, obs in zip(agents, obs_n)]这一步时，我想输出看一下每个智能体act的情况，如下所示，
> 
> ```
> def predict(self, obs, use_target_model=False):
>         obs = paddle.to_tensor(np.array(obs).reshape(1, -1), dtype='float32')
>         act = self.alg.predict(obs, use_target_model=use_target_model)
>         print(act)
>         act_numpy = act.detach().cpu().numpy().flatten()
>         return act_numpy
> ```
> 
> 我的任务中动作空间是，0：前进，1：左转，2：后退，我以为定义了Discrete(3,)，它会输出0或者1或者2，但发现是这里的act输出是三个小数，然后我选择了三个小数中最大的数对应的序列号为动作，请问可以这样处理吗？如果这样不对，请问有别的方法吗？ 祝PARL越来越好~

**Comment by haotiantianya** [comment]
你好，我想请问一下，我看了maddpg官网环境用了multidiscrete，把min和max设为0和4，发现它输出的是一组9维的小数，这个时候它怎么确定动作呢？
