### ISSUE TITLE
Aircraft

### ISSUE THREAD

**Issue by Mealoore** [PaddlePaddle/PARL#845]
what's the enviroment of Aircraft.gif in the file https://github.com/PaddlePaddle/PARL/README.md, and which paper is it in?

**Comment by TomorrowIsAnOtherDay** [comment]
Please refer to the paper published in CoRL: Intervention Aided Reinforcement Learning for Safe and Practical Policy Optimization in Navigation

**Comment by Mealoore** [comment]
Thanks a lot, is it open source?Where is the code?The link is not valid.

**Comment by TomorrowIsAnOtherDay** [comment]
Sorry, the code is not available. You can try reproduce the algorithm following the paper.
