### ISSUE TITLE
运行QuickStart出问题，是怎么回是

### ISSUE THREAD

**Issue by 13682191915** [PaddlePaddle/PARL#846]
![报错](https://user-images.githubusercontent.com/68330914/165126372-200fe978-4ce9-4e49-9840-6db02ef0b7b9.png)

**Comment by TomorrowIsAnOtherDay** [comment]
hello，看来你跑的代码比较久，你这版本的代码需要静态图paddle，建议重新下载最新版本PARL的代码

**Comment by 13682191915** [comment]
> 

谢谢，解决问题了。
