### ISSUE TITLE
运行例子报错

### ISSUE THREAD

**Issue by 13682191915** [PaddlePaddle/PARL#847]
运行QuickStart/train.py报一下错误，自己的环境信息在图片中
D:\ANACONDA\envs\parl\python.exe G:/PARL1/examples/QuickStart/train.py
[04-26 08:29:10 MainThread @logger.py:242] Argv: G:/PARL1/examples/QuickStart/train.py
D:\ANACONDA\envs\parl\lib\site-packages\paddle\vision\transforms\functional_pil.py:36: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  'nearest': Image.NEAREST,
D:\ANACONDA\envs\parl\lib\site-packages\paddle\vision\transforms\functional_pil.py:37: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  'bilinear': Image.BILINEAR,
D:\ANACONDA\envs\parl\lib\site-packages\paddle\vision\transforms\functional_pil.py:38: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  'bicubic': Image.BICUBIC,
D:\ANACONDA\envs\parl\lib\site-packages\paddle\vision\transforms\functional_pil.py:39: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead.
  'box': Image.BOX,
D:\ANACONDA\envs\parl\lib\site-packages\paddle\vision\transforms\functional_pil.py:40: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  'lanczos': Image.LANCZOS,
D:\ANACONDA\envs\parl\lib\site-packages\paddle\vision\transforms\functional_pil.py:41: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead.
  'hamming': Image.HAMMING
[04-26 08:29:12 MainThread @utils.py:79] WRN paddlepaddle version: 2.2.2. The dynamic graph version of PARL is under development, not fully tested and supported
Traceback (most recent call last):
  File "G:/PARL1/examples/QuickStart/train.py", line 22, in <module>
    from cartpole_agent import CartpoleAgent
  File "G:\PARL1\examples\QuickStart\cartpole_agent.py", line 18, in <module>
    from parl import layers
ImportError: cannot import name 'layers' from 'parl' (G:\PARL1\parl\__init__.py)
![ku](https://user-images.githubusercontent.com/68330914/165195961-f338ae28-6d67-43a0-b0e7-4b524093f75c.png)

**Comment by TomorrowIsAnOtherDay** [comment]
你这个问题和上一个issue一样，你下载的PARL代码太旧了，这个版本还依赖于静态图paddle。
