### ISSUE TITLE
请问MADDPG那个例子里面的speedup的具体作用是啥？

### ISSUE THREAD

**Issue by amocken** [PaddlePaddle/PARL#849]
![image](https://user-images.githubusercontent.com/48198083/165652760-68af94fb-0835-416f-82ce-2999d12fe078.png)

**Comment by rical730** [comment]
噢这个参数是在静态图里起到加速底层fluid计算的作用，迁移到动态图框架后，这个参数其实已经失效了，可以删除，感谢指出，我们fix一下。
