### ISSUE TITLE
dqn图形化界面

### ISSUE THREAD

**Issue by wahaha23333333** [PaddlePaddle/PARL#851]
在https://github.com/PaddlePaddle/PARL/tree/develop/examples/tutorials/parl2_dygraph/lesson3/dqn 里面进行python train.py，为什么看不到图形化界面，就是看不到杆子的动画，只在cmd里有显示运行结果代码？
<img width="629" alt="image" src="https://user-images.githubusercontent.com/104571636/165754928-8a069531-4202-4136-9b7f-672ef68416e1.png">

**Comment by rical730** [comment]
你好，在train.py的第126行手动修改render=True，就可以看到每隔一段时间评估的动画，默认render是False

https://github.com/PaddlePaddle/PARL/blob/develop/examples/tutorials/parl2_dygraph/lesson3/dqn/train.py#L126

**Comment by wahaha23333333** [comment]
非常非常感谢！

**Comment by rical730** [comment]
不客气 ^_^，欢迎关注PARL仓库~觉得不错可以点个star
