### ISSUE TITLE
请问MADDPG的总奖励在哪看？

### ISSUE THREAD

**Issue by djjstyle** [PaddlePaddle/PARL#853]
这是MADDPG的部分代码，我只看到每个agent各自的奖励，没看到他们共同作用产生的奖励
def run_episode(env, agents):
    obs_n = env.reset()#先尝试得到了四个初始状态
    total_reward = 0
    agents_reward = [0 for _ in range(env.n)]#用于存储每个agent的奖励
    steps = 0
    while True:
        steps += 1
        action_n = [agent.predict(obs) for agent, obs in zip(agents, obs_n)]
        #zip返回元组列表，action_n是包含四个动作的列表[a,b,c,d]
        next_obs_n, reward_n, done_n, _ = env.step(action_n)#将动作输入到环境中
        done = all(done_n)
        terminal = (steps >= MAX_STEP_PER_EPISODE)#是否是最后一个动作

**Comment by TomorrowIsAnOtherDay** [comment]
MADDPG 的算法只通过单个智能体的奖励进行更新，相关的配套环境也没有提供总奖励。
另外，QMIX是针对总奖励进行训练的，你可以参考下它的环境。
