### ISSUE TITLE
请问我为什么装不了parl2.0.3以上版本的工具包？我的环境是python3.8

### ISSUE THREAD

**Issue by djjstyle** [PaddlePaddle/PARL#854]

**Comment by TomorrowIsAnOtherDay** [comment]
系统版本是？

**Comment by rical730** [comment]
目前parl最高版本就是2.0.3， 由于我们在MADDPG做了兼容连续动作空间的升级，才把MADDPG的依赖包要求改成 parl>2.0.3，如果想要尝试运行最新版的MADDPG，暂时可以通过源码安装PARL，下载PARL后在根目录下`pip install .`

**Comment by djjstyle** [comment]
好的谢谢，我还有一个问题：在MADDPG里，我自定义一个动作空间，是二维列表，报错AssertionError: act_space must be instance of  gym.spaces.Discrete or multiagent.multi_discrete.MultiDiscrete，我看了一下示例的act_space形式是[Discrete(3), Discrete(5)]，这是怎么得到的？或者说我如何自定义得到这个形式的act_space？

**Comment by rical730** [comment]
gym.spaces.Discrete 是 gym 规范下的离散动作 action space，相关的使用和构造可以查询openAI的gym官网。

**Comment by djjstyle** [comment]
非常感谢，我已解决问题

**Comment by rical730** [comment]
parl 2.0.4 版本已发布，欢迎使用最新版本的parl 体验最新版的 MADDPG
