### ISSUE TITLE
在MADDPG中，动作空间act_space是[Discrete(3), Discrete(5)]，请问这种类型的数据我如何自定义得到？或者是否可以用别的类型的数据平替？

### ISSUE THREAD

**Issue by djjstyle** [PaddlePaddle/PARL#855]
我将act_space自定义的列表形式的数据会报错：AssertionError: act_space must be instance of             gym.spaces.Discrete or multiagent.multi_discrete.MultiDiscrete

**Comment by TomorrowIsAnOtherDay** [comment]
关于gym的动作定义问题，去gym官方仓库下提问更合适。
