### ISSUE TITLE
ImportError: cannot import name 'layers' from 'parl' (E:\ProgramData\Anaconda3\envs\pythonProject3\lib\site-packages\parl\__init__.py)

### ISSUE THREAD

**Issue by young-shy** [PaddlePaddle/PARL#867]
你好，采用的parl2.0.2（win10）

**Comment by young-shy** [comment]
你好，采用的Python3.8，paddlepaddle==2.1.2，parl==2.0,2（win10），请问有什么不妥之处吗？

**Comment by shy520520** [comment]
> 你好，采用的parl2.0.2（win10）

**Comment by young-shy** [comment]
运行的是这个案例来着https://github.com/PaddlePaddle/PARL/tree/develop/examples/tutorials/parl2_dygraph/lesson3/dqn

**Comment by TomorrowIsAnOtherDay** [comment]
能截图看下更多的错误提示吗？这个错误提示一般是安装了旧版本的paddle，但是看你的版本号又是正确的。

**Comment by young-shy** [comment]
已解决，谢谢

**Comment by TomorrowIsAnOtherDay** [comment]
具体是什么原因导致的呢？可以分享下吗？
