### ISSUE TITLE
关于教学课程tutorials/parl2_dygraph/lesson5/homework/ddpg_quadrotor/train.py  /训练次数和环境设计问题

### ISSUE THREAD

**Issue by AngryovoCsr** [PaddlePaddle/PARL#871]
训练循环条件为，如下
while total_steps < args.train_total_steps:
参数默认为为5e6次，如下
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--train_total_steps",
        default=5e6,
        type=int,
        help='Max time steps to run environment')
args = parser.parse_args()

请问：1、为什么我运行时total steps已经超过了50w次还没有停止？
           2、另外这个demo的环境的reward设计原则是：悬停越久越好；能量损耗越久越好；离初始位置越近越好在代码层面体现在哪 
                里呢?PaddlePaddle/MetaGym/metagym/quadrotor的环境设计没读懂

**Comment by TomorrowIsAnOtherDay** [comment]
第一个问题有log证明“total steps已经超过了50w次还没有停止”吗？把log提供下给我们看看。
第二个问题：悬停越久越好体现在healthy_score，https://github.com/PaddlePaddle/MetaGym/blob/3b4551219b86c8c267d593dd4e15e84a6366e976/metagym/quadrotor/env.py#L225

**Comment by AngryovoCsr** [comment]
非常感谢回答。
1、日志已上传
[train_log (2).zip](https://github.com/PaddlePaddle/PARL/files/8715644/train_log.2.zip)
2、在这里反映一个很久之前遇到的关于paddle的问题，安装paddle时，官方文档“GPU的paddle，对于 CUDA 11.2，需要搭配cuDNN 8.1.1”，而目前nvdia的官网对于 CUDA 11.2，只有cudnn8.4版本的文件，我安装了这个版本的cudnn，在训练的时候却出现如下情况，提示我安装的是cudnn8.1版本，而paddle依赖的是8.2版本，请问问题出在了哪里
![3](https://user-images.githubusercontent.com/105338544/169025017-3eb927aa-c61e-4405-9286-ee389e52deee.PNG)

**Comment by TomorrowIsAnOtherDay** [comment]
5e6是500w...你的log只跑了不到100w，当然没有停下来。
paddle的问题请到paddle官方仓库提issue: https://github.com/PaddlePaddle/Paddle/issues

**Comment by AngryovoCsr** [comment]
感谢耐心回答。犯了低级错误，5e6反应成50w次了，直接思维定式了
