### ISSUE TITLE
这里写错了啊

### ISSUE THREAD

**Issue by amocken** [PaddlePaddle/PARL#875]
https://github.com/PaddlePaddle/PARL/tree/develop/examples/tutorials/parl2_dygraph/lesson5/ddpg/train.py
![image](https://user-images.githubusercontent.com/48198083/168753201-3e50f95a-c8b1-442e-b665-d98a6811a42b.png)
😅

**Comment by rical730** [comment]
感谢指出😂，确实大意了

**Comment by rical730** [comment]
修复PR已合入，本issue先关闭了，若使用PARL的过程中还有其他问题，欢迎提新issue指出
