### ISSUE TITLE
这里提示部分没改过来

### ISSUE THREAD

**Issue by amocken** [PaddlePaddle/PARL#876]
https://github.com/PaddlePaddle/PARL/blob/develop/parl/algorithms/paddle/maddpg.py
这里漏写了DiagGaussianDistribution
![image](https://user-images.githubusercontent.com/48198083/168753681-18b3518d-db77-48f9-ad7d-def2e317ce97.png)
这里漏写了gym.spaces.Box
![image](https://user-images.githubusercontent.com/48198083/168753952-b77a1e0a-e9bd-4866-bbb4-570eddd297e2.png)

**Comment by rical730** [comment]
收到，感谢提醒，我们马上fix一下

**Comment by rical730** [comment]
修复PR已合入，文档部分已更新，AssertionError部分的提示下一个版本会生效，但不影响目前版本2.0.4兼容 gym.spaces.Box
