### ISSUE TITLE
这里写重复了

### ISSUE THREAD

**Issue by amocken** [PaddlePaddle/PARL#881]
https://github.com/PaddlePaddle/PARL/blob/develop/examples/tutorials/parl2_dygraph/lesson5/ddpg/train.py
![image](https://user-images.githubusercontent.com/48198083/169760701-712adcc1-ce0e-419d-b186-4821d5a5ca82.png)
😅

**Comment by TomorrowIsAnOtherDay** [comment]
十分感谢你的反馈，这个您可以尝试自己发PR修复哈：）

**Comment by TomorrowIsAnOtherDay** [comment]
这样您也能成为PARL的contributor了哈哈哈哈

**Comment by amocken** [comment]
> 这样您也能成为PARL的contributor了哈哈哈哈

我对提交代码方面不熟悉😂

**Comment by TomorrowIsAnOtherDay** [comment]
其实就是删两行代码提交PR即可，我们来操作下，再次感谢反馈：）

**Comment by TomorrowIsAnOtherDay** [comment]
fixed in #882
