### ISSUE TITLE
运行https://github.com/PaddlePaddle/PARL/blob/develop/examples/DQN_variant/train.py 引用库出问题

### ISSUE THREAD

**Issue by A5230171** [PaddlePaddle/PARL#884]
在上述链接的train.py中，第20行
from parl.utils import logger, summary
引用 logger.py、summary.py 

但后续的 使用 summary.add_scalar() 时，显示没有该函数。
错误讯息：在 'summary.py' 中找不到引用 'add_scalar' 

使用 logger.info() 时，也显示没有该函数。
错误讯息：在 'logger.py' 中找不到引用 'info'

**Comment by TomorrowIsAnOtherDay** [comment]
感谢反馈，请提供下PARL、python版本信息还有系统信息。

**Comment by A5230171** [comment]
Python = 3.6 
PARL = 2.0.4
paddlepaddle = 2.3.0

系统信息：Windows10 
處理器	Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz   3.70 GHz
已安裝記憶體(RAM)	32.0 GB (31.7 GB 可用)

**Comment by A5230171** [comment]
我有看了一下 logger.py、summary.py 代码

貌似没有看到有对应的 function 诶，不知道是否我看得不对，请再指教我，谢谢！

**Comment by TomorrowIsAnOtherDay** [comment]
请提供下运行如下代码的错误提示：
```python
from parl.utils import logger
logger.info("Hello world!")
```

**Comment by TomorrowIsAnOtherDay** [comment]
logger.py 在这个路径，你可以确认下你本地对应路径是否有代码的。
https://github.com/PaddlePaddle/PARL/blob/develop/parl/utils/logger.py

**Comment by A5230171** [comment]
> logger.py 在这个路径下，你可以确认下你本地路径是否有代码的。 https://github.com/PaddlePaddle/PARL/blob/develop/parl/utils/logger.py

您好，向你报告最新的进展：

我有在AI Studio 上测试了上面logger.py、summary.py的相关代码，的确是可以正常运行的。

然后我尝试将 python3.6 更换为 python3.7 后，Pycharm 编译器虽然显示异常，但可以正常运行是OK的。

**Comment by TomorrowIsAnOtherDay** [comment]
你使用的是conda环境吗？建议你使用conda 环境安装parl，这是Windows下我们推荐的安装方式。

**Comment by A5230171** [comment]
> 你使用的是conda环境吗？建议你使用conda 环境安装parl，这是Windows下我们推荐的安装方式。

谢谢，是的，是用conda安装的。

**Comment by TomorrowIsAnOtherDay** [comment]
你可以在终端上测试下代码吗？感觉像是pycharm的问题。
