### ISSUE TITLE
关于本地运行程序无法生成【vdlrecords.xxxx.log】档的疑问

### ISSUE THREAD

**Issue by A5230171** [PaddlePaddle/PARL#888]
您好，请问一下，

我在AI Studio上运行代码，能够顺利的在 train_log/train 目录底下生成：
log.log
vdlrecords.xxxx.log

而在本地的Pycharm上运行，只能在本地的train_log/train 目录底下生成：
log.log
events.out.tfevents.1653862330.DESKTOP-CH9OB8T

好像没有生成日志档，请问怎么处理，才能在本地生成 vdlrecords 档呢？

**Comment by TomorrowIsAnOtherDay** [comment]
本地得要安装visuldl 才可以生成的，目前默认使用的是tensorboard。

**Comment by A5230171** [comment]
> tensorboard

明白啦，謝謝！已解決我的疑問
