### ISSUE TITLE
关于分布式的PPO

### ISSUE THREAD

**Issue by allendred** [PaddlePaddle/PARL#889]
PPO的分布式有两种做法,一种是像a3c一样分别做梯度,然后聚合,另一种是只用分布式采样,然后交给主agent更新,后一种的gae该怎么计算呢,是应该把所有分布式采样的轨迹拼起来做gae,还是应该分别做,然后放一起做训练呢

**Comment by TomorrowIsAnOtherDay** [comment]
后者，可以等每个节点单独跑完一个episode，各自算GAE。
