### ISSUE TITLE
关于ddpg算法输出动作值约束问题

### ISSUE THREAD

**Issue by young-shy** [PaddlePaddle/PARL#893]
你好，请问，是否应该对图中划线部分的动作输出值加以约束呢？
![image](https://user-images.githubusercontent.com/71912372/172512925-51935d3c-6c98-48d0-a801-6b59fe7f3a93.png)

**Comment by rical730** [comment]
不需要的，Actor的最后一层网络已经用了tanh激活函数限制输出范围了

**Comment by young-shy** [comment]
如果动作输出范围不在tanh激活函数范围[-1,1]呢？

**Comment by young-shy** [comment]
是否应该在图片中对应位置添加约束呢？

**Comment by TomorrowIsAnOtherDay** [comment]
我们一般的做法是，policy里增加tanh作为激活函数，把输出限制在【-1，1】。
然后再后处理把【-1，1】这个区间映射到当前场景所需要的区间。
举个例子，当前场景要求是【-5，5】，那我把policy输出的action * 5就可以了。

**Comment by young-shy** [comment]
好的，谢谢
