### ISSUE TITLE
关于DDPG调参问题

### ISSUE THREAD

**Issue by young-shy** [PaddlePaddle/PARL#896]
一般情况下，经验池容量、小批量数据量、训练前的预存数据量、每个step的奖励值范围等参数有什么参考的设计方法吗?
在使用DDPG的过程中，发现训练了大概一百多个episode后奖励值就基本不发生变化了，并且显然不是最优的结果，想来可能是参数的问题。

**Comment by TomorrowIsAnOtherDay** [comment]
建议使用原始paper里的超参数设定，现在很多算法在发表时候就附上了超参数设定作为参考。

**Comment by young-shy** [comment]
好的，感谢
