### ISSUE TITLE
parl 2.2.0 SAC无法调用

### ISSUE THREAD

**Issue by yufeng-Lu520** [PaddlePaddle/PARL#897]
debug PARL/example/SAC/train.py 
在sitepackage里的sac.py里增加print输出任意字符，发现都没有输出。所以这个算法有调用sac.py吗，如果有的话为什么断点设置在sac.py里无法断呢

**Comment by TomorrowIsAnOtherDay** [comment]
sac.py 有好几个版本的，你确定得确定改的是paddle版本的。
这里面集合了fluid（静态图）、torch、paddle（动态图），你得改paddle目录下的sac.py
https://github.com/PaddlePaddle/PARL/tree/develop/parl/algorithms

**Comment by yufeng-Lu520** [comment]
> 

感谢，已经解决，再请教一个问题，在Visual studio里设置sac.py的断点但是没有断，如何在运行的时候debug在sac.py呢

**Comment by TomorrowIsAnOtherDay** [comment]
我们一般使用vim编辑器，不熟悉visual studio的断点debug功能，无法解答：）（另外，可以star下PARL 关注下后续更新）

**Comment by yufeng-Lu520** [comment]
> 
好的，感谢
