### ISSUE TITLE
DDPG策略网络输出问题

### ISSUE THREAD

**Issue by young-shy** [PaddlePaddle/PARL#899]
你好，请问如果DDPG的策略网络输出值主要边界值，可能是由于什么问题导致的呢？有什么较好的解决方法吗？

**Comment by TomorrowIsAnOtherDay** [comment]
这个问题可以参考下之前的issue：
https://github.com/PaddlePaddle/PARL/issues/462#issuecomment-736208491

**Comment by young-shy** [comment]
好的，我看这里相对于教程的ddpg模型有个不一样的操作就是 在经验池达到预存数据量之前均采用随机动作，这应该也是为了加强模型的探索性吧
![image](https://user-images.githubusercontent.com/71912372/172976023-298a5423-c5a2-48a8-b626-02f9093469af.png)

**Comment by TomorrowIsAnOtherDay** [comment]
是的，理解没问题：）

**Comment by young-shy** [comment]
thanks
