### ISSUE TITLE
example中MADDPG的动作输出是否像DDPG一样添加了噪音

### ISSUE THREAD

**Issue by ariesyy212** [PaddlePaddle/PARL#901]
在MADDPG例子文件中没有看到噪音的设置，如果没有涉及噪音的话，可以自己额外添加吗？

**Comment by TomorrowIsAnOtherDay** [comment]
探索其实是有，具体参考这里：
https://github.com/PaddlePaddle/PARL/blob/5fed2d393de0bbf41ebb6a81c7ff22d88853ee5a/parl/algorithms/paddle/maddpg.py#L129
不过这个写法确实不符合PARL的sample/predict风格，我们后续修改下，感谢反馈：）

**Comment by ShuaibinLi** [comment]
Fixed in PR https://github.com/PaddlePaddle/PARL/pull/942
