### ISSUE TITLE
请问图片经过卷积池化后得到的数据需要归一化或者标准化再输入到强化学习的网络中吗？

### ISSUE THREAD

**Issue by styledyy** [PaddlePaddle/PARL#902]

**Comment by TomorrowIsAnOtherDay** [comment]
目前大部分强化学习算法不需要归一化(layer_norm 或者batch_norm)也能达到论文效果的，所以这一操作不是必须的。

**Comment by RisingAuroras** [comment]
@TomorrowIsAnOtherDay  会不会因为目前常用的环境如atari或者mujoco 不是很复杂，所以不用layer_norm/batch_norm 也可以
