### ISSUE TITLE
“xparl start --port 6006”是否可以指定IP地址（电脑有多个网卡）？

### ISSUE THREAD

**Issue by EastSmith** [PaddlePaddle/PARL#906]
使用“xparl start --port 6006”可以启动一个主节点，然后另外电脑的使用 “xparl connect --address 192.168.0.12:6006”，即可把计算资源加入到主节点；

但是电脑有多个网卡，假定另外一个网卡的网段是 192.112.0.* ，我想在“xparl start --port 6006”时指定为这个“192.112.0.*”的网段，另外电脑也通过这个网段连接，是否有这样的命令参数？

**Comment by TomorrowIsAnOtherDay** [comment]
目前是通过python的socket包获取本机默认IP的，没有接口可以指定使用特定网卡的：）

**Comment by EastSmith** [comment]
好的，看来得想办法设置系统的默认网卡：）
