### ISSUE TITLE
这里第2个log_prob似乎跟第1个log_prob毫无关系

### ISSUE THREAD

**Issue by amocken** [PaddlePaddle/PARL#908]
https://github.com/PaddlePaddle/PARL/blob/develop/parl/algorithms/paddle/sac.py
那第一个log_prob的存在意义是啥？
![image](https://user-images.githubusercontent.com/48198083/174973429-b97748f2-76fd-47c9-b9de-d4dfb82d06d3.png)

**Comment by TomorrowIsAnOtherDay** [comment]
注意下81行的计算符号是【-=】，不是【=】，多了个减号

**Comment by amocken** [comment]
> 注意下81行的计算符号是【-=】，不是【=】，多了个减号

不好意思，是我大意了😅

**Comment by TomorrowIsAnOtherDay** [comment]
【狗头】
