### ISSUE TITLE
paddle，parl的版本问题？

### ISSUE THREAD

**Issue by LHT-Liu** [PaddlePaddle/PARL#910]
您好，我先使用的是pycharm，都直接搜不到paddlepaddle的版本是1.63的？想直接使用最新版本的库，还怎么操作呀？

**Comment by TomorrowIsAnOtherDay** [comment]
你的python 版本是？

**Comment by LHT-Liu** [comment]
> 你的python 版本是？

python版本：3.9
pycharm版本：2021.2.2

**Comment by TomorrowIsAnOtherDay** [comment]
https://github.com/PaddlePaddle/PARL/tree/develop/examples/tutorials#%E5%AE%89%E8%A3%85%E4%BE%9D%E8%B5%96%E6%B3%A8%E6%84%8F%E8%AF%B7%E5%8A%A1%E5%BF%85%E5%AE%89%E8%A3%85%E5%AF%B9%E5%BA%94%E7%9A%84%E7%89%88%E6%9C%AC
你得看这里的说明：python为3.6/3.7.
paddle1.63发行的时候，还没有py3.9，所以找不到是合理的。

**Comment by LHT-Liu** [comment]
> 

我看到了，就是我的python版本是3.9不可以是吗，必须下载一个3.6或者3.7是吧

现在有针对3.9的版本的paddlepaddle吗

**Comment by TomorrowIsAnOtherDay** [comment]
是的，如果需要按照指定版本的paddle（1.63），只能下载py3.6/3.7。建议你使用anaconda 安装低版本的python环境。

**Comment by LHT-Liu** [comment]
> 

明白了，我的意思是咱们这个paddlepaddle目前没有更新到3.9或者3.10版本吗？或者说以后paddlepaddle以后会适配更新版本的python吗？

**Comment by TomorrowIsAnOtherDay** [comment]
是这样的，paddle分静态图和动态图版本。静态图(1.x版本）从去年开始已经废弃，不再更新。
动态图版本(2.0+版本)目前一直在跟进和兼容最新python版本，3.9和3.10在支持计划中。

**Comment by LHT-Liu** [comment]
嗯嗯，我就是我下载的是2.x版本，就是动态图的吧，这个版本有对应的可以运行的例子吗？就是我不想下载3.6/3.7版本的python。这个版本有对应的学习的例子吗

**Comment by TomorrowIsAnOtherDay** [comment]
https://github.com/PaddlePaddle/PARL/tree/develop/examples/tutorials/parl2_dygraph
这个是对应动态图版本的，你可以运行试试看，有问题可以直接在这里交流：）
