### ISSUE TITLE
建议再提供一个动态调整温度系数的SAC版本

### ISSUE THREAD

**Issue by amocken** [PaddlePaddle/PARL#911]
我看目前parl提供的SAC算法框架的温度系数是固定的，但SAC的论文提供了动态调整温度系数的方法，希望parl也提供一下动态调整温度系数的版本

**Comment by TomorrowIsAnOtherDay** [comment]
我们之前测试过动态调整的版本，在mujoco上还是不如手动调整的效果好，所以只开源了目前的版本。

**Comment by amocken** [comment]
> 我们之前测试过动态调整的版本，在mujoco上还是不如手动调整的效果好，所以只开源了目前的版本。

好吧
