### ISSUE TITLE
关于paddle奖励设置问题

### ISSUE THREAD

**Issue by young-shy** [PaddlePaddle/PARL#912]
请问paddle库 有算法是对奖励值进行了归一化处理吗？

**Comment by TomorrowIsAnOtherDay** [comment]
你具体指的是哪个工作（算法）呢？

**Comment by young-shy** [comment]
抱歉，来晚了。之前没太在意，因为看这里介绍说是paddle库进行了这样的处理，但是看代码并非都是如此，TD3就没有直接对reward就行这样的处理
![image](https://user-images.githubusercontent.com/71912372/175769264-2f784097-92b6-4fe5-a99c-a28617c17829.png)

**Comment by young-shy** [comment]
：）
