### ISSUE TITLE
在训练和验证时如何如何设置model.train()和model.eval()

### ISSUE THREAD

**Issue by tangmingkai** [PaddlePaddle/PARL#915]
在训练和验证时如何如何设置model.train()和model.eval(), 好像在algorithm里面没有设置

**Comment by TomorrowIsAnOtherDay** [comment]
目前我们是没有该接口的，这个需求已放在todo里面了，近期将会完成开发，感谢你的反馈。

**Comment by TomorrowIsAnOtherDay** [comment]
hello，这个API已经增加，目前可以在agent中直接调用。
https://parl.readthedocs.io/zh_CN/latest/apis/agent.html#parl.core.paddle.agent.Agent.eval
