### ISSUE TITLE
强化学习营第3节DQN训练报错 要求安装paddlepaddle 1.6.3

### ISSUE THREAD

**Issue by libxing** [PaddlePaddle/PARL#923]
1.6.3已经被删了 python3.6 3.7都无法安装，尝试安装paddlepaddle 1.7.0 可以正常运行 给后来人一条正确路子

**Comment by A5230171** [comment]
> 

我刚刚看了一下，他们PARL团队后面有基于PaddlePaddle2.0的动态图版本做了新的教程范例。
链接如下：
https://github.com/PaddlePaddle/PARL/tree/develop/examples/tutorials/parl2_dygraph
可以看看

**Comment by libxing** [comment]
> 

谢谢！
