### ISSUE TITLE
PPO 通过修改配置降低显存占用

### ISSUE THREAD

**Issue by Aganlengzi** [PaddlePaddle/PARL#928]
请问，https://github.com/PaddlePaddle/PARL/tree/develop/examples/PPO 是否可以通过修改配置降低显存占用？在一个芯片上单卡跑到Updates 400+ 时报out of memory了

**Comment by TomorrowIsAnOtherDay** [comment]
把batch_size调小一点？

**Comment by Aganlengzi** [comment]
多谢回复，已调到16训完

**Comment by TomorrowIsAnOtherDay** [comment]
可以star下PARL关注我们后续的研发：）
