### ISSUE TITLE
我用算法训练时出现Unhandled exception in thread started by  Error in sys.excepthook:

### ISSUE THREAD

**Issue by djjstyle** [PaddlePaddle/PARL#932]
‘Unhandled exception in thread started by 
Error in sys.excepthook:

Original exception was:’
请问这是什么原因？这对训练会有影响吗？

**Comment by TomorrowIsAnOtherDay** [comment]
这应该是程序结束时出现的吧？

**Comment by djjstyle** [comment]
> 这应该是程序结束时出现的吧？

不是，是在运行过程中出现的

**Comment by djjstyle** [comment]
> 这应该是程序结束时出现的吧？

请问这会影响算法的效果吗？

**Comment by TomorrowIsAnOtherDay** [comment]
你在运行PARL的哪个example 过程中出现的呢？

**Comment by djjstyle** [comment]
> 你在运行PARL的哪个example 过程中出现的呢？
PARL-develop\examples\tutorials\lesson2\q_learning还有PARL-develop\examples\DQN

**Comment by TomorrowIsAnOtherDay** [comment]
不影响。我们这两个example没有多线程。
