### ISSUE TITLE
请问这个错误该如何处理（新手，求详细）

### ISSUE THREAD

**Issue by QIU1015** [PaddlePaddle/PARL#933]
AssertionError                            Traceback (most recent call last)
<ipython-input-7-c496be4ddbdb> in <module>()
     18 import turtle
     19 import numpy as np
---> 20 assert gym.__version__ == "0.18.0", "[Version WARNING] please try `pip install gym==0.18.0`"
     21 # turtle tutorial : https://docs.python.org/3.3/library/turtle.html
     22 

AssertionError: [Version WARNING] please try `pip install gym==0.18.0`

**Comment by TomorrowIsAnOtherDay** [comment]
这不是提示很明显了吗？执行下面的安装命令。
pip install gym==0.18.0
