### ISSUE TITLE
clarification of environments used in A2C algorithm

### ISSUE THREAD

**Issue by TomorrowIsAnOtherDay** [PaddlePaddle/PARL#94]
Currently we are using `envname`&`NoFrameSkip-v4` for training.
https://github.com/PaddlePaddle/PARL/blob/ee3e8dc2ab2286512405b6b0bb00bdb8e43fca44/examples/A2C/a2c_config.py#L21
We should add more details in READEME for users to make sure that they use the actual environments.

**Comment by TomorrowIsAnOtherDay** [comment]
note:
https://github.com/PaddlePaddle/PARL/blob/d18f19a92181d6edf049b8f2f22000f8c8d7512e/examples/A2C/atari_model.py#L17
this line should be removed.

**Comment by TomorrowIsAnOtherDay** [comment]
note2: 

Currently the command `tensorboard` cannot be found after installing `PARL` in Mac, and we should add fix this issue in our installation script.

**Comment by TomorrowIsAnOtherDay** [comment]
When users run the following code: 
```python
from parl.utils import logger
from parl.utils import tensorboard
import numpy as np
```
parl will not create any tensorbard files.

**Comment by TomorrowIsAnOtherDay** [comment]
note3:
refine the API `get_weights` of `parl.Model` so it return a dict like `parl.Algorithm` and `parl.Agent`.

**Comment by TomorrowIsAnOtherDay** [comment]
note4: 
use a CPU version of Paddle for checking the compatibility on CPU

**Comment by zenghsh3** [comment]
note5:
when creating too many actors: "zmq.error.ZMQError: Too many open files"

**Comment by TomorrowIsAnOtherDay** [comment]
All the environments use gym API now. I
