### ISSUE TITLE
并行接口不支持gbk

### ISSUE THREAD

**Issue by Wu-Jiayang** [PaddlePaddle/PARL#945]
![image](https://user-images.githubusercontent.com/62842862/185439645-66e616c3-c2d9-412f-aa11-76be705afb2f.png)
![image](https://user-images.githubusercontent.com/62842862/185439733-94e504f3-d58a-4f79-ad69-1b654118e89f.png)
版本：2.0.5

**Comment by TomorrowIsAnOtherDay** [comment]
hello，可以提供下你的系统信息以及python版本信息吗？

**Comment by Wu-Jiayang** [comment]
> hello，可以提供下你的系统信息以及python版本信息吗？

win10，Python3.8

**Comment by Wu-Jiayang** [comment]
> hello，可以提供下你的系统信息以及python版本信息吗？

@TomorrowIsAnOtherDay

**Comment by TomorrowIsAnOtherDay** [comment]
收到，我们找一台Windows笔记本定位下问题。

**Comment by Wu-Jiayang** [comment]
经检查可能是代码中存在中文注释的原因，除此之外好像还存在其他问题，稍后发上来
@TomorrowIsAnOtherDay

**Comment by TomorrowIsAnOtherDay** [comment]
好的，保持沟通：）

**Comment by Wu-Jiayang** [comment]
删除中文注释后问题解决，非常感谢

**Comment by TomorrowIsAnOtherDay** [comment]
感谢反馈，parl的并行需要把代码序列化打包后分发到多个机器上运行，如存在中文注释可能会引发序列化过程中的错误。
