### ISSUE TITLE
parl14个月没有一丝一毫更新

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/PARL#955]
看到parl仓库Code代码,几天就更新一次,搞不懂,为什么parl14个月没有一丝一毫更新?别的飞桨套件仓库都是3个月左右就更新一次.强化学习parl都没人用吗?issues总数量,新增数量也非常少.14个月不更新,实在忍不住了,心痒难耐,过来吐槽几句.请问parl管理人,这个仓库几时更新啊?这个仓库的根本目的是什么?打败所有强化学习仓库还是什么目的?我内心真心觉得,这个仓库的根本目的就是给parl建设者使用的,完全不是为了造福广大强化学习学者.
顶会中,强化学习的论文不少吧,有较大进步的论文不少吧,没一篇让parl看得上吗?
要说算法,我对于nnue算法最感兴趣,一个4层的超小网络,经过不用太多的GPU训练,随随便便吊打世界冠军,推理时,靠CPU就可以了,不用花大价钱购买GPU.我相信,你们没兴趣复现,只能吐槽一句.还有,我对于transformer应用于强化学习很感兴趣.
最后再说一句,我对parlC++训练感兴趣.

**Comment by TomorrowIsAnOtherDay** [comment]
PARL的研发记录请查看该页面：
https://github.com/PaddlePaddle/PARL/commits/develop
