### ISSUE TITLE
PPO-mujoco GPU训练reward曲线与CPU相差较大

### ISSUE THREAD

**Issue by USTCKAY** [PaddlePaddle/PARL#973]
python版本：3.7.0
环境：paddlepaddle-gpu     2.3.2
           parl                 2.0.5           /paddle/PARL
           gym                  0.18.0
           mujoco-py            2.1.2.14
          PyYAML               6.0
mujoco版本：210
GPU单卡训练，训练指令：python train.py --env 'HalfCheetah-v2' --continuous_action --train_total_steps 1000000
GPU rewards曲线：
![截屏2022-10-31 10 01 00](https://user-images.githubusercontent.com/50285351/199000728-7e2889be-65ff-428b-85ca-80bf9e7d4777.png)
CPU rewards曲线：
![截屏2022-10-31 19 48 11](https://user-images.githubusercontent.com/50285351/199001040-6ebc3c48-e56b-4625-ab10-cf74a13ec658.png)
可以看到，CPU的rewards能到达4000左右，与官方的结果相似，但GPU只能达到1600，与CPU结果相差较大。

更新：又用gpu跑了一遍，reward曲线似乎正常了
![截屏2022-11-01 14 30 10](https://user-images.githubusercontent.com/50285351/199174390-a13258a3-cf8a-4193-8aa9-8e2f88a108b6.png)

**Comment by TomorrowIsAnOtherDay** [comment]
感谢反馈，请问这是mujoco哪个任务呢？

**Comment by USTCKAY** [comment]
> 感谢反馈，请问这是mujoco哪个任务呢？

HalfCheetah-v2

**Comment by TomorrowIsAnOtherDay** [comment]
duplicated to #974
