### ISSUE TITLE
parl安装问题

### ISSUE THREAD

**Issue by Newman2022** [PaddlePaddle/PARL#983]
pip安装总是报错，不知道是什么原因，麻烦解答一下
![image](https://user-images.githubusercontent.com/113902395/201704187-b9095986-5e63-4240-b255-17fb8f201a8e.png)
![image](https://user-images.githubusercontent.com/113902395/201704382-f24d4177-b130-466e-831d-bbc522c8993e.png)

**Comment by TomorrowIsAnOtherDay** [comment]
hello，windows下建议使用anaconda配置python环境：）
