### ISSUE TITLE
请问如何指定gpu进行训练

### ISSUE THREAD

**Issue by zqx1609** [PaddlePaddle/PARL#984]
比如我机器上有8张卡，我想要指定'cuda:3'的卡进行训练而不是使用编号第一张的卡，要如何操作呢？

**Comment by TomorrowIsAnOtherDay** [comment]
可以设置环境变量，export CUDA_VISIBLE_DEVICES=2

**Comment by zqx1609** [comment]
https://copyfuture.com/blogs-details/20210122095423502Z 我之前看见这里说parl.agent类里面有变量self.place显示了当前设备，但是我自己写的时候这个变量并不存在，这个变量后来删除了吗

**Comment by TomorrowIsAnOtherDay** [comment]
你看的这个教程是静态图版本的，目前PARL已经全面支持动态图，没有这个变量了

**Comment by zqx1609** [comment]
谢谢，明白了
