### ISSUE TITLE
虽然但是关于PARL的文档好像有些疏漏

### ISSUE THREAD

**Issue by ZhangzrJerry** [PaddlePaddle/PARL#995]
在 https://parl.readthedocs.io/zh_CN/latest/tutorial/getting_started.html 中
![image](https://user-images.githubusercontent.com/87751816/203583631-a2666618-ef0d-46cb-b04d-7b4b3f07535e.png)
方法名和参数顺序出现了点bug

**Comment by ZhangzrJerry** [comment]
这里的快速开始例程好像很古早了

**Comment by TomorrowIsAnOtherDay** [comment]
十分感谢你的反馈！
已经提PR修复，见#996 （虽然这个PR ID有点特殊..

**Comment by ZhangzrJerry** [comment]
> 十分感谢你的反馈！ 已经提PR修复，见#996 （虽然这个PR ID有点特殊..

啊哈，谢谢你们的维护，祝你早点下班
